Cir234 draft
apache/doris pull request #10354
Opened 2022-06-23 03:55 UTC by englefly

# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-06-23 08:29 UTC, yiguolei commented on be/src/exec/tablet_sink.cpp
> +    if (row_no == RowBatch::INVALID_ROW_INDEX || _cur_batch->total_byte_size() > BATCH_SIZE_FOR_SEND) {
使用tuple pool的size 来计算

2022-06-23 08:30 UTC, yiguolei commented on be/src/exec/tablet_sink.h
> +        size_t v = _pending_batches_bytes;
这个不需要这么写

2022-06-23 08:36 UTC, yiguolei commented on be/src/vec/exec/volap_scan_node.cpp
> +                blocks.back()->rows() + block->rows() <= _runtime_state->batch_size() &&
这个地方可能不用

2022-06-23 09:03 UTC, englefly commented on be/src/exec/tablet_sink.cpp
> +    if (row_no == RowBatch::INVALID_ROW_INDEX || _cur_batch->total_byte_size() > BATCH_SIZE_FOR_SEND) {
done

2022-06-23 09:04 UTC, englefly commented on be/src/exec/tablet_sink.h
> +        size_t v = _pending_batches_bytes;
done

2022-06-23 09:32 UTC, englefly commented on be/src/vec/exec/volap_scan_node.cpp
> +                blocks.back()->rows() + block->rows() <= _runtime_state->batch_size() &&
将外层while循环的条件调整，遇到 raw_bytes_read >= raw_bytes_threshold  就推出循环，这样可以避免大宽表时生成巨大的block

2022-06-23 09:42 UTC, xinyiZzz commented on be/src/exec/tablet_sink.cpp
> +        if (_pending_batches_bytes>1073741824){
之后这里用 MemTracker 的值作为判断条件是不是更合适

2022-06-23 09:52 UTC, englefly commented on be/src/exec/tablet_sink.cpp
> +        if (_pending_batches_bytes>1073741824){
master版本可以

2022-06-23 11:11 UTC, yiguolei approved these changes
LGTM

2022-06-24 01:11 UTC, morningman requested changes
Need more test, holding

2022-06-24 02:55 UTC, morningman approved these changes
LGTM

2022-06-24 03:01 UTC, yiguolei approved these changes
LGTM

2022-06-24 03:02 UTC, merged