[multi-catalog]Fix hive partiton prune in hive and hudi exteranl table.
apache/doris pull request #10547
Opened 2022-07-01 09:49 UTC by SaintBacchus

# Proposed changes

Issue Number: close #10546

## Problem Summary:
`ExprBuilder` use stack to build the expr. 
The input order is : col, value and the output is value, col, but the `>=` is not reverse.
Example:
`col >=  1` => `1 >= col`

In this case, it's better use the queue to keeper the input order.

And also the `CompoundPredicate(OR)` have some problems,  it should be `alwaysTrue` whenever it's not a partiton key or it's not a supported op.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-07-02 04:04 UTC, morningman commented
It is strange that all exprs should pass the `NormalizeBinaryPredicatesRule`, and expr like `1 < col` should be converted to `col > 1` already.

2022-07-02 04:22 UTC, SaintBacchus commented
> It is strange that all exprs should pass the `NormalizeBinaryPredicatesRule`, and expr like `1 < col` should be converted to `col > 1` already.

it get the col,value and op expr one by one, and then compose they by fixed order. so it will cause issue

2022-07-05 06:43 UTC, morningman approved these changes

2022-07-05 06:43 UTC, morningman commented on fe/fe-core/src/main/java/org/apache/doris/planner/HudiScanNode.java
> +            hivePartitionPredicate = HiveMetaStoreClientHelper.convertToHivePartitionExpr(
We call `convertToHivePartitionExpr` twice in `HudiScanNode`.
I think the call in `getFileStatus()` can be removed?

2022-07-05 06:43 UTC, morningman commented on fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java
>              List<String> partitions, String tblName) throws DdlException {
```suggestion
            List<String> partitionKeys, String tblName) throws DdlException {
```

2022-07-05 06:43 UTC, morningman commented on fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java
> +        public ExprNodeGenericFuncDescContext() {
We can use a `static final` field to replace this constructor.

2022-07-05 06:43 UTC, morningman commented on fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java
> +            List<String> partitions, String tblName) throws DdlException {
```suggestion
            List<String> partitionKeys, String tblName) throws DdlException {
```

2022-07-05 06:43 UTC, morningman commented on fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java
> +                    ExprNodeGenericFuncDescContext left = convertToHivePartitionExpr(
```
                    ExprNodeGenericFuncDescContext left = convertToHivePartitionExpr(
                            compoundPredicate.getChild(0), partitions, tblName);
                    ExprNodeGenericFuncDescContext right = convertToHivePartitionExpr(
                            compoundPredicate.getChild(1), partitions, tblName);
```
This part can be extracted out of `switch case` block

2022-07-05 06:43 UTC, morningman commented on fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java
> +                        return new ExprNodeGenericFuncDescContext(genAlwaysTrueExpr(tblName));
I think it can just return `new ExprNodeGenericFuncDescContext()` ?

2022-07-05 07:25 UTC, morningman requested changes
need modify

2022-07-06 02:21 UTC, morningman approved these changes
LGTM

2022-07-06 02:22 UTC, merged