[enhancement] speed up week_of_year by pre_calc table
apache/doris pull request #10586
Opened 2022-07-04 08:16 UTC by englefly

# Proposed changes
select  count(LO_ORDERDATE)  FROM  lineorder  WHERE  weekofyear(LO_ORDERDATE)  =  6;
before: 13 sec
after: 19 sec
we make a static const uint8_t array week_of_year_table in VecDateTimeValue.
if the year is between [1950, 2029], we get the result from array week_of_year_table, otherwise calculate the result as before.

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-07-04 08:34 UTC, Gabriel39 reviewed
> before: 13 sec
> after: 19 sec

make slower?

2022-07-04 08:35 UTC, kpfly commented
Why does it have a negative impact on performance ？

2022-07-04 09:05 UTC, yiguolei submitted a review, later dismissed
LGTM

2022-07-04 09:14 UTC, englefly commented
> Why does it have a negative impact on performance ？



> Why does it have a negative impact on performance ？



> 



> > before: 13 sec
> > after: 19 sec
> 
> make slower?



> > before: 13 sec
> > after: 19 sec
> 
> make slower?

sorry，笔误

2022-07-04 09:15 UTC, Gabriel39 requested changes

2022-07-04 09:15 UTC, Gabriel39 commented on be/src/vec/runtime/vdatetime_value.cpp
> +        return week_of_year_table[value._year - 1950][value._month][value._day];
`mode` also needs to be considered

2022-07-04 11:29 UTC, englefly commented on be/src/vec/runtime/vdatetime_value.cpp
> +        return week_of_year_table[value._year - 1950][value._month][value._day];
in doris，mode is a hard-coded value 3.

2022-07-05 03:15 UTC, yiguolei approved these changes
LGTM

2022-07-05 07:37 UTC, merged