[feature-wip](nereids) Swap limit and project.
apache/doris pull request #12490
Opened 2022-09-08 14:26 UTC by Kikyou1997

# Proposed changes

Issue Number: noissue

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-09-09 02:12 UTC, morrySnow commented on fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/batch/RewriteJob.java
> +                .add(topDownBatch(ImmutableList.of(new SwapLimitAndProject())))
nit: rename to PushDownProjectThroughLimit

2022-09-09 04:17 UTC, wangshuo128 commented
Just curious, does BE support limit output before calculating projections inside a BE plan node currently?
Let's say we have a plan `limit -> project -> olap scan`. After applying the rule, it's rewritten to `project -> limit -> olap scan`.  
The translated plan would be `OlapScanNode(project and then limit)` or something else. If so, does BE support this plan(first limit and then project inside olap scan) currently? @Kikyou1997 @morrySnow

2022-09-09 06:41 UTC, morrySnow approved these changes

2022-09-09 06:45 UTC, morrySnow commented
> Just curious, does BE support limit output before calculating projections inside a BE plan node currently? Let's say we have a plan `limit -> project -> olap scan`. After applying the rule, it's rewritten to `project -> limit -> olap scan`. The translated plan would be `OlapScanNode(scan data from underlying olap scanners, limit and then project)` or something else. If so, does BE support this plan(firstly limit and then project inside olap scan) currently? @Kikyou1997 @morrySnow

This rule is rewrite `project -> limit` to `limit -> project`. The reason is we could get tree like `project -> limit -> project -> other node`. If we do not rewrite it. we could not merge the two project into one. And if we has more than one project on one node, the second one will overwrite the first one when translate. Then, be will core dump or return `slot cannot find` error.

2022-09-09 06:52 UTC, wangshuo128 commented
> > Just curious, does BE support limit output before calculating projections inside a BE plan node currently? Let's say we have a plan `limit -> project -> olap scan`. After applying the rule, it's rewritten to `project -> limit -> olap scan`. The translated plan would be `OlapScanNode(scan data from underlying olap scanners, limit and then project)` or something else. If so, does BE support this plan(firstly limit and then project inside olap scan) currently? @Kikyou1997 @morrySnow
> 
> This rule is rewrite `project -> limit` to `limit -> project`. The reason is we could get tree like `project -> limit -> project -> other node`. If we do not rewrite it. we could not merge the two project into one. And if we has more than one project on one node, the second one will overwrite the first one when translate. Then, be will core dump or return `slot cannot find` error.

ok, thanks. :)

2022-09-09 06:53 UTC, morrySnow requested changes

2022-09-09 06:53 UTC, morrySnow commented on fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/batch/RewriteJob.java
> +                .add(topDownBatch(ImmutableList.of(new PushdownLimitThroughProject())))
```suggestion
                .add(topDownBatch(ImmutableList.of(new PushdownProjectThroughLimit())))
```

2022-09-09 06:54 UTC, wangshuo128 commented
BTW, we'd better correct the PR title as well.

2022-09-09 07:59 UTC, morrySnow commented
> BTW, we'd better correct the PR title as well.

done😁

2022-09-13 05:24 UTC, morrySnow approved these changes

2022-09-13 05:26 UTC, merged