[Enhancement](optimize) optimize for insert_indices_from
apache/doris pull request #12807
Opened 2022-09-21 06:53 UTC by BiteTheDDDDt

# Proposed changes

for tpch Q5:

before:
![图片](https://user-images.githubusercontent.com/7939630/191434754-65968ad4-6712-4fb3-946e-cad875959292.png)
after:
![图片](https://user-images.githubusercontent.com/7939630/191434785-ca839cc7-32f4-4222-9e58-c2b9d9021f39.png)

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-09-21 08:14 UTC, adonis0147 commented on be/src/vec/columns/column_vector.cpp
> +        // nullmap : offset == -1 means is null at the here, set true here
Is the comment relevant? `offset` is missing here.

2022-09-21 08:14 UTC, adonis0147 commented on be/src/vec/columns/column_vector.cpp
> +        // real data : offset == -1 what at is meaningless
ditto

2022-09-26 12:17 UTC, HappenLee requested changes

2022-09-26 12:17 UTC, HappenLee commented on be/src/vec/columns/column_vector.cpp
> +            data[origin_size + i] = src_data[indices_begin[i]];
This is undefined behavior, and might break horribly

2022-09-26 12:19 UTC, HappenLee approved these changes
LGTM

2022-09-27 07:49 UTC, merged