[feature-wip] (recover) new recover ddl and support show dropped
apache/doris pull request #13067
Opened 2022-09-29 12:34 UTC by nextdreamblue

# Proposed changes

Issue Number: close #8421

## Problem summary

1. 当drop库、表、partition的时候，会放到回收站中，并且允许同名信息，通过库、表、partition的id来区分；
2. 增加show dropped命令，可以查看回收站中库、表、partition的信息，包括类型（db、table、partition）、名称、各级id（比如partition除了显示自身的id，还会显示所属库和表的id），删除时间等；
3. 支持recover的时候指定id去恢复，并且支持恢复到一个新名字；如果不指定id，存在多个同名对象时，会恢复最近一次删除的对象；

后续补充更详细的用户手册或文档、回归测试、测试用例等

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
4. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
5. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
6. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
7. Are there any changes that cannot be rolled back:
    - [x] Yes (If Yes, please explain WHY)
    - [ ] No

修改了与drop相关的journal信息保存的内容，导致不能回滚

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-10-14 09:41 UTC, hello-stephen commented
https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221014174110_clickbench_pr_29429.html

2022-10-14 14:01 UTC, morningman commented
I will review this PR

2022-10-15 15:01 UTC, nextdreamblue commented on fe/fe-core/src/main/cup/sql_parser.cup
> +    | KW_DROPPED opt_wild_where
ok, i will fix it

2022-10-15 15:04 UTC, nextdreamblue commented on fe/fe-core/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
> +            recycleTime = System.currentTimeMillis();
yes, sometimes recycleTime can change when fe restart before saving recycleTime to new image.

2022-10-15 15:17 UTC, nextdreamblue commented on fe/fe-core/src/main/java/org/apache/doris/analysis/ShowDroppedStmt.java
> +            .add("Type").add("Name").add("DbId").add("TableId").add("PartitionId").add("DropTime")
这个地方主要想让用户可以在一个查询中就能获取当前id的所属父id是谁，方便用户去区分同名咨询。比如说两个不同的database，每个database都删除过表test，通过上边的命令，就能看到两个不同的表test属于哪个database。否则很难通过一个过期的id去知道这个表曾经的信息。

2022-10-16 08:18 UTC, nextdreamblue commented on fe/fe-core/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
> +        eraseDatabaseWithSameId(db.getId());
my fault, i will fix it

2022-10-16 08:19 UTC, nextdreamblue commented on fe/fe-core/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
> +        RecycleDatabaseInfo databaseInfo = new RecycleDatabaseInfo(db, tableNames, tableIds);
嗯，后续所有判断都只通过tableIds来做，我优化一下这块逻辑

2022-10-16 09:01 UTC, nextdreamblue commented on fe/fe-core/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
> +                if (!Strings.isNullOrEmpty(newTableName)) {
ok, i fix it

2022-10-16 14:04 UTC, nextdreamblue commented on fe/fe-core/src/main/cup/sql_parser.cup
> +    KW_RECOVER KW_DATABASE ident:dbName opt_id:dbId opt_table_alias:alias
ok, i will fix it

2022-10-16 14:35 UTC, nextdreamblue commented on fe/fe-core/src/main/cup/sql_parser.cup
> +    KW_RECOVER KW_DATABASE ident:dbName opt_id:dbId opt_table_alias:alias
改了一版，发现这个地方如果不写表名的话，很多语法解析比如判断用户是否对该表名有权限很难做，只能从catalogrecyclebin中通过tableid获取到table后才能知道表名，然后才能回头再判断是否读该表有权限去恢复，这太绕了。不如让用户指定表名和id，成对的去恢复，对用户使用也没太大影响

2022-10-17 07:29 UTC, nextdreamblue commented on fe/fe-core/src/main/cup/sql_parser.cup
> +    KW_RECOVER KW_DATABASE ident:dbName opt_id:dbId opt_table_alias:alias
这块我建议保留现在的设计，让用户自己去输入name和id。只是通过id的话，改动的代码有点多，而且很绕

2022-10-26 02:55 UTC, morningman reviewed
LGTM, but please add some regression test for this feature.

2022-10-26 08:51 UTC, nextdreamblue commented
> LGTM, but please add some regression test for this feature.

add regression test done

2022-10-27 02:06 UTC, morningman approved these changes
LGTM

2022-10-27 04:01 UTC, morningman commented
Still has problem, do not merge
```
2022-10-27 11:56:46,614 WARN (leaderCheckpointer|78) [EditLog.loadJournal():919] [INCONSISTENT META] replay failed  opCode=10 org.apache.doris.persist.CreateTableInfo@55a89c38: errCode = 7, detailMessage = errCode = 2, detailMessage = unknown db, dbName=default_cluster:db1
org.apache.doris.common.MetaNotFoundException: errCode = 7, detailMessage = errCode = 2, detailMessage = unknown db, dbName=default_cluster:db1
	at org.apache.doris.datasource.InternalCatalog.replayCreateTable(InternalCatalog.java:1244) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.catalog.Env.replayCreateTable(Env.java:3171) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.persist.EditLog.loadJournal(EditLog.java:200) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.catalog.Env.replayJournal(Env.java:2457) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.master.Checkpoint.doCheckpoint(Checkpoint.java:124) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.master.Checkpoint.runAfterCatalogReady(Checkpoint.java:76) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.0-SNAPSHOT]
```

2022-10-27 04:02 UTC, morningman requested changes
some issue

2022-10-27 08:24 UTC, nextdreamblue commented
> Still has problem, do not merge
> 
> ```
> 2022-10-27 11:56:46,614 WARN (leaderCheckpointer|78) [EditLog.loadJournal():919] [INCONSISTENT META] replay failed  opCode=10 org.apache.doris.persist.CreateTableInfo@55a89c38: errCode = 7, detailMessage = errCode = 2, detailMessage = unknown db, dbName=default_cluster:db1
> org.apache.doris.common.MetaNotFoundException: errCode = 7, detailMessage = errCode = 2, detailMessage = unknown db, dbName=default_cluster:db1
> 	at org.apache.doris.datasource.InternalCatalog.replayCreateTable(InternalCatalog.java:1244) ~[doris-fe.jar:1.0-SNAPSHOT]
> 	at org.apache.doris.catalog.Env.replayCreateTable(Env.java:3171) ~[doris-fe.jar:1.0-SNAPSHOT]
> 	at org.apache.doris.persist.EditLog.loadJournal(EditLog.java:200) ~[doris-fe.jar:1.0-SNAPSHOT]
> 	at org.apache.doris.catalog.Env.replayJournal(Env.java:2457) ~[doris-fe.jar:1.0-SNAPSHOT]
> 	at org.apache.doris.master.Checkpoint.doCheckpoint(Checkpoint.java:124) ~[doris-fe.jar:1.0-SNAPSHOT]
> 	at org.apache.doris.master.Checkpoint.runAfterCatalogReady(Checkpoint.java:76) ~[doris-fe.jar:1.0-SNAPSHOT]
> 	at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) ~[doris-fe.jar:1.0-SNAPSHOT]
> 	at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.0-SNAPSHOT]
> ```

fix it, please try again

2022-10-27 10:08 UTC, hello-stephen commented
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.32 seconds
 load time: 572 seconds
 storage size: 17154644833 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221027180833_clickbench_pr_34730.html

2022-10-27 13:46 UTC, morningman approved these changes, later dismissed
LGTM

2022-10-28 02:39 UTC, hello-stephen commented
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.72 seconds
 load time: 558 seconds
 storage size: 17154655341 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221028023927_clickbench_pr_35041.html

2022-10-28 02:42 UTC, morningman approved these changes, later dismissed

2022-10-28 11:05 UTC, hello-stephen commented
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.91 seconds
 load time: 561 seconds
 storage size: 17154644846 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221028110500_clickbench_pr_35345.html

2022-10-31 09:44 UTC, morningman approved these changes
LGTM

2022-10-31 09:44 UTC, merged