[enhancement](storage) set the segment cache capacity according to the open file limit of the process
apache/doris pull request #13269
Opened 2022-10-11 02:27 UTC by liaoxin01

# Proposed changes

Issue Number: close #xxx

## Problem summary

Now segment_cache_capacity is 1000000, which usually exceeds open file limit. A large number of file descriptor will not be eliminated because of segment_cache_capacity is so large, resulting in too many open files errors. The client will receive -3109 error. 

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-10-11 02:35 UTC, dataroaring requested changes

2022-10-11 02:35 UTC, dataroaring commented on be/src/runtime/exec_env_init.cpp
> +    LOG(INFO) << "segment cache capacity: " << segment_cache_capacity;
log out fd_number here and print segment_cache_capacity = fd_number / 3 * 2.

2022-10-12 02:09 UTC, zhannngchen approved these changes
LGTM

2022-10-12 04:10 UTC, dataroaring approved these changes
LGTM

2022-10-12 04:10 UTC, merged