[function](string_function) add new string function 'not_null_or_empty'
apache/doris pull request #13418
Opened 2022-10-17 10:03 UTC by zy-kkk

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-10-17 10:42 UTC, BiteTheDDDDt requested changes
Need add test

2022-10-17 10:46 UTC, BiteTheDDDDt commented on be/src/vec/functions/function_string.h
> +            res_map->get_data();
We better check nullmap when input column is nullable.

2022-10-17 10:46 UTC, BiteTheDDDDt commented on be/src/vec/functions/function_string.h
> +            res_map->get_data();
line 444 seems unused

2022-10-17 10:47 UTC, BiteTheDDDDt commented on docs/zh-CN/docs/sql-manual/sql-functions/string-functions/not_null_or_empty.md
> +| null_or_empty(NULL) |
```suggestion
| not_null_or_empty(NULL) |
```

2022-10-17 11:07 UTC, zy-kkk commented on docs/zh-CN/docs/sql-manual/sql-functions/string-functions/not_null_or_empty.md
> +| null_or_empty(NULL) |
done

2022-10-17 11:08 UTC, zy-kkk commented
> Need add test

done

2022-10-17 14:04 UTC, BiteTheDDDDt commented on be/src/vec/functions/function_string.h
> +            res_map->get_data();
I mean, we can't guarantee that when the xth element of a ColumnNullable is null, it must have a length of 0.

2022-10-18 13:23 UTC, BiteTheDDDDt approved these changes
LGTM

2022-10-19 03:10 UTC, merged