Add column reader writer for segment V2
apache/doris pull request #1346
Opened 2019-06-21 02:17 UTC by imay

2019-06-24 06:49 UTC, kangpinghuang requested changes

2019-06-24 06:49 UTC, kangpinghuang commented on be/src/olap/rowset/segment_v2/column_reader.cpp
> +    // current offset when read this page
Is this argument start from 0 or 1?
It seems that it start from 1 here? Add some comment to describe it?

2019-06-24 06:49 UTC, kangpinghuang commented on be/src/olap/rowset/segment_v2/column_reader.cpp
> +            if (column_view.is_nullable()) {
if the column reader is not nullable, then will column_view.is_nullable can be true?

2019-06-24 06:49 UTC, kangpinghuang commented on be/src/olap/rowset/segment_v2/column_reader.cpp
> +    // TODO(zc): compress
```suggestion
    // TODO(zc): decompress
```

2019-06-24 06:49 UTC, kangpinghuang commented on be/src/olap/rowset/segment_v2/encoding_info.cpp
> +    static Status create_page_decoder(const Slice& data, PageDecoder** decoder) {
Here should add PageDecoderOptions?

2019-06-24 07:05 UTC, kangpinghuang requested changes

2019-06-24 07:05 UTC, kangpinghuang commented on be/src/olap/rowset/segment_v2/column_reader.cpp
> +#include "env/env.h" // for RleDecoder
for RandomAccessFile?

2019-06-24 07:31 UTC, imay commented on be/src/olap/rowset/segment_v2/encoding_info.h
> +        return _create_buidler_func(opts, builder);
OK

2019-06-24 07:47 UTC, imay commented on be/src/olap/rowset/segment_v2/encoding_info.cpp
> +    static Status create_page_decoder(const Slice& data, PageDecoder** decoder) {
I will add it when it is needed

2019-06-24 07:54 UTC, imay commented on be/src/olap/rowset/segment_v2/column_reader.cpp
> +        return Status::Corruption("Bad page, page size is too small");
I think we can print log in caller

2019-06-25 08:59 UTC, chaoyli approved these changes

2019-06-25 08:59 UTC, merged