[feature](running_difference) support running_difference function
apache/doris pull request #13737
Opened 2022-10-27 11:12 UTC by ZhangYiXi-dev

# Proposed changes

Issue Number: close #xxx

## Problem summary

Calculates the difference between successive row values ​​in the data block. Returns 0 for the first row and the difference from the previous row for each subsequent row.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-10-27 15:18 UTC, hello-stephen commented
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.34 seconds
 load time: 589 seconds
 storage size: 17154821198 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221027151845_clickbench_pr_34884.html

2022-10-28 02:29 UTC, zhangstar333 commented on be/src/vec/functions/function_running_difference.h
> +
maybe it's better to return true

2022-10-28 02:31 UTC, zhangstar333 commented on be/src/vec/functions/function_running_difference.h
> +
I see in ...functions.py file, you set return type is ALWAYS_NOT_NULLABLE, but here make_nullable

2022-10-28 02:36 UTC, Yukang-Lian requested changes
plz add regression-test and docs.

2022-10-28 02:36 UTC, Yukang-Lian commented on be/src/vec/functions/function_running_difference.cpp
> +}
plz remove redundant code.

2022-10-28 02:36 UTC, Yukang-Lian commented on be/test/vec/function/function_running_difference_test.cpp
> +
We need to add more ut to test different data types such as `float` and `date`.

2022-10-28 02:36 UTC, Yukang-Lian commented on gensrc/script/doris_builtins_functions.py
> +
we need to register other data types. As follows
```suggestion
[['running_difference'], 'FLOAT', ['FLOAT'],
        '',
        '', '', 'vec', 'ALWAYS_NOT_NULLABLE'],```

2022-10-28 03:08 UTC, hello-stephen commented
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 39.02 seconds
 load time: 555 seconds
 storage size: 17154699331 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221028030844_clickbench_pr_35046.html

2022-10-28 05:06 UTC, hello-stephen commented
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.77 seconds
 load time: 559 seconds
 storage size: 17154644859 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221028050643_clickbench_pr_35136.html

2022-10-31 02:41 UTC, dataroaring commented on be/src/vec/functions/function_running_difference.cpp
> +    //factory.register_function<FunctionCase<true, true>>();
Please remove useless comment.

2022-10-31 02:56 UTC, dataroaring commented on regression-test/suites/query_p0/sql_functions/math_functions/test_running_difference.sql
> +                                                   ('1', '2022-10-28', '2022-03-12 10:41:00', 1.4);
add null for test.

2022-10-31 02:56 UTC, dataroaring commented on regression-test/suites/query_p0/sql_functions/math_functions/test_running_difference.sql
> +                )
add a column not nullale.

2022-10-31 08:15 UTC, zhangstar333 commented on be/src/vec/functions/function_running_difference.h
> +    using DstFieldType = typename NumberTraits::ResultOfSubtraction<SrcFieldType, SrcFieldType>::Type;
now seems it's could remove

2022-11-01 03:08 UTC, Yukang-Lian submitted a review, later dismissed
LGTM

2022-11-07 09:30 UTC, dataroaring submitted a review, later dismissed
LGTM

2022-11-11 13:22 UTC, dataroaring approved these changes
LGTM

2022-11-11 13:22 UTC, merged

2022-11-13 08:48 UTC, HappenLee commented on be/src/vec/functions/function_running_difference.h
> +    bool use_default_implementation_for_constants() const override { return true; }
`use_default_implementation_for_constants` should be false.