[typo](docs)add udf doc and optimize udf regression test
apache/doris pull request #14000
Opened 2022-11-07 03:06 UTC by LemonLiTree

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-11-07 03:54 UTC, hello-stephen commented
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.91 seconds
 load time: 457 seconds
 storage size: 17177814414 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221107035451_clickbench_pr_40759.html

2022-11-08 01:25 UTC, Gabriel39 requested changes

2022-11-08 01:25 UTC, Gabriel39 commented on docs/zh-CN/docs/ecosystem/udf/java-user-defined-function.md
>  ## 暂不支持的场景
Update this part

2022-11-08 02:36 UTC, LemonLiTree commented on docs/zh-CN/docs/ecosystem/udf/java-user-defined-function.md
>  ## 暂不支持的场景
OK

2022-11-08 03:00 UTC, Gabriel39 approved these changes
LGTM

2022-11-10 01:24 UTC, merged