Add administrator guide of load
apache/doris pull request #1488
Opened 2019-07-16 11:53 UTC by EmmyMiao87

The catalogue of load docs:
+ load-manual.md
---- broker-load-manual.md
---- insert-into-manual.md
---- stream-load-manual.md

This commit also changes max/min_stream_load_timeout to max/min_load_timeout.
The old config named stream_load_timeout means the max timeout suited for all types of load.
So the config name has been changed.

2019-07-17 06:51 UTC, morningman requested changes
建议按照如下方式组织文档：

1. load-manual 中仅介绍 Doris 导入的一些总体概念，如
     * 针对批量导入设计，大致流程。
     * PENDING\ETL 这些状态。
     * 不介绍任何具体使用方式和参数


2. 在各自的文档中，详细介绍和对应导入方式相关的所有使用方式和配置参数，保证用户在一个文档内就能完全掌握对应的导入方式。
3. 每个导入文档可以在最开始提供一个demo，帮助用户可以跟着demo完成一次对应的导入操作。
4. 任何已经废弃的、或即将废弃的（如mini load, version v1 等），不提，或者引导用户使用新的方式。
5. 每种导入要给出最佳实践，比如适合的数据量、适用的场景、可能出现的问题和解决办法。

2019-07-17 06:51 UTC, morningman commented on docs/documentation/cn/administrator-guide/load-data/insert-into-manual.md
> ++ VALUES
要注明VALUES这种方式仅适用于导入几条数据作为demo，完全不适用于任何测试和生产环境。Doris 不合适单条导入的场景。请使用 Insert into select 进行批量导入

2019-07-19 03:01 UTC, EmmyMiao87 commented
1. 总文档中隐去transaction 的概念，用户不好理解。
2. 异步导入方式下，用户可以提交的最大job数量和同时能够running的job数量之间的关系，以及对应的两个配置要说明下（你只说了 desired\_max\_waiting\_jobs 这一个）
3. ROUTINE LOAD 也应该放到总体文档介绍
4. Stream load 中的列映射和转换方式介绍。

2019-07-25 13:01 UTC, morningman approved these changes

2019-07-25 13:02 UTC, merged