Fix timediff can't support time berfore 1970
apache/doris pull request #1600
Opened 2019-08-07 10:37 UTC by HangyuanLiu

Fix timediff can't support time berfore 1970
#1570

2019-08-07 11:23 UTC, morningman submitted a review, later dismissed
LGTM

2019-08-07 11:49 UTC, imay requested changes

2019-08-07 11:49 UTC, imay commented on be/src/exprs/timestamp_functions.cpp
> +    int day_diff = ts_value1.daynr() - ts_value2.daynr();
Can you encapsulate a function return seconds since 0000-01-01 in DateTimeValue?

2019-08-15 04:45 UTC, imay approved these changes
LGTM

2019-08-15 04:45 UTC, merged