[bugfix](disk balance) fix new rowset time check when add tablet
apache/doris pull request #16261
Opened 2023-01-30 11:56 UTC by yixiutt

In disk balancer, new rowset create time is same as old one, and when add tablet, there has a creation time check that new_time must bigger than old time, so disk balancer will always failed.

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-01-30 15:27 UTC, hello-stephen commented
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.05 seconds
 load time: 485 seconds
 storage size: 17123066570 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230130152659_clickbench_pr_87261.html

2023-01-31 02:27 UTC, yinzhijian requested changes
The _convert_rowset_ids in _gen_and_write_header_to_hdr_file modifies the createtime. If disk balance encounters a creation time that is the same, it could be because the modification of the time failed here.

2023-01-31 07:16 UTC, yinzhijian submitted a review, later dismissed
LGTM

2023-01-31 12:13 UTC, zhannngchen approved these changes, later dismissed
LGTM

2023-02-03 13:49 UTC, zhannngchen approved these changes

2023-02-03 13:49 UTC, merged