add kafka_default_offsets  when no partiotion specify .support read kafka partition from start
apache/doris pull request #1642
Opened 2019-08-14 09:28 UTC by wkhappy1

add kafka_default_offsets  when no partiotion specify
value OFFSET_BEGINNING,OFFSET_END

2019-08-14 11:55 UTC, imay requested changes

2019-08-14 11:55 UTC, imay commented on fe/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
> +    public static final String KAFKA_DEFAULT_OFFSETS="kafka_default_offsets";
```suggestion
    public static final String KAFKA_DEFAULT_OFFSETS = "kafka_default_offsets";
```

2019-08-14 11:55 UTC, imay commented on fe/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
> +    private String kafkaDefaultOffset="";
```suggestion
    private String kafkaDefaultOffset = "";
```

2019-08-14 11:55 UTC, imay commented on fe/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
> +        final String kafkaODefaultffsetsString = dataSourceProperties.get(KAFKA_DEFAULT_OFFSETS);
```suggestion
        final String kafkaDefaultOffsetsString = dataSourceProperties.get(KAFKA_DEFAULT_OFFSETS);
```

2019-08-14 11:55 UTC, imay commented on fe/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
> +                if(!kafkaDefaultOffSet.isEmpty()) {
```suggestion
                if (!kafkaDefaultOffSet.isEmpty()) {
```

2019-08-14 11:55 UTC, imay commented on fe/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
> +                    if(kafkaDefaultOffSet.equals(KafkaProgress.OFFSET_BEGINNING)) {
```suggestion
                    if (kafkaDefaultOffSet.equalsIgnoreCase(KafkaProgress.OFFSET_BEGINNING)) {
```

2019-08-14 11:55 UTC, imay commented on fe/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
> +                    }else if(kafkaDefaultOffSet.equals(KafkaProgress.OFFSET_END)) {
```suggestion
                    } else if (kafkaDefaultOffSet.equalsIgnoreCase(KafkaProgress.OFFSET_END)) {
```

2019-08-14 12:15 UTC, morningman requested changes

2019-08-14 12:15 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
> +                    }else if(kafkaDefaultOffSet.equals(KafkaProgress.OFFSET_END)) {
```suggestion
                    } else if(kafkaDefaultOffSet.equals(KafkaProgress.OFFSET_END)) {
```

2019-08-14 12:15 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
> +                    }else {
```suggestion
                    } else {
```

2019-08-14 12:15 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
> +                if(!kafkaDefaultOffSet.isEmpty()) {
```suggestion
                if (!kafkaDefaultOffSet.isEmpty()) {
```

2019-08-14 12:15 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
> +                    if(kafkaDefaultOffSet.equals(KafkaProgress.OFFSET_BEGINNING)) {
```suggestion
                    if (kafkaDefaultOffSet.equals(KafkaProgress.OFFSET_BEGINNING)) {
```

2019-08-15 07:46 UTC, imay submitted a review, later dismissed
LGTM

2019-08-15 08:22 UTC, morningman requested changes

2019-08-15 08:22 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
> +            kafkaDefaultOffSet = convertedCustomProperties.get(KAFKA_DEFAULT_OFFSETS);
```suggestion
            kafkaDefaultOffSet = convertedCustomProperties.remove(KAFKA_DEFAULT_OFFSETS);
```

convertedCustomProperties 中只能包含可以被 librdkafka 识别的properties，所以这个default offset 需要单独移除

2019-08-16 05:29 UTC, morningman approved these changes
LGTM

2019-08-16 05:30 UTC, merged