[bug](be) fix accept null predicate mem leak
apache/doris pull request #18510
Opened 2023-04-10 07:38 UTC by ByteYue

# Proposed changes

Issue Number: close #xxx
The former logic inside accept null predicate would cause memory leak.
## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-04-10 07:38 UTC, ByteYue commented
run buildall

2023-04-10 11:14 UTC, dataroaring submitted a review, later dismissed
LGTM

2023-04-10 11:18 UTC, xiaokang submitted a review, later dismissed
LGTM

2023-04-10 11:51 UTC, gavinchou commented on be/src/olap/accept_null_predicate.h
> +            auto original_flags_buf = std::make_unique<bool>(size);
Should it be `std::make_unique<bool[]>(size)`?

2023-04-10 11:51 UTC, gavinchou requested changes

2023-04-10 11:51 UTC, gavinchou commented on be/src/olap/accept_null_predicate.h
> +            auto original_flags_buf = std::make_unique<bool>(size);
Ditto

2023-04-10 11:57 UTC, ByteYue commented
run buildall

2023-04-11 01:07 UTC, yiguolei approved these changes
LGTM

2023-04-11 01:08 UTC, merged