[Improve](be)check swap
apache/doris pull request #18891
Opened 2023-04-21 07:00 UTC by zzzzzzzs

# Proposed changes

Check swap

## Problem summary

Check if swap is turned off

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-04-21 12:00 UTC, dataroaring requested changes

2023-04-21 12:00 UTC, dataroaring commented on bin/start_be.sh
> +    echo "Please disable swap partitioning before installation."
swap memory .

2023-04-21 12:40 UTC, zzzzzzzs commented on bin/start_be.sh
> +    echo "Please disable swap partitioning before installation."
OK

2023-09-02 14:56 UTC, dataroaring approved these changes
LGTM

2023-09-02 14:57 UTC, dataroaring commented
run buildall

2023-09-02 15:00 UTC, yujun777 approved these changes
LGTM

2023-09-04 01:28 UTC, hello-stephen commented
run clickbench

2023-09-04 02:09 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.02 seconds
 stream load tsv:          529 seconds loaded 74807831229 Bytes, about 134 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.9 seconds inserted 10000000 Rows, about 346K ops/s
 storage size: 17161923744 Bytes

2023-09-05 01:39 UTC, merged