[refactor](multi catalog)Refactor FileQueryScanNode init and finalize mothods.
apache/doris pull request #18954
Opened 2023-04-23 07:39 UTC by Jibing-Li

Refactor FileQueryScanNode init and finalize methods.
Handle schema related initialization in init method, handle scan range generation in finalize method.

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-04-23 11:12 UTC, morningman commented on fe/fe-core/src/main/java/org/apache/doris/planner/FileLoadScanNode.java
> +            setDefaultValueExprs(scanProvider, context.srcSlotDescByName, context.params);
I think this can be moved to `init`

2023-04-23 11:13 UTC, morningman approved these changes
LGTM

2023-04-23 11:13 UTC, morningman requested changes
Need to modify

2023-04-23 12:38 UTC, Jibing-Li commented
run buildall

2023-04-24 03:04 UTC, Jibing-Li commented
run buildall

2023-04-25 00:21 UTC, Jibing-Li commented
run buildall

2023-04-25 03:17 UTC, morningman approved these changes
LGTM

2023-04-25 03:18 UTC, merged