Support specifying inverted index columns when creating table
apache/doris pull request #1917
Opened 2019-09-30 07:24 UTC by wubiaoi

For #1865

2019-10-08 09:33 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/catalog/OlapTable.java
> +        // inverted index columns
Write invertedIndexColumns should after baseIndexId.

2019-10-08 09:33 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/catalog/OlapTable.java
> +        if (Catalog.getCurrentCatalogJournalVersion() >= FeMetaVersion.VERSION_64) {
should after baseIndexId.

2019-10-08 09:33 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/catalog/OlapTable.java
> +        if (Catalog.getCurrentCatalogJournalVersion() >= FeMetaVersion.VERSION_64) {
should after baseIndexId.

2019-10-08 09:34 UTC, kangkaisen commented
Please add UT and doc.

2019-10-08 09:35 UTC, kangkaisen commented
@wubiaoi  Hi, The schema change for invert index In BE is another PR?

2019-11-26 08:48 UTC, kangpinghuang requested changes
There are some problems.

2019-11-26 08:48 UTC, kangpinghuang commented on fe/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
> +        List<String> idxCols = COMMA_SPLITTER.splitToList(idxColsStr.toLowerCase());
I think this List is name, not idx, So I think colNames is a better name.

2019-11-26 08:48 UTC, kangpinghuang commented on fe/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
> +                if (column.isKey()) {
here,
if the table is a agg table, inverted index can only be used in key columns, not value columns;
if the table is duplicate table, inverted index can be used in both key and value;
if the table is unique table, inverted index can only be used in key column.

2019-11-26 08:48 UTC, kangpinghuang commented on fe/src/main/java/org/apache/doris/catalog/Catalog.java
> +            }
add a UT to test this logic?

2019-11-26 09:19 UTC, wubiaoi commented
`CREATE INDEX` and `DROP INDEX`  are more reasonable

2019-11-26 09:19 UTC, closed without merging