Support segment zone map
apache/doris pull request #1931
Opened 2019-10-04 08:53 UTC by liutang123

#1860  Support segment zone map and key range.

2019-10-04 08:59 UTC, liutang123 commented
cc @gaodayue support segment zone map.

2019-10-08 10:00 UTC, gaodayue requested changes

2019-10-08 10:02 UTC, gaodayue commented
Also note that `BetaRowset`, `Segment`, and `ColumnReader` should be thread safe but the current implementation is not. However I think this should be fixed in a separate PR.

2019-10-08 12:28 UTC, liutang123 commented on gensrc/proto/segment_v2.proto
> +    optional ZoneMapPB zone_map = 10;
`zone_map` is a field of `ColumnMetaPB`. Is `column_zone_map ` really better than `zone_map`?

2019-10-08 12:30 UTC, liutang123 commented on gensrc/proto/segment_v2.proto
> +    optional ZoneMapPB zone_map = 10;
id 9 was occupied by dict_page.

2019-10-11 15:16 UTC, imay commented on be/src/olap/rowset/segment_v2/segment.cpp
> +            ZoneMapPB c_zone_map = c_meta.zone_map();
```suggestion
            auto& c_zone_map = c_meta.zone_map();
```

2019-10-12 08:47 UTC, imay approved these changes
LGTM

2019-10-13 14:06 UTC, merged