[feature](compact) Duplicate with no keys tables compaction coredump
apache/doris pull request #19490
Opened 2023-05-10 07:15 UTC by herry2038

# Proposed changes

Issue Number: close #18621

## Problem summary

1. Duplicate with no keys tables when compaction will coredump;
2.Vitical compaction will build heap table to do compaction, it will be no need for duplicate no keys tables.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

2023-05-10 08:22 UTC, herry2038 commented
run buildall

2023-05-10 13:21 UTC, herry2038 commented
run buildall

2023-05-11 06:16 UTC, herry2038 commented
run buildall

2023-05-11 06:27 UTC, herry2038 commented
run buildall

2023-05-11 09:20 UTC, herry2038 commented
run compile

2023-05-14 12:46 UTC, dataroaring commented
run buildall

2023-05-16 13:52 UTC, dataroaring requested changes

2023-05-16 13:52 UTC, dataroaring commented on be/src/vec/olap/vertical_merge_iterator.cpp
> +                VerticalMergeIteratorContext* next_ctx = new VerticalMergeIteratorContext(
please use unique_ptr

2023-05-16 13:52 UTC, dataroaring commented on be/src/vec/olap/vertical_merge_iterator.h
> +    VerticalMergeIteratorContext* _cur_iter_ctx;
please use unique_ptr

2023-05-17 07:00 UTC, dataroaring approved these changes, later dismissed
LGTM

2023-05-17 07:01 UTC, dataroaring commented
run buildall

2023-05-17 09:14 UTC, dataroaring approved these changes
LGTM

2023-05-17 09:14 UTC, herry2038 commented
run buildall

2023-05-17 14:22 UTC, merged