[Feature](Nereids)support delete
apache/doris pull request #20452
Opened 2023-06-05 09:13 UTC by sohardforaname

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-06-06 03:57 UTC, sohardforaname commented
run buildall

2023-06-15 13:44 UTC, sohardforaname commented
run buildall

2023-06-16 02:40 UTC, morrySnow commented on fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
> +        (USING relation (COMMA relation)*)?
```suggestion
        USING relation (COMMA relation)*
```

2023-06-16 02:40 UTC, morrySnow commented on fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/DeleteCommand.java
> +        this.logicalQuery = logicalQuery;
ImmutableList.copyOf and Objects.requireNonNull

2023-06-16 06:46 UTC, sohardforaname commented
run buildall

2023-06-16 07:41 UTC, sohardforaname commented
run buildall

2023-06-16 08:27 UTC, sohardforaname commented
run buildall

2023-06-16 10:32 UTC, morrySnow approved these changes

2023-06-16 11:07 UTC, Kikyou1997 approved these changes

2023-06-16 11:08 UTC, morrySnow requested changes

2023-06-16 11:08 UTC, morrySnow commented on fe/fe-core/src/main/java/org/apache/doris/analysis/DeleteStmt.java
> -        }
why remove this?

2023-06-16 11:10 UTC, sohardforaname commented
run buildall

2023-06-18 04:23 UTC, morrySnow approved these changes

2023-06-18 08:22 UTC, merged