[enhancement](nereids) Sync stats across FE cluster after analyze
apache/doris pull request #21482
Opened 2023-07-04 08:24 UTC by Kikyou1997

## Proposed changes

Before this PR, if user connect to follower and analyze table, stats would not get cached in follower FE, since Analyze stmt would be forwarded to master, and in follower it's still lazy load to cache.

After this PR, once analyze finished on master, master would sync stats to all followers and update follower's stats cache

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-07-06 08:32 UTC, Kikyou1997 commented
run buildall

2023-07-06 11:42 UTC, Kikyou1997 commented
run buildall

2023-07-07 06:47 UTC, Kikyou1997 commented
run buildall

2023-07-07 10:22 UTC, Kikyou1997 commented
run buildall

2023-07-08 10:14 UTC, Kikyou1997 commented
run buildall

2023-07-08 10:16 UTC, Kikyou1997 commented
run buildall

2023-07-09 13:40 UTC, Kikyou1997 commented
run buildall

2023-07-10 03:28 UTC, Kikyou1997 commented
run buildall

2023-07-10 06:55 UTC, englefly submitted a review, later dismissed

2023-07-10 06:55 UTC, englefly commented on fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
> +    public final Map<Long, ColumnStatistic> partitionIdToColStats = new HashMap<>();
we need partition range. where can I get partition range by partition id?

2023-07-10 06:57 UTC, englefly commented on fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
> +            columnStatisticBuilder.setAvgSizeByte(columnStatisticBuilder.getCount() == 0 ?
it not proper to set avgSize=0 for empty table

2023-07-10 07:04 UTC, englefly requested changes

2023-07-10 07:04 UTC, englefly commented on fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
>                      / columnStatisticBuilder.getCount());
if we do not have schema info, leave it -1, and we could make up avgSize at computeScan().

2023-07-10 07:04 UTC, Kikyou1997 commented on fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
> +            columnStatisticBuilder.setAvgSizeByte(columnStatisticBuilder.getCount() == 0 ?
这不这么处理，这个地方就是NaN，现在Gson处理不了NaN，序列化会失败。你觉得不合适的原因是什么

2023-07-10 07:15 UTC, Kikyou1997 commented on fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
>                      / columnStatisticBuilder.getCount());
这个地方和schema info没什么关系，你这句话前后半句的关联是啥

2023-07-10 10:10 UTC, englefly approved these changes

2023-07-11 08:33 UTC, yiguolei approved these changes
LGTM

2023-07-11 08:34 UTC, yiguolei commented
run buildall

2023-07-11 12:09 UTC, merged