[enhancement](flush) make async flush status msg visible
apache/doris pull request #21530
Opened 2023-07-05 08:17 UTC by TangSiyang2001

## Proposed changes

When flushing memtable  failed, msg is invisible now, which is confused when locating problems.

Recording flush status with msg rather than simply record a status code.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-07-05 08:22 UTC, TangSiyang2001 commented
run buildall

2023-07-05 08:33 UTC, TangSiyang2001 commented
run buildall

2023-07-05 08:35 UTC, TangSiyang2001 commented
run buildall

2023-07-05 08:41 UTC, TangSiyang2001 commented
run buildall

2023-07-05 09:11 UTC, TangSiyang2001 commented
run buildall

2023-07-05 11:08 UTC, TangSiyang2001 commented
run buildall

2023-07-05 11:15 UTC, TangSiyang2001 commented
run click bench

2023-07-05 11:16 UTC, TangSiyang2001 commented
run click bench

2023-07-05 11:16 UTC, TangSiyang2001 commented
run click bench

2023-07-05 11:16 UTC, TangSiyang2001 commented
run clickbench

2023-07-05 11:19 UTC, dataroaring requested changes
LGTM

2023-07-05 11:19 UTC, dataroaring commented on be/src/olap/rowset/beta_rowset_writer.cpp
> +        return Status::Error<WRITER_DATA_WRITE_ERROR>(s.to_string());
keep the error code.

2023-07-05 15:57 UTC, TangSiyang2001 commented
run buildall

2023-07-06 00:24 UTC, TangSiyang2001 commented
run p0

2023-07-06 16:38 UTC, TangSiyang2001 commented
run build all

2023-07-06 16:39 UTC, TangSiyang2001 commented
run buildall

2023-07-07 01:48 UTC, TangSiyang2001 commented
run clickbench

2023-07-07 03:08 UTC, TangSiyang2001 commented
run buildall

2023-07-10 09:12 UTC, dataroaring approved these changes
LGTM

2023-07-10 09:13 UTC, freemandealer approved these changes
LGTM

2023-07-10 09:14 UTC, merged