[feature](partial update) support MOW partial update for insert statement
apache/doris pull request #21597
Opened 2023-07-06 15:15 UTC by bobhan1

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-07-06 15:16 UTC, bobhan1 commented
run buildall

2023-07-06 15:43 UTC, hello-stephen commented
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 51.08 seconds
 stream load tsv:          464 seconds loaded 74807831229 Bytes, about 153 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          56 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 insert into select:          68.5 seconds inserted 10000000 Rows, about 145K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230706154314_clickbench_pr_173882.html

2023-07-06 15:47 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 53.68 seconds
 stream load tsv:          509 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          87.1 seconds inserted 10000000 Rows, about 114K ops/s
 storage size: 17162618037 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230706234725_clickbench_pr_173884.html

2023-07-06 23:43 UTC, bobhan1 commented
run feut

2023-07-07 02:27 UTC, bobhan1 commented
run buildall

2023-07-07 02:28 UTC, bobhan1 commented
correctness_p0/test_sequence_col_default_value.groovy需要等https://github.com/apache/doris/pull/21592合入才能过

2023-07-07 02:54 UTC, hello-stephen commented
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.48 seconds
 stream load tsv:          460 seconds loaded 74807831229 Bytes, about 155 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          56 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 insert into select:          68.5 seconds inserted 10000000 Rows, about 145K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230707025434_clickbench_pr_174077.html

2023-07-07 02:59 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 53.13 seconds
 stream load tsv:          509 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         18 seconds loaded 2358488459 Bytes, about 124 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          87.8 seconds inserted 10000000 Rows, about 113K ops/s
 storage size: 17164073040 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230707105928_clickbench_pr_174068.html

2023-07-07 06:29 UTC, bobhan1 commented
run buildall

2023-07-07 06:57 UTC, hello-stephen commented
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.55 seconds
 stream load tsv:          453 seconds loaded 74807831229 Bytes, about 157 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          56 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 insert into select:          70.0 seconds inserted 10000000 Rows, about 142K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230707065702_clickbench_pr_174274.html

2023-07-07 09:16 UTC, bobhan1 commented
为什么一个列被定义为default null然后has_default_value()是false？如果这个不是bug的话需要https://github.com/apache/doris/pull/21623等合入。

2023-07-07 09:28 UTC, bobhan1 commented
run buildall

2023-07-07 09:48 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 52.97 seconds
 stream load tsv:          504 seconds loaded 74807831229 Bytes, about 141 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          86.6 seconds inserted 10000000 Rows, about 115K ops/s
 storage size: 17164221953 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230707174850_clickbench_pr_174408.html

2023-07-07 10:01 UTC, hello-stephen commented
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 52.4 seconds
 stream load tsv:          447 seconds loaded 74807831229 Bytes, about 159 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          56 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 insert into select:          69.6 seconds inserted 10000000 Rows, about 143K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230707100123_clickbench_pr_174420.html

2023-07-11 01:46 UTC, bobhan1 commented
run buildall

2023-07-11 02:52 UTC, hello-stephen commented
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.56 seconds
 stream load tsv:          446 seconds loaded 74807831229 Bytes, about 159 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          25.4 seconds inserted 10000000 Rows, about 393K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230711025211_clickbench_pr_176133.html

2023-07-11 03:43 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 54.92 seconds
 stream load tsv:          504 seconds loaded 74807831229 Bytes, about 141 MB/s
 stream load json:         18 seconds loaded 2358488459 Bytes, about 124 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.4 seconds inserted 10000000 Rows, about 352K ops/s
 storage size: 17162428055 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230711114337_clickbench_pr_176129.html

2023-07-17 14:08 UTC, dataroaring requested changes

2023-07-18 06:55 UTC, bobhan1 commented
run buildall

2023-07-18 23:48 UTC, bobhan1 commented
run buildall

2023-07-19 00:26 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 52.99 seconds
 stream load tsv:          505 seconds loaded 74807831229 Bytes, about 141 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17170269726 Bytes

2023-07-19 08:45 UTC, bobhan1 commented
run buildall

2023-07-19 09:19 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 50.33 seconds
 stream load tsv:          531 seconds loaded 74807831229 Bytes, about 134 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.7 seconds inserted 10000000 Rows, about 348K ops/s
 storage size: 17171164285 Bytes

2023-07-22 08:14 UTC, bobhan1 commented
run buildall

2023-07-22 08:57 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.24 seconds
 stream load tsv:          508 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.9 seconds inserted 10000000 Rows, about 346K ops/s
 storage size: 17162644569 Bytes

2023-07-23 03:43 UTC, dataroaring submitted a review, later dismissed
LGTM

2023-07-25 06:56 UTC, dataroaring commented
run buildall

2023-07-25 07:40 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.04 seconds
 stream load tsv:          506 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.9 seconds inserted 10000000 Rows, about 346K ops/s
 storage size: 17162337900 Bytes

2023-08-29 22:15 UTC, bobhan1 commented
run buildall

2023-08-30 01:21 UTC, bobhan1 commented
run buildall

2023-08-30 02:24 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.9 seconds
 stream load tsv:          551 seconds loaded 74807831229 Bytes, about 129 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.7 seconds inserted 10000000 Rows, about 348K ops/s
 storage size: 17162208875 Bytes

2023-09-08 08:08 UTC, bobhan1 commented
run buildall

2023-09-11 01:19 UTC, bobhan1 commented
run buildall

2023-09-11 05:57 UTC, bobhan1 commented
run clickbench

2023-09-13 03:34 UTC, bobhan1 commented
run buildall

2023-09-13 07:20 UTC, zhannngchen commented
Add more cases using `INSERT INTO SELECT`

2023-09-13 10:54 UTC, bobhan1 commented
run buildall

2023-09-13 11:54 UTC, zhannngchen commented on regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_native_insert_stmt.groovy
> +    def tableName6 = "test_partial_update_native_insert_stmt6"
We also need a case that have multiple key columns and user's statement only provide part of key columns.

2023-09-13 12:51 UTC, bobhan1 commented
run buildall

2023-09-13 12:52 UTC, zhannngchen submitted a review, later dismissed
LGTM

2023-09-13 13:29 UTC, bobhan1 commented
run buildall

2023-09-14 01:56 UTC, bobhan1 commented
run p0

2023-09-14 02:18 UTC, bobhan1 commented
run buildall

2023-09-14 02:23 UTC, zhannngchen approved these changes, later dismissed
LGTM

2023-09-14 02:39 UTC, bobhan1 commented
run buildall

2023-09-14 08:23 UTC, bobhan1 commented
run feut

2023-09-14 10:05 UTC, dataroaring submitted a review, later dismissed
LGTM

2023-09-14 10:16 UTC, bobhan1 commented
run buildall

2023-09-14 10:35 UTC, bobhan1 commented
run buildall

2023-09-14 10:41 UTC, morrySnow commented on fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
> +                    sendBatchParallelism, false, isInsertStrict, isInsertIgnore);
please add this feature to nereids' dml too

2023-09-14 13:32 UTC, xiaokang commented
run buildall

2023-09-14 13:47 UTC, bobhan1 commented
run buildall

2023-09-15 03:39 UTC, bobhan1 commented
run buildall

2023-09-15 04:14 UTC, bobhan1 commented
run buildall

2023-09-15 07:19 UTC, bobhan1 commented
run buildall

2023-09-15 08:01 UTC, bobhan1 commented
run buildall

2023-09-15 11:49 UTC, dataroaring approved these changes
LGTM

2023-09-16 09:11 UTC, xiaokang approved these changes
LGTM

2023-09-16 09:12 UTC, merged