[Fix](Nereids)fix file sink bug in add default limit rule.
apache/doris pull request #21830
Opened 2023-07-14 09:08 UTC by sohardforaname

## Proposed changes

Issue Number: close #xxx

FileSink should be always the top of a plan tree, we should override the visitor in add default limit rule.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-07-14 09:08 UTC, sohardforaname commented
run buildall

2023-07-14 09:41 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 51.8 seconds
 stream load tsv:          513 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          28.8 seconds inserted 10000000 Rows, about 347K ops/s
 storage size: 17163644145 Bytes

2023-07-17 12:47 UTC, morrySnow requested changes

2023-07-17 12:47 UTC, morrySnow commented on fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/AddDefaultLimit.java
> +    public LogicalPlan visitLogicalFileSink(LogicalFileSink<? extends Plan> sink, StatementContext context) {
should also update `ColumnPruning` and `StatsCalculator`

2023-07-19 03:32 UTC, sohardforaname commented
run buildall

2023-07-19 04:17 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 52.69 seconds
 stream load tsv:          511 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.8 seconds inserted 10000000 Rows, about 347K ops/s
 storage size: 17164820521 Bytes

2023-07-19 07:11 UTC, sohardforaname commented
run buildall

2023-07-19 13:41 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 53.2 seconds
 stream load tsv:          507 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.4 seconds inserted 10000000 Rows, about 340K ops/s
 storage size: 17161709786 Bytes

2023-07-20 04:51 UTC, sohardforaname commented
run buildall

2023-07-20 05:30 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.23 seconds
 stream load tsv:          511 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.6 seconds inserted 10000000 Rows, about 337K ops/s
 storage size: 17169589775 Bytes

2023-07-20 10:40 UTC, sohardforaname commented
run buildall

2023-07-20 11:48 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.61 seconds
 stream load tsv:          508 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17164099471 Bytes

2023-07-21 06:21 UTC, jackwener approved these changes

2023-07-21 10:21 UTC, morrySnow approved these changes

2023-07-21 10:22 UTC, merged