Persist sqlmode in load metadata and add sqlmode to forward master request
apache/doris pull request #2216
Opened 2019-11-15 12:17 UTC by xy720

ISSUE #2213 
This commit includes the following:
1. Persist sqlmode in load metadata so that it can be get to re-parse/re-analyze the querystmt when the routine/broker/stream load is replayed.
2. Add sqlmode as a param into forward master request so that non-leader node can transfer its sql mode to leader node when the request is send.

2019-11-15 14:06 UTC, morningman requested changes

2019-11-15 14:06 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
> +            sessionVariables.put(SessionVariable.SQL_MODE, "0");
Use a defined variable to replace "0" here, such as SQLMode.DEFAULT

2019-11-15 14:06 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
> +            sessionVariables.put(SessionVariable.SQL_MODE, "0");
Use a defined variable to replace "0" here

2019-11-15 14:06 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
> +    public Map<String, String> getSessionVariables() {
If there is no other place to call this get method, remove it.

2019-11-15 14:06 UTC, morningman commented on gensrc/thrift/FrontendService.thrift
> +    4: required i64 sqlMode
Add this sqlMode to the end. Better to keep the origin variables order.

2019-11-19 08:57 UTC, morningman approved these changes
LGTM

2019-11-19 08:58 UTC, merged

2019-11-19 09:20 UTC, imay commented on gensrc/thrift/FrontendService.thrift
> +    11: required i64 sqlMode
New added field should be optional.