[feature](Nereids): pushdown COUNT(*) through join
apache/doris pull request #22545
Opened 2023-08-03 06:39 UTC by jackwener

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-08-03 06:42 UTC, jackwener commented
run buildall

2023-08-03 07:13 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 44.96 seconds
 stream load tsv:          512 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17162068132 Bytes

2023-08-06 15:35 UTC, englefly approved these changes

2023-08-06 15:35 UTC, englefly commented on fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushdownCountThroughJoin.java
> + * Notice: when Count(*) exists, group by mustn't be empty.
please update this comments as we discussed

2023-08-06 15:35 UTC, englefly requested changes
How about count(1) ?

2023-08-07 01:07 UTC, starocean999 approved these changes

2023-08-07 01:48 UTC, englefly approved these changes

2023-08-07 04:53 UTC, merged