[enhancement](thirdparty) upgrade thirdparty libs
apache/doris pull request #23290
Opened 2023-08-21 20:52 UTC by xinyiZzz

## Proposed changes

protobuf 3.15.0 -> 21.11
glog 0.4.0 -> 0.6.0
lz4 1.9.3 -> 1.9.4
curl 7.79.0 -> 8.2.1
brpc 1.4.0 -> 1.6.0
zstd 1.5.2 -> 1.5.5
arrow 7.0.0 -> 13.0.0
abseil 20220623.1 -> 20230125.3
orc 1.7.2 -> 1.9.0
jemalloc for arrow 5.2.1 -> 5.3.0
xsimd 7.0.0 -> 13.0.0
opentelemetry-proto 0.19.0 -> 1.0.0
opentelemetry 1.8.3 -> 1.10.0

new:
c-ares  -> 1.19.1
grpc -> 1.54.3

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-08-22 07:20 UTC, xinyiZzz commented
run buildall

2023-08-22 07:50 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.71 seconds
 stream load tsv:          553 seconds loaded 74807831229 Bytes, about 129 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162299264 Bytes

2023-08-22 16:09 UTC, xinyiZzz commented
run buildall

2023-08-22 16:38 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.7 seconds
 stream load tsv:          537 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162073019 Bytes

2023-08-23 02:49 UTC, adonis0147 requested changes

2023-08-23 02:49 UTC, adonis0147 commented on thirdparty/vars.sh
> +BRPC_NAME="1.6.0.tar.gz"
```suggestion
BRPC_NAME="brpc-1.6.0.tar.gz"
```

2023-08-23 02:49 UTC, adonis0147 commented on thirdparty/vars.sh
> +XSIMD_NAME="9.0.1.tar.gz"
```suggestion
XSIMD_NAME="xsimd-9.0.1.tar.gz"
```

2023-08-23 02:49 UTC, adonis0147 commented on thirdparty/vars.sh
> +OPENTELEMETRY_PROTO_NAME=v1.0.0.tar.gz
```suggestion
OPENTELEMETRY_PROTO_NAME="opentelemetry-proto-v1.0.0.tar.gz"
```

2023-08-23 04:13 UTC, xinyiZzz commented
run buildall

2023-08-23 04:13 UTC, xinyiZzz commented on thirdparty/vars.sh
> +BRPC_NAME="1.6.0.tar.gz"
fix

2023-08-23 04:14 UTC, xinyiZzz commented on thirdparty/vars.sh
> +XSIMD_NAME="9.0.1.tar.gz"
fixed

2023-08-23 04:14 UTC, xinyiZzz commented on thirdparty/vars.sh
> +OPENTELEMETRY_PROTO_NAME=v1.0.0.tar.gz
fixed

2023-08-23 04:17 UTC, xinyiZzz commented
run buildall

2023-08-23 04:46 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 44.97 seconds
 stream load tsv:          554 seconds loaded 74807831229 Bytes, about 128 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.4 seconds inserted 10000000 Rows, about 340K ops/s
 storage size: 17162085456 Bytes

2023-08-23 06:04 UTC, adonis0147 approved these changes
LGTM

2023-08-23 12:24 UTC, morningman approved these changes
LGTM

2023-08-23 12:25 UTC, merged