Remove VersionHash used to comparison in BE
apache/doris pull request #2358
Opened 2019-12-03 04:06 UTC by chaoyli

2019-12-03 08:56 UTC, morningman requested changes

2019-12-03 08:56 UTC, morningman commented on be/src/olap/schema_change.cpp
> +    if (max_continuous_version.second > request.alter_version) {
```suggestion
    if (max_continuous_version.second >= request.alter_version) {
```

2019-12-04 01:57 UTC, imay approved these changes
LGTM

2019-12-04 12:08 UTC, morningman approved these changes
LGTM

2019-12-04 12:09 UTC, merged