[Enhancement](Column) Support int default value to int type column
apache/doris pull request #23594
Opened 2023-08-29 01:52 UTC by waywtdcc

## Proposed changes

Issue Number: close  #20670 #24125

## Further comments

Support int/bigint/decimal default value to int/bigint/decimal type column

2023-08-29 01:58 UTC, waywtdcc commented
run buildall

2023-08-29 03:15 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.86 seconds
 stream load tsv:          536 seconds loaded 74807831229 Bytes, about 133 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17161920510 Bytes

2023-08-31 02:52 UTC, waywtdcc commented
run buildall

2023-08-31 03:29 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.99 seconds
 stream load tsv:          540 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17162085244 Bytes

2023-09-01 07:34 UTC, zy-kkk reviewed
You should add new tests, including create, alter, insert into, stream load, and not modify the old ones. We need to ensure compatibility with the old behaviors

2023-09-01 08:26 UTC, waywtdcc commented
> You should add new tests, including create, alter, insert into, stream load, and not modify the old ones. We need to ensure compatibility with the old behaviors

Thanks for your review. I made a commit, is that right?

2023-09-04 00:29 UTC, waywtdcc commented
run buildall

2023-09-04 01:09 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 50.33 seconds
 stream load tsv:          530 seconds loaded 74807831229 Bytes, about 134 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162058782 Bytes

2023-09-09 07:17 UTC, TangSiyang2001 commented on regression-test/suites/load_p0/insert/test_insert_default_value.groovy
> +
Please add test case for stream load.

2023-09-13 03:30 UTC, waywtdcc commented
run buildall

2023-09-19 00:30 UTC, waywtdcc commented
@TangSiyang2001  @zy-kkk  hello,can you help me to review this pr?

2023-09-19 02:57 UTC, TangSiyang2001 approved these changes
LGTM

2023-09-27 07:49 UTC, zy-kkk submitted a review, later dismissed
LGTM

2023-09-27 07:51 UTC, zy-kkk commented
run buildall

2023-10-08 06:56 UTC, waywtdcc commented
Hi everyone, any questions? Can it be merged?

2023-10-18 02:12 UTC, waywtdcc commented
@TangSiyang2001 hello?Can this pr merge to master?

2023-12-19 11:19 UTC, zy-kkk approved these changes
LGTM

2024-02-20 01:36 UTC, waywtdcc commented
this pr can merged?

2024-03-20 13:57 UTC, dataroaring approved these changes
LGTM

2024-03-20 13:58 UTC, dataroaring commented
@waywtdcc Sorry for late reply, there are conflicts need to be resolved.

2024-03-20 14:09 UTC, morrySnow requested changes

2024-03-20 14:09 UTC, morrySnow commented on fe/fe-core/src/main/cup/sql_parser.cup
> +        RESULT = new ColumnDef.DefaultValue(true, value);
update Nereids' parser and CreateTableCommand too

2024-06-11 02:27 UTC, closed without merging