[enhancement](load) support dry_run_query for load
apache/doris pull request #23680
Opened 2023-08-30 12:43 UTC by dataroaring

If dry_run_query is set, a sink just discards blocks and do not send them to destination.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-08-30 12:43 UTC, dataroaring commented
run buildall

2023-08-30 13:00 UTC, freemandealer requested changes
pls modify the docs. It seems this dose not share the  same semantic with the original `dry_run_query` documented in [here](https://doris.apache.org/zh-CN/docs/dev/advanced/variables?_highlight=dry_run_query#%E6%94%AF%E6%8C%81%E7%9A%84%E5%8F%98%E9%87%8F)

2023-08-30 13:55 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.59 seconds
 stream load tsv:          550 seconds loaded 74807831229 Bytes, about 129 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17161874913 Bytes

2023-08-31 03:30 UTC, dataroaring commented
run buildall

2023-08-31 03:59 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.12 seconds
 stream load tsv:          543 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17162031087 Bytes

2023-09-02 06:34 UTC, dataroaring commented
run buildall

2023-09-02 07:39 UTC, hello-stephen commented
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.17 seconds
 stream load tsv:          530 seconds loaded 74807831229 Bytes, about 134 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.7 seconds inserted 10000000 Rows, about 348K ops/s
 storage size: 17162378704 Bytes

2023-09-02 14:35 UTC, Yukang-Lian approved these changes

2023-09-02 14:35 UTC, bobhan1 approved these changes

2023-09-02 14:35 UTC, yujun777 approved these changes
LGTM

2023-09-03 07:07 UTC, hf200012 approved these changes
LGTM

2023-09-03 07:08 UTC, merged