[fix](planner): do not use == to compare encapsulate type, use equals instead.
apache/doris pull request #24444
Opened 2023-09-15 08:05 UTC by xutaoustc

[fix](*): do not use == to compare encapsulate type, use equals instead.

for example, the following sample will lead to hard-to-find bugs

public class Wrapper {
public static void main(String[] args){
Integer i1 = 100;
Integer i2 = 100;
Integer i3 = 1000;
Integer i4 = 1000;
System.out.println(i1 == i2);
System.out.println(i1 != i2);
System.out.println(i3 == i4);
System.out.println(i3 != i4);
}
}

true
false
false
true

2023-09-15 12:47 UTC, SWJTU-ZhangLei approved these changes

2023-09-16 01:58 UTC, yiguolei approved these changes
LGTM

2023-09-16 01:58 UTC, yiguolei commented
run buildall

2023-09-18 01:47 UTC, morningman approved these changes
LGTM

2023-09-20 06:25 UTC, yiguolei commented
run buildall

2023-09-25 09:06 UTC, xutaoustc commented
run buildall

2023-12-30 13:26 UTC, yiguolei approved these changes

2023-12-30 13:27 UTC, yiguolei commented
run buildall

2024-01-06 09:35 UTC, yiguolei commented
run buildall

2024-06-27 06:55 UTC, dataroaring commented
run buildall

2024-06-27 07:03 UTC, morrySnow requested changes

2024-06-27 07:03 UTC, morrySnow commented on fe/fe-core/src/test/java/org/apache/doris/nereids/util/HyperGraphBuilder.java
> +            Boolean res = lv.equals(rv) && (lv != null) && (rv != null);
```suggestion
            Boolean res = (lv != null) && (rv != null) && lv.equals(rv);
```

2024-12-26 00:11 UTC, closed without merging