Colocate Join (#245)
apache/doris pull request #246
Opened 2018-10-18 09:14 UTC by kangkaisen

[For 245](https://github.com/apache/incubator-doris/issues/245)

Please review, Thanks!

**About Test**
I will add test later.

2018-10-19 06:32 UTC, imay commented on fe/src/com/baidu/palo/qe/SessionVariable.java
> +    public boolean isDisableColocateJoin()
{ should in the same line
public boolean isDisableColocateJoin() {

2018-10-19 06:52 UTC, imay requested changes
some code style case

The code is a bit more, take a closer look at the logic later.

2018-10-19 06:52 UTC, imay commented on gensrc/thrift/PaloInternalService.thrift
> +  28: optional bool disable_colocate_join = false;
This flag is useless to BE, no need to add this option

2018-10-19 06:52 UTC, imay commented on fe/src/com/baidu/palo/planner/HashJoinNode.java
> +    {
code style

2018-10-19 06:52 UTC, imay commented on fe/src/com/baidu/palo/planner/DistributedPlanner.java
> +
code style: 
should be one empty line

2018-10-19 06:52 UTC, imay commented on fe/src/com/baidu/palo/alter/DecommissionBackendJob.java
> +                          LOG.info("{} is colocate table, ColocateCloneChecker will handle the tablet clone", olapTable.getName());
LOG.info will produce too many log? 

change this to debug? or drop this log?

2018-10-19 06:52 UTC, imay commented on fe/src/com/baidu/palo/catalog/Catalog.java
> +                      ErrorReport.reportDdlException(ErrorCode.ERR_COLOCATE_TABLE_MUST_OLAP_TABLE);
code style: 
4 space indentation

2018-10-19 06:52 UTC, imay commented on fe/src/com/baidu/palo/clone/BackendInfo.java
> +public class BackendInfo
code style

2018-11-02 11:44 UTC, kangkaisen commented
Update this commit. 

Because the  change for latest code is big, I will do a full test on this weekend.

2018-11-07 06:55 UTC, imay submitted a review, later dismissed
You should update your commit log, change it to like "support colocate join" or something, And in the commit log body, you can add more detail about this feature. 

And there are code conflicts to be resolved

2018-11-07 08:20 UTC, kangkaisen commented
@imay  I have Updated the commit message and resolved the conflicts. please review. Thanks.

2018-11-07 10:00 UTC, imay requested changes

2018-11-07 10:12 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
> +        if (properties.size() == 1 && properties.containsKey(KEY_COLOCATE_WITH)) {
Currently, alter table colocate_with property need global ALTER Privilege.  so normal user  couldn't alter and we shouldn't grant  normal user  global ALTER Privilege.

2018-11-07 10:17 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/catalog/Catalog.java
> +
Yes. OK.

2018-11-07 10:17 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/catalog/Catalog.java
> +                        ErrorReport.reportDdlException(ErrorCode.ERR_COLOCATE_TABLE_MUST_SAME_BUCKNUM);
OK

2018-11-07 10:18 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/catalog/Catalog.java
> +                            ErrorReport.reportDdlException(ErrorCode.ERR_COLOCATE_TABLE_MUST_SAME_DISTRIBUTED_COLUMNS);
OK

2018-11-07 10:50 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/catalog/Catalog.java
> +                    }
Yes. I see.

I could merge `logColocateAddTable` and `logColocateBackendsPerBucketSeq` to one ,but `createTableWithLock` still have on log. how do we handle this better ?

2018-11-07 11:00 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/catalog/Catalog.java
> +    public void modifyTableColocate(Database db, OlapTable table, String colocateTable) throws DdlException {
1 schemaChangeHandler.process has kept  the db write lock, so we needn't add lock here.

2 OK, I will add a check

2018-11-07 11:14 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/planner/DistributedPlanner.java
> +            }
OK.

2018-11-07 11:15 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/planner/DistributedPlanner.java
> +                leftTable.getColocateTable().equalsIgnoreCase(rightTable.getColocateTable())) {
OK

2018-11-07 12:20 UTC, imay commented on fe/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
> +        if (properties.size() == 1 && properties.containsKey(KEY_COLOCATE_WITH)) {
Why? If one user have ALTER privilege for two tables, it's reasonable that he could make these two tables colocated.

2018-11-07 12:31 UTC, imay commented on fe/src/main/java/org/apache/doris/catalog/Catalog.java
> +                    }
We must keep metadata keep consistent. If one operation failed, we should guarantee that thing can still work.

Following is a suggest.

If we `createTableWithLock ` first, and log another operation `logChangeTableToColocate`.  And     if the second log failed, we also have complete meta, which have a table without colocate property. 

Can this method work and be implemented easily.

2018-11-08 02:29 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
> +        if (properties.size() == 1 && properties.containsKey(KEY_COLOCATE_WITH)) {
Yes.  it's reasonable user could later table colocate_with property. but require a global ALTER Privilege is not reasonable. normal users shouldn't have global ALTER Privilege, if they have, they will could read all dbs.  I tested it. So we should check db level Privilege not global Privilege.

2018-11-08 02:31 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/catalog/Catalog.java
> +                    }
I see. OK

2018-11-08 07:11 UTC, imay commented on fe/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
> +        if (properties.size() == 1 && properties.containsKey(KEY_COLOCATE_WITH)) {
Yes, you're right, I mistakenly thought that the DB privilege was checked before.

2018-11-08 07:14 UTC, imay commented
@kangkaisen 
Could you add some `help doc` to this PR, which help user to use this feature.

2018-11-08 07:31 UTC, kangkaisen commented
OK, I will add design doc  and help doc later.

2018-11-09 08:41 UTC, kangkaisen commented
Add help doc for colocate join.

2018-11-16 02:52 UTC, kangkaisen commented
Hi. @imay Is there any question about this PR?  If not, I will resolve the conflict and rebase the commit.

2018-11-16 02:57 UTC, imay commented
> Hi. @imay Is there any question about this PR? If not, I will resolve the conflict and rebase the commit.

Some things have hindered me, so I haven't reviewed yet. I will reply to you earlier next week?

2018-11-16 03:05 UTC, kangkaisen commented
OK，Thanks you.

2018-11-19 03:24 UTC, imay requested changes

2018-11-19 12:31 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/clone/ColocateTableBalancer.java
> +public class ColocateTableBalancer extends Daemon {
OK

2018-11-19 12:35 UTC, kangkaisen commented on fe/src/main/java/org/apache/doris/planner/OlapScanNode.java
> +                    tabletId2BucketSeq.put(id, allTabletIds.indexOf(id));
OK

2018-11-25 13:58 UTC, kangkaisen commented
Add more comment for `ColocateTableBalancer`

2018-12-05 02:53 UTC, kangkaisen commented
Rebase this commit.

2018-12-06 10:58 UTC, morningman approved these changes
LGTM, but I need a further review after merged

2018-12-06 10:58 UTC, imay approved these changes

2018-12-06 10:59 UTC, merged