Doris view support parenthesis
apache/doris pull request #253
Opened 2018-10-30 09:40 UTC by kangkaisen

### How to Reproduce
1 Create a view
```
create view test_view (id) as select (1 + 2) % 3 as id;
```
2 query the view
```
select * from test_view;
```
the result is 
```

id
--
3
```
The right result for this sql should be 0, not 3.

the result for `show create view`:
```
CREATE VIEW `test_view` AS SELECT 1 + 2 % 3 AS `id`;
```
we found the parenthesis in view has lost.

### How to solve

Refer to IMPALA-495 and IMPALA-4325

2018-11-02 08:20 UTC, kangkaisen commented
Update this commit

2018-11-05 15:17 UTC, imay approved these changes
LGTM

2018-11-05 15:20 UTC, imay requested changes
This PR have conflicts

2018-11-06 07:25 UTC, imay approved these changes

2018-11-06 07:25 UTC, merged