[Coverage](merge-on-write) add concurrent partial updates case for row store table
apache/doris pull request #25346
Opened 2023-10-12 06:56 UTC by bobhan1

## Proposed changes

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-10-12 06:56 UTC, bobhan1 commented
run buildall

2023-10-12 09:58 UTC, dataroaring submitted a review, later dismissed
LGTM

2023-10-12 10:01 UTC, liaoxin01 approved these changes
LGTM

2023-10-12 10:04 UTC, zhannngchen commented on regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_parallel.groovy
> +                PROPERTIES("replication_num" = "1", "enable_unique_key_merge_on_write" = "true", "store_row_column" = "true")
add sequence column

2023-10-12 11:18 UTC, bobhan1 commented
run buildall

2023-10-13 11:20 UTC, bobhan1 commented
run buildall

2023-10-13 11:26 UTC, zhannngchen submitted a review, later dismissed
LGTM

2023-10-16 03:10 UTC, bobhan1 commented
run buildall

2023-10-16 05:52 UTC, bobhan1 commented
run clickbench

2023-10-16 06:43 UTC, zhannngchen requested changes
Still have unfixed issues

2023-10-16 11:05 UTC, bobhan1 commented
run buildall

2023-10-16 13:35 UTC, dataroaring commented
run buildall

2023-10-17 01:18 UTC, bobhan1 commented
run p0

2023-10-17 02:45 UTC, bobhan1 commented
run p0

2023-10-17 02:45 UTC, bobhan1 commented
run clickbench

2023-10-17 04:14 UTC, zhannngchen commented on be/src/olap/tablet.cpp
> +            if (st.is<KEY_ALREADY_EXISTS>() && (!is_partial_update || have_input_seq_column)) {
Please also update the comment here, it's a little hard to understand for other devs

2023-10-17 05:20 UTC, bobhan1 commented
run buildall

2023-10-17 06:23 UTC, zhannngchen submitted a review, later dismissed
LGTM

2023-10-17 06:42 UTC, zhannngchen approved these changes, later dismissed
LGTM

2023-10-17 06:53 UTC, bobhan1 commented
run buildall

2023-10-17 08:28 UTC, bobhan1 commented
run p0

2023-10-17 09:07 UTC, bobhan1 commented
run p0

2023-10-17 09:12 UTC, bobhan1 commented
run buildall

2023-10-18 01:45 UTC, zhannngchen approved these changes
LGTM

2023-10-18 01:46 UTC, zhannngchen commented
run p0

2023-10-18 03:32 UTC, merged