(improvement)(multi-table) support multi table load
apache/doris pull request #25762
Opened 2023-10-23 07:05 UTC by HHoflittlefish777

## Proposed changes

support multi table load.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-10-23 07:05 UTC, HHoflittlefish777 commented
run buildall

2023-10-23 09:04 UTC, HHoflittlefish777 commented
run buildall

2023-10-25 03:01 UTC, HHoflittlefish777 commented
run buildall

2023-10-25 03:21 UTC, freemandealer commented on fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
innecessary change

2023-10-25 03:22 UTC, freemandealer requested changes

2023-10-25 03:22 UTC, freemandealer commented on be/src/pipeline/pipeline_fragment_context.cpp
> +        RETURN_IF_ERROR(
DCHECK request.__isset.desc_tbl

2023-10-25 03:28 UTC, HHoflittlefish777 commented
run buildall

2023-10-25 03:30 UTC, freemandealer approved these changes
LGTM

2023-10-25 06:13 UTC, HHoflittlefish777 commented
run clickbench

2023-10-25 13:28 UTC, dataroaring approved these changes
LGTM

2023-10-25 13:52 UTC, merged