[improvement](agg) speed up serialization of aggregation function collect_list/collect_set
apache/doris pull request #26467
Opened 2023-11-06 09:28 UTC by mrhhsg

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-11-06 09:28 UTC, mrhhsg commented
run buildall

2023-11-06 15:48 UTC, mrhhsg commented
run buildall

2023-11-08 07:31 UTC, yiguolei approved these changes
LGTM

2023-11-08 07:43 UTC, JackDrogon requested changes

2023-11-08 07:43 UTC, JackDrogon commented on be/src/agent/be_exec_version_manager.h
> +inline const int BeExecVersionManager::max_be_exec_version = 4;
why not use constexpr

2023-11-08 07:43 UTC, JackDrogon commented on be/src/vec/aggregate_functions/aggregate_function_collect.h
> +            if (version >= 4) {
what's the meaning of 4

2023-11-08 07:43 UTC, JackDrogon commented on be/src/vec/aggregate_functions/aggregate_function_collect.h
> +            if (version >= 4) {
too many special judge version >= 4, use factory method to refactor it

2023-11-24 10:13 UTC, closed without merging