[Improve](txn) Add some fuzzy test stub in txn
apache/doris pull request #26712
Opened 2023-11-09 13:34 UTC by deardeng

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-11-15 00:25 UTC, dataroaring commented
run buildall

2023-11-15 04:01 UTC, yujun777 requested changes

2023-11-15 04:01 UTC, yujun777 commented on fe/fe-core/src/main/java/org/apache/doris/alter/AlterJobV2.java
> +        if (DebugPointUtil.isEnable("FE.ALTER_JOB_V2_RUN")) {
boolean stop = DebugPointUtil.getDebugParamOrDefault(FE.ALTER_JOB_V2_RUN, "stop", false)

2023-11-15 04:21 UTC, yujun777 commented on fe/fe-core/src/main/java/org/apache/doris/alter/AlterJobV2.java
> +        if (DebugPointUtil.isEnable("FE.ALTER_JOB_V2_RUN")) {
use  if (DebugPointUtil.isEnable("FE.STOP_ALTER_JOB_RUN")) { return; }  ?

each point name should clear ?

2023-11-15 06:25 UTC, deardeng commented on be/src/olap/task/engine_publish_version_task.cpp
> +    DBUG_EXECUTE_IF("EnginePublishVersionTask.finish", {
fixed

2023-11-15 06:26 UTC, deardeng commented on fe/fe-core/src/main/java/org/apache/doris/alter/AlterJobV2.java
> +        long waitTimeMs = DebugPointUtil.isEnable(name) ? DebugPointUtil.getDebugParamOrDefault(name, 0) : 0;
fixed

2023-11-15 06:48 UTC, deardeng commented on fe/fe-core/src/main/java/org/apache/doris/alter/AlterJobV2.java
> +        if (DebugPointUtil.isEnable("FE.ALTER_JOB_V2_RUN")) {
fixed

2023-11-15 07:11 UTC, yujun777 approved these changes
LGTM

2023-11-15 12:26 UTC, dataroaring approved these changes
LGTM

2023-11-16 03:49 UTC, yiguolei approved these changes
LGTM

2023-11-16 03:50 UTC, merged