[enhancement](load) improve error msg for load when cancelled by mem gc
apache/doris pull request #26809
Opened 2023-11-11 09:47 UTC by freemandealer

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-11-11 09:49 UTC, freemandealer commented
run buildall

2023-11-12 05:45 UTC, freemandealer commented
run buildall

2023-11-13 15:03 UTC, dataroaring requested changes

2023-11-13 15:03 UTC, dataroaring commented on be/src/runtime/runtime_state.h
> +    std::string _cancel_reason;
please check thread safe.

2023-11-28 09:09 UTC, dataroaring approved these changes
LGTM

2023-11-28 09:28 UTC, CalvinKirs approved these changes

2023-11-28 09:36 UTC, merged