[enhancement](JNI) Provide default environment variables if it is unset
apache/doris pull request #27037
Opened 2023-11-15 08:29 UTC by zy-kkk

## Proposed changes

Issue Number: close #xxx

from #19041 
BE with java support needs some environment variables to start up and we have set them up in the start scripts (such as `start_be.sh`). However, if we debug BE directly, these environment variables are not set by default. For the convenience, we should provide default environment variables under this scenario.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-11-15 08:31 UTC, zy-kkk commented
run buildall

2023-11-15 08:37 UTC, adonis0147 requested changes

2023-11-15 08:37 UTC, adonis0147 commented on be/src/util/jni-util.cpp
> +
It is not suitable to use the environment `LD_LIBRARY_PATH`. This environment is usually used for test. You would better to use `-Djava.library.path` like the original snippet.

2023-11-15 09:09 UTC, adonis0147 requested changes

2023-11-15 09:09 UTC, adonis0147 commented on be/src/util/jni-util.cpp
> +    addJarsFromPath(std::string(doris_home) + "/custom_lib");
```suggestion
    add_jars_from_path(std::string(doris_home) + "/lib");
    add_jars_from_path(std::string(doris_home) + "/custom_lib");
```

2023-11-15 09:09 UTC, adonis0147 commented on be/src/util/jni-util.cpp
> +    auto addJarsFromPath = [&](const std::string& base_path) {
```suggestion
    auto add_jars_from_path = [&](const std::string& base_path) {
```

2023-11-15 09:09 UTC, adonis0147 commented on be/src/util/jni-util.cpp
> +    if (hadoop_conf_dir && *hadoop_conf_dir) {
```suggestion
    if (hadoop_conf_dir != nullptr && strlen(hadoop_conf_dir) > 0) {
```

2023-11-15 09:09 UTC, adonis0147 commented on be/src/util/jni-util.cpp
> +    std::string libhdfs_opts = fmt::format("{} -Djava.library.path={}/lib/hadoop_hdfs/native",
Should add the path `DORIS_HOME/lib` for `libz.so`.

2023-11-15 10:09 UTC, adonis0147 approved these changes

2023-11-15 10:11 UTC, zy-kkk commented
run buildall

2023-11-15 11:39 UTC, zy-kkk commented
run external

2023-11-16 02:16 UTC, zy-kkk commented
run buildall

2023-11-16 06:24 UTC, CalvinKirs approved these changes

2023-11-16 06:37 UTC, merged