[case](regression-test) add backup recovery for inverted index and bl…
apache/doris pull request #27616
Opened 2023-11-27 06:50 UTC by felixwluo

…oom filter

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-11-27 13:23 UTC, dataroaring submitted a review, later dismissed
LGTM

2023-11-28 02:28 UTC, w41ter approved these changes

2023-11-30 06:20 UTC, w41ter commented
run buildall

2023-11-30 06:20 UTC, w41ter approved these changes

2023-12-01 06:14 UTC, w41ter commented on regression-test/suites/backup_restore/test_backup_restore_bloom_filter.groovy
> +            `category_id` int NOT NULL
Exception:
java.sql.SQLException: errCode = 2, detailMessage = Syntax error in line 6:
        Duplicate KEY(`id`)
        ^
Encountered: DUPLICATE
Expected: COMMA

2023-12-01 06:38 UTC, w41ter commented on regression-test/suites/backup_restore/test_backup_restore_bloom_filter.groovy
> +	)
```suggestion
        )
```

2023-12-01 06:57 UTC, felixwluo commented
run buildall

2023-12-03 15:14 UTC, dataroaring submitted a review, later dismissed
LGTM

2023-12-04 02:23 UTC, w41ter requested changes

2023-12-04 02:23 UTC, w41ter commented on regression-test/suites/backup_restore/test_backup_restore_bloom_filter.groovy
> +            `saler_id` int NOT NULL,
Exception:
java.sql.SQLException: errCode = 2, detailMessage = Key columns should be a ordered prefix of the schema. KeyColumns[0] (starts from zero) is saler_id, but corresponding column is sale_date in the previous columns declaration.

2023-12-04 03:40 UTC, w41ter commented
run buildall

2023-12-04 07:29 UTC, felixwluo commented
run buildall

2023-12-05 02:53 UTC, dataroaring approved these changes
LGTM

2023-12-05 03:01 UTC, w41ter approved these changes

2023-12-05 09:11 UTC, merged