[feature](merge-on-write) enable merge-on-write by default again
apache/doris pull request #28105
Opened 2023-12-07 03:40 UTC by bobhan1

## Proposed changes

fix #27188, #28096

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-12-07 05:08 UTC, bobhan1 commented
run feut

2023-12-07 05:08 UTC, bobhan1 commented
run p0

2023-12-07 07:28 UTC, bobhan1 commented
run buildall

2023-12-07 08:45 UTC, zhannngchen approved these changes
LGTM

2023-12-08 03:06 UTC, bobhan1 commented
run buildall

2023-12-08 21:12 UTC, yiguolei commented
run buildall

2023-12-11 03:25 UTC, bobhan1 commented
run buildall

2023-12-11 09:34 UTC, bobhan1 commented
run buildall

2023-12-11 09:38 UTC, zhannngchen commented on regression-test/suites/update/test_update_unique.groovy
> +            DISTRIBUTED BY HASH(k) BUCKETS 5 properties("replication_num" = "1", "enable_unique_key_merge_on_write" = "false");
Why MoW can't work here?

2023-12-11 09:41 UTC, zhannngchen commented on regression-test/suites/schema_change_p0/test_schema_change.groovy
> +            PROPERTIES("replication_num" = "1", "light_schema_change" = "true", "enable_unique_key_merge_on_write" = "false");
ditto

2023-12-11 09:41 UTC, zhannngchen commented on regression-test/suites/schema_change_p0/test_rename_column.groovy
> +        PROPERTIES ( "replication_num" = "1" , "light_schema_change" = "false", "enable_unique_key_merge_on_write" = "false")
ditto

2023-12-11 09:42 UTC, zhannngchen requested changes
For each case that must use MOR, please add a comment to explain the reason.

2023-12-12 06:24 UTC, bobhan1 commented
run buildall

2023-12-12 07:01 UTC, bobhan1 commented
run buildall

2023-12-12 07:22 UTC, zhannngchen submitted a review, later dismissed
LGTM

2023-12-13 01:43 UTC, liaoxin01 commented on regression-test/suites/datatype_p0/datev1/test_datev1_common.groovy
> +    sql """set delete_without_partition=true; """
Is the delete partition behavior inconsistent between mow and mor？

2023-12-13 01:50 UTC, bobhan1 commented on regression-test/suites/datatype_p0/datev1/test_datev1_common.groovy
> +    sql """set delete_without_partition=true; """
从文档的描述来看似乎是mor表的行为有问题，这里删除条件推断不出来分区 https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/DELETE/
> 语法一中，如果为分区表，需要指定分区，如果不指定，doris 会从条件中推断出分区。两种情况下，doris 无法从条件中推断出分区: 1) 条件中不包含分区列；2) 分区列的 op 为 not in。当分区表未指定分区，或者无法从条件中推断分区的时候，需要设置会话变量 delete_without_partition 为 true，此时 delete 会应用到所有分区。

2023-12-13 02:53 UTC, liaoxin01 approved these changes
LGTM

2023-12-13 03:24 UTC, bobhan1 commented
run buildall

2023-12-13 08:07 UTC, bobhan1 commented
run buildall

2023-12-13 09:36 UTC, bobhan1 commented
run buildall

2023-12-13 11:25 UTC, bobhan1 commented
run external

2023-12-14 06:34 UTC, zhannngchen approved these changes
LGTM

2023-12-14 11:35 UTC, merged