Starts with
apache/doris pull request #2813
Opened 2020-01-20 06:53 UTC by Lishi-hub

Returns true whether string starts with the specified prefix, otherwise it returns false.

2020-01-20 06:58 UTC, HangyuanLiu commented
1、Please rename title, so as "Support starts_with function"?
2、Please relate this PR to issue

2020-01-20 06:59 UTC, HangyuanLiu requested changes

2020-01-20 06:59 UTC, HangyuanLiu commented on gensrc/script/doris_builtins_functions.py
> +            '_ZN5doris15StringFunctions11starts_withEPN9doris_udf15FunctionContextERKNS1_9StringValES6_'],
remove tab

2020-01-20 07:03 UTC, Lishi-hub commented on gensrc/script/doris_builtins_functions.py
> +            '_ZN5doris15StringFunctions11starts_withEPN9doris_udf15FunctionContextERKNS1_9StringValES6_'],
done

2020-01-20 15:47 UTC, imay approved these changes
LGTM

2020-01-21 06:08 UTC, HangyuanLiu approved these changes

2020-01-21 06:09 UTC, merged