[BUG](Meta) Fix fe exit by wrong dynamic properties
apache/doris pull request #28138
Opened 2023-12-07 12:00 UTC by liutang123

## Proposed changes

Issue Number: close #xxx
```
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:620) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:776) ~[?:?]
        at org.apache.doris.catalog.DynamicPartitionProperty.<init>(DynamicPartitionProperty.java:75) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.catalog.TableProperty.executeBuildDynamicProperty(TableProperty.java:115) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.catalog.TableProperty.buildProperty(TableProperty.java:82) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.catalog.Catalog.replayModifyTableProperty(Catalog.java:5646) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.persist.EditLog.loadJournal(EditLog.java:763) [palo-fe.jar:3.4.0]
        at org.apache.doris.catalog.Catalog.replayJournal(Catalog.java:2516) [palo-fe.jar:3.4.0]
        at org.apache.doris.catalog.Catalog$3.runOneCycle(Catalog.java:2299) [palo-fe.jar:3.4.0]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) [palo-fe.jar:3.4.0]
```

Prevent setting incorrect table properties

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-12-07 12:00 UTC, liutang123 commented
run buildall

2023-12-13 11:56 UTC, yujun777 commented on fe/fe-core/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
> +                && DynamicPartitionUtil.checkDynamicPartitionPropertiesAllValid(properties)) {
else if (DynamicPartitionUtil.checkDynamicPartitionPropertiesExist(properties)) {
         if (!DynamicPartitionUtil.checkDynamicPartitionPropertiesAllValid(properties)) {
               throws exception ...
        }
} ...

2023-12-13 12:02 UTC, yujun777 commented on fe/fe-core/src/main/java/org/apache/doris/catalog/TableProperty.java
> +                    valid = false;
should throw exception or  ignore unknown property here.

2023-12-13 12:04 UTC, yujun777 requested changes
Please add test case.

2024-06-09 16:29 UTC, liutang123 commented
run buildall

2024-06-10 06:15 UTC, liutang123 commented
run buildall

2024-06-11 17:41 UTC, liutang123 commented
run buildall

2024-06-12 01:51 UTC, dataroaring approved these changes
LGTM

2024-06-12 02:41 UTC, yujun777 approved these changes
LGTM

2024-06-14 06:20 UTC, merged