[opt](limit) cancel running fragments when query with limit is finished
apache/doris pull request #28384
Opened 2023-12-14 05:31 UTC by AshinGau

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-12-14 06:44 UTC, AshinGau commented
run buildall

2023-12-18 02:49 UTC, AshinGau commented
run buildall

2023-12-19 02:20 UTC, AshinGau commented
run buildall

2023-12-19 03:37 UTC, yiguolei requested changes
You can pick this PR to 2.0, but not merge to master. I am thinking about this case.

2023-12-19 06:23 UTC, AshinGau commented
run buildall

2023-12-22 11:23 UTC, closed without merging