Support not_empty function and empty function
apache/doris pull request #2911
Opened 2020-02-15 09:41 UTC by Lishi-hub

Support not_empty function 
Returns 0 for an empty string or 1 for a non-empty string.
#2593

Support empty function
Returns 1 for an empty string or 0 for a non-empty string. 
 #2592

2020-02-15 09:55 UTC, HangyuanLiu requested changes

2020-02-15 09:55 UTC, HangyuanLiu commented on be/src/exprs/string_functions.cpp
> +    }
```suggestion
    } else {
```

2020-02-15 09:55 UTC, HangyuanLiu commented on be/src/exprs/string_functions.cpp
> +    }
```suggestion
    } else {
```

2020-02-15 09:55 UTC, HangyuanLiu commented on be/src/exprs/string_functions.cpp
> +        return BooleanVal::null();
Considered non-empty if it contains at least one byte, even if this is a space or a null byte. The function should return true or false, not null.

2020-02-15 09:55 UTC, HangyuanLiu commented on gensrc/script/doris_builtins_functions.py
> +                    '_ZN5doris15StringFunctions5emptyEPN9doris_udf15FunctionContextERKNS1_9StringValE'],
```suggestion
             '_ZN5doris15StringFunctions5emptyEPN9doris_udf15FunctionContextERKNS1_9StringValE'],
```

2020-02-15 09:55 UTC, HangyuanLiu commented
Pleas Resolve confilicts

2020-02-16 13:05 UTC, morningman commented
Is it necessary to implement this function? Why not using `length(str) == 0`?

2020-02-17 02:31 UTC, HangyuanLiu commented
> Is it necessary to implement this function? Why not using `length(str) == 0`?
@morningman 
I think is necessary ,length(null) == null and empty(null) == 1. And empty(array) is necessary when we implement complex type

2020-02-17 13:56 UTC, morningman commented
> I think is necessary ,length(null) == null and empty(null) == 1. And empty(array) is necessary when we implement complex type

so maybe `null_or_empty` is better? like `Strings.isNullOrEmpty(xxx)` in Guava lib ?

2020-02-18 03:23 UTC, HangyuanLiu commented
> > I think is necessary ,length(null) == null and empty(null) == 1. And empty(array) is necessary when we implement complex type
> 
> so maybe `null_or_empty` is better? like `Strings.isNullOrEmpty(xxx)` in Guava lib ?

OK

2020-02-24 07:09 UTC, closed without merging