Add multi-ver olaptablesink for LOAD
apache/doris pull request #2956
Opened 2020-02-20 10:09 UTC by vagetablechicken

Ref #2780 

So we can use 
```
LOAD LABEL ...
        PROPERTIES 
        ( 
        "buffer_num"="5", 
        "mem_limit_per_buf"="5368709120", 
        "size_limit_per_buf"="62914560"
        );
```
to use multi-ver olaptablesink,  to accelerate the time-consuming load.

- [ ] add configuration references

- [ ] add doc

2020-02-20 14:46 UTC, morningman requested changes

2020-02-20 14:46 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
> +import com.google.common.base.Joiner;
Plz reorganize your imports order:

org.apache.doris
com
org
java
javax

2020-02-20 14:46 UTC, morningman commented on fe/src/main/java/org/apache/doris/planner/OlapTableSink.java
> +            if (memLimitPerBuf > 0)
warp with `{}`, even if there is only one line after `if`

2020-02-20 14:46 UTC, morningman commented on gensrc/thrift/DataSinks.thrift
> +    15: optional i32 buffer_num
Add some comment for these fields

2020-02-20 14:46 UTC, morningman commented on be/src/exec/tablet_sink.h
> +class RowBuffer {
Add some comments for this class

2020-03-10 03:58 UTC, vagetablechicken commented
After talking the matter over, we decided against this multi-thread version. I will submit a new design, just use one sender thread send batches asynchronously.
Thanks for the reviews!

2020-03-10 03:58 UTC, closed without merging