fix int128 bloom filter write bug
apache/doris pull request #2995
Opened 2020-02-26 04:02 UTC by kangpinghuang

issue #2994

2020-02-26 11:13 UTC, chaoyli submitted a review, later dismissed

2020-03-05 00:57 UTC, morningman approved these changes
LGTM

2020-03-05 01:05 UTC, morningman requested changes
Do we need unit test of test case for this bug?

2020-03-05 01:14 UTC, morningman approved these changes
LGTM

2020-03-05 01:15 UTC, merged