Support Amazon S3 data source in Broker Load
apache/doris pull request #3004
Opened 2020-02-26 14:35 UTC by frwrdt

issue  #3003

2020-02-26 14:50 UTC, chaoyli commented
Does access s3 need a SDK or dependent library?
This library may be incorporated into third-party

2020-02-26 15:13 UTC, HangyuanLiu requested changes

2020-02-26 15:13 UTC, HangyuanLiu commented on fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java
> +            } catch (Exception e) {
Why catch all exception

2020-02-26 15:13 UTC, HangyuanLiu commented on fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java
> +        String accessKey = properties.containsKey(FS_S3A_ACCESS_KEY) ? properties.get(FS_S3A_ACCESS_KEY) : "";
properties.getOrDefault ?

2020-02-26 15:13 UTC, HangyuanLiu commented on fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java
> +                AUTHENTICATION_SIMPLE);
Please keep indentation

2020-02-27 05:43 UTC, frwrdt commented on fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java
> +                AUTHENTICATION_SIMPLE);
ok

2020-02-27 05:43 UTC, frwrdt commented on fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java
> +        String accessKey = properties.containsKey(FS_S3A_ACCESS_KEY) ? properties.get(FS_S3A_ACCESS_KEY) : "";
ok

2020-02-27 05:44 UTC, frwrdt commented on fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java
> +            } catch (Exception e) {
should be 'IOException'

2020-02-27 06:05 UTC, frwrdt commented
> Does access s3 need a SDK or dependent library?
> This library may be incorporated into third-party



> Does access s3 need a SDK or dependent library?
> This library may be incorporated into third-party

There is no change in pom.xml and lib for be and fe. 
This pr just add hadoop-aws sdk in pom.xml for broker and there is no conflict in dependencies.

2020-03-01 03:56 UTC, HangyuanLiu approved these changes
LGTM

2020-03-01 04:53 UTC, imay approved these changes
LGTM

2020-03-01 04:53 UTC, merged