add broker load internal doc
apache/doris pull request #3013
Opened 2020-02-27 09:06 UTC by kangpinghuang

add a doc of broker load realization.

2020-02-27 10:08 UTC, EmmyMiao87 requested changes

2020-02-27 10:08 UTC, EmmyMiao87 commented on docs/documentation/cn/internal/broker_load.md
> +	在LoadLoadingTask任务下发之后，就会开始事务在BE的中执行，并且在BE中DeltaWriter会调用prepare_txn将事务进行持久化。如果所有的LoadLoadingTask quorum完成，则会认为该事务成功，会通过publish_version rpc向BE发送PublishVersionTask，进行事务的提交。
task quorum完成稍微可能会被误解，应该是导入涉及到的所有tablet都quorum完成

2020-02-27 10:14 UTC, imay requested changes

2020-02-27 10:14 UTC, imay commented on docs/documentation/cn/internal/broker_load.md
> +# Doris Broker导入实现解析
license header

2020-02-27 11:14 UTC, EmmyMiao87 commented on docs/documentation/cn/internal/broker_load.md
> +# Doris Broker导入实现解析
Long time no see, Doctor Zhao~

2020-02-29 14:41 UTC, kangkaisen commented
@kangpinghuang  Great doc. Thanks for your share.

2020-02-29 14:44 UTC, kangkaisen commented
One suggestion:
**Please remove the most of code, give the method name is enough，we should use language and picture to instead of the code.**

2020-03-01 03:00 UTC, morningman requested changes
建议整个 broker 导入主要重点介绍 FE 端的作业调度和任务生成部分。
BE端的 BrokerScanNode -> OlapTableSink 部分单独作为整个流式导入框架的BE端部分单独行程一篇文档。

2020-03-02 02:15 UTC, kangpinghuang commented on docs/documentation/cn/internal/broker_load.md
> +在Broker导入中，用户只要提供一份base表的数据，Doris会为用户进行一下处理：
ok

2020-03-02 02:16 UTC, kangpinghuang commented on docs/documentation/cn/internal/broker_load.md
> +- 用户将请求发送到FE，经过FE进行语法和语意分析，之后生成BrokerLoadJob
ok

2020-03-02 04:13 UTC, kangpinghuang commented on docs/documentation/cn/internal/broker_load.md
> +一个PlanFragment中包含多个ExecNode组成的树状执行计划（类型spark stage中包含的rdd），其中SinkNode(上面中的_sink变量)类型spark中带action操作的rdd，执行数据序列化操作，可能后续会进行持久化，也可能通过网络发送到下一个PlanFragment中。get_next_internal会调用PlanNode执行计划树获取数据，然后通过SinkN
ok，我修改一下

2020-06-10 03:08 UTC, closed without merging