[feature](merge-cloud) Add `CloudClusterChecker` to sync cluster info…
apache/doris pull request #30243
Opened 2024-01-22 13:35 UTC by deardeng

… in cloud

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-01-22 14:15 UTC, dataroaring commented
run buildall

2024-01-23 05:58 UTC, gavinchou requested changes

2024-01-23 05:58 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/system/SystemInfoService.java
> +    public Cloud.GetClusterResponse getCloudCluster(String clusterName, String clusterId, String userName) {
move it to cloudsysteminfo if it is only used in cloud mode

2024-01-23 05:58 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudEnv.java
> +    private CloudClusterChecker cloudClusterCheck;
consider put a cloudsysteminfo object into CloudEnv and CloudClusterChecker

2024-01-23 12:40 UTC, dataroaring commented
run buildall

2024-01-23 12:54 UTC, gavinchou approved these changes

2024-01-23 13:30 UTC, dataroaring approved these changes
LGTM

2024-01-23 15:49 UTC, merged