[feature](merge-cloud) add available clusters for load
apache/doris pull request #30340
Opened 2024-01-24 16:06 UTC by luwei16

2024-01-24 16:37 UTC, luwei16 commented
run buildall

2024-01-24 17:40 UTC, gavinchou requested changes

2024-01-24 17:40 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
> +    private LoadLoadingTask createAndInit(Database db, OlapTable table, List<BrokerFileGroup> brokerFileGroups,
just call it createLoadingTask()

2024-01-24 17:40 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/cloud/planner/CloudStreamLoadPlanner.java
> +            }
whats the difference between setCloudCluster() and setCloudCluster(cluster)
can we merge them into one method?
if not, changing the former one to another name like chooseCloudCluster() may avoid the confusion

2024-01-24 17:40 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
> +    public void setCloudCluster() {
pls add some commment here to desc what is going on

2024-01-24 17:40 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/cloud/load/loadv2/CloudBrokerLoadJob.java
> +        super();
this call is redundant

2024-01-24 17:40 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/cloud/load/loadv2/CloudBrokerLoadJob.java
> +    protected static final String CLUSTER_ID = "clusterId";
it seems to be confusing with the existing clusterid stored on BE.
is it better using cloudClusterId instead?

2024-01-25 06:54 UTC, luwei16 commented
run buildall

2024-01-25 07:12 UTC, luwei16 commented
run buildall

2024-01-25 15:45 UTC, gavinchou approved these changes

2024-01-25 15:45 UTC, gavinchou commented
run buildall

2024-01-25 15:51 UTC, luwei16 commented
run buildall

2024-01-26 01:51 UTC, luwei16 commented
run buildall

2024-01-26 02:08 UTC, dataroaring approved these changes
LGTM

2024-01-26 06:38 UTC, merged