[feature](merge-cloud) Fix cloud cluster checker cant get backends
apache/doris pull request #30467
Opened 2024-01-27 12:40 UTC by deardeng

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-01-27 12:41 UTC, deardeng commented
run buildall

2024-01-27 13:03 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudClusterChecker.java
> +            LOG.info("get cluster info  clusterIds: {}", remoteClusterIdToPB);
th word "clusterIds" is redundant

2024-01-27 13:13 UTC, deardeng commented on fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudClusterChecker.java
> +            LOG.info("get cluster info  clusterIds: {}", remoteClusterIdToPB);
fixed

2024-01-27 14:50 UTC, deardeng commented
run buildall

2024-01-28 07:16 UTC, dataroaring approved these changes, later dismissed
LGTM

2024-01-28 07:19 UTC, gavinchou requested changes

2024-01-28 07:19 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudClusterChecker.java
>          LOG.info("daemon cluster get cluster info succ, current cloudClusterIdToBackendMap: {}",
this log should be in getcloudbackends()

2024-01-28 07:19 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudClusterChecker.java
> +                    + "cloud_unique_id={}, response={}", Config.cloud_unique_id, response);
this function should return here.

2024-01-28 07:19 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudClusterChecker.java
> +        } else {
eliminate `else` block to reduce indention

2024-01-29 02:21 UTC, deardeng commented
run buildadd

2024-01-29 07:00 UTC, gavinchou approved these changes

2024-01-29 09:26 UTC, dataroaring approved these changes
LGTM

2024-01-29 10:15 UTC, dataroaring commented
run buildall

2024-01-29 12:06 UTC, merged