[Spark load] FE creates spark load job and submits spark etl job
apache/doris pull request #3055
Opened 2020-03-09 02:28 UTC by wyb

1. Users create Spark load job through MySQL protocol. 
2. FE generates the config related to the etl job, writes it to the file named jobconfig.json, and submits a spark etl job. ISSUE #3010

2020-03-09 06:41 UTC, wangbo commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkLoadJob.java
> +    }
For the initial version test,maybe we can abort transaction here when the SparkLoadJob is done to keep job state final.

2020-03-09 06:44 UTC, wangbo commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
> +            createJobConfigFile(configDirPath, configFilePath, loadJobId, jobJsonConfig);
Here we need add a ```todo```, for clearing temporary file produced by SparkLoadJob. Such as config, or hive table

2020-03-09 06:46 UTC, wangbo commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
> +    private static final String APP_RESOURCE = PaloFe.DORIS_HOME_DIR + "/lib/spark-etl-1.0.0.jar";
maybe we can use Palo-Fe.jar just for the first test

2020-03-09 16:51 UTC, kangpinghuang requested changes

2020-03-09 16:51 UTC, kangpinghuang commented on fe/pom.xml
> +            <version>2.4.5</version>
add a variable for this version and the scala version.

2020-03-09 16:51 UTC, kangpinghuang commented on fe/src/main/java/org/apache/doris/analysis/LoadStmt.java
> +            if (entry.getKey().startsWith("bitmap_data")) {
add a const define for bitmap_data

2020-03-09 16:51 UTC, kangpinghuang commented on fe/src/main/java/org/apache/doris/analysis/LoadStmt.java
>                  dataDescription.setIsHadoopLoad(true);
should here be changed?

2020-03-11 01:37 UTC, imay requested changes
Add documents about how to use this function.

2020-03-11 01:37 UTC, imay commented on fe/src/main/java/org/apache/doris/analysis/EtlClusterWithBrokerDesc.java
> +    private Map<String, String> properties;
Is broker needed when cluster is specified?

2020-03-11 01:37 UTC, imay commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkLoadPendingTask.java
> +public class SparkLoadPendingTask extends LoadTask {
should add some comments about what has been done in this class.

2020-03-17 15:21 UTC, morningman reviewed
Could you add a doc or comment to describe the process flow of the spark load job?
It is not easy to review such a huge pull request.

2020-03-17 15:21 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
> +                        LOG.warn("update spark load job etl status fail. error: {}", e);
Better to print job id here

2020-03-17 15:21 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
> +public class SparkEtlJobHandler {
Add comment for this class.

2020-03-17 15:21 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
> +            return null;
Why not throw the exception?

2020-03-17 15:21 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
> +        } else if (etlJobState == State.FAILED || etlJobState == State.KILLED || etlJobState == State.LOST) {
Do we need to care about the difference of FAILED/KILLED or LOST?

2020-03-17 15:21 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkLoadPendingTask.java
> +                case RANDOM:
No need to support RANDOM. It is deprecated.

2020-03-17 15:21 UTC, morningman commented on fe/src/main/java/org/apache/doris/load/loadv2/etl/EtlJobConfig.java
> +
This GSON naming policy is `LOWER_CASE_WITH_UNDERSCORES`. But here you use CamelCase. Does it matter?

2020-03-18 06:55 UTC, wangbo commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
> +
1 support add hadoop queue
2 support user specify jars
3 support specify hive-site.xml
```suggestion
launcher.addSparkArg("--queue", "hadoop-queue");
launcher.addSparkArg("--jars", "a.jar,b.jar,c.jar");
launcher.addSparkArg("--files", "/spark-2.2/conf/hive-site.xml");
```

2020-03-18 06:56 UTC, wangbo commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
> +                .addAppArgs(configFilePath);
I think we'd better use spark cluster mode.
```suggestion
.setDeployMode("cluster");
```

2020-03-18 06:57 UTC, wangbo commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
> +                .addAppArgs(configFilePath);
I think we'd better use spark cluster mode.
`.setDeployMode("cluster");`

2020-03-18 06:58 UTC, wangbo commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
> +            Util.deleteDirectory(new File(configDirPath));
No delete here ,otherwise SparkEtl may not find the config file

2020-03-18 07:04 UTC, wangbo commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkLoadJob.java
> +        switch (status.getState()) {
I think we can print doris job id and spark appid here to connect doris's job to spark app.

2020-03-18 07:22 UTC, wangbo commented on fe/src/main/java/org/apache/doris/load/loadv2/SparkLoadPendingTask.java
> +    private EtlColumn createEtlColumn(Column column) {
I think it's better to add toString method here for LOG ,because it's hard to remote debug SparkEtlJob.

2020-05-19 04:31 UTC, closed without merging