[refactor-wip](FS) Use golang-like generator to replace FS's list interface
apache/doris pull request #31214
Opened 2024-02-21 08:37 UTC by ByteYue

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-02-21 08:54 UTC, gavinchou requested changes

2024-02-21 08:54 UTC, gavinchou commented on be/src/io/fs/file_system.h
> +struct FsListGenerator {
class?
and, an interface/base class should always have sufficient and clear comments for all the functions.

consider naming FsListGenerator -> FileListIterator ?

2024-02-21 08:54 UTC, gavinchou commented on be/src/io/fs/file_system.h
> +    virtual Status init() = 0;
what is init() for? subclass should be initialized when it is created, we dont need to call baseclass.init().

2024-02-21 08:54 UTC, gavinchou commented on be/src/io/fs/file_system.h
> +    Result<FileInfo> next() {
just make it pure virtual and eliminate `generageNext()`,
calling it here is not a good design.

2024-02-21 08:54 UTC, gavinchou commented on be/src/io/fs/file_system.h
> +    FileInfo file_info;
what's this for ? cache?

2024-02-21 09:44 UTC, yiguolei commented
Any benifits for this refactor?

2024-02-21 13:18 UTC, ByteYue commented
run buildall

2024-02-22 10:28 UTC, ByteYue commented
run buildall

2024-02-22 14:24 UTC, ByteYue commented
run buildall

2024-02-23 07:24 UTC, ByteYue commented
run buildall

2024-02-24 11:27 UTC, ByteYue commented
run buildall

2024-02-24 12:00 UTC, ByteYue commented
run buildall

2024-02-24 12:18 UTC, ByteYue commented
run buildall

2024-02-24 12:57 UTC, ByteYue commented
run buildall

2024-02-25 06:20 UTC, ByteYue commented
run buildall

2024-02-25 06:39 UTC, ByteYue commented
run buildall

2024-02-26 03:02 UTC, hello-stephen commented
run p0

2024-02-26 08:45 UTC, ByteYue commented
run buildall

2024-08-26 00:10 UTC, closed without merging