[feature](merge-cloud) Make MetaService compatible with selectdb cloud
apache/doris pull request #31620
Opened 2024-02-29 11:46 UTC by w41ter

## Proposed changes

Issue Number: close #xxx

An patch for brpc is added, to maintain compatibility between the old and new versions of the service, when modifying the package name of the proto file.

This patch adds a service option 'secondary_package_name', and the bRPC will add the service with the two package names.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-02-29 11:53 UTC, gavinchou requested changes

2024-02-29 11:53 UTC, gavinchou commented on cloud/src/meta-service/meta_server.cpp
> +    options.secondary_package_name = "selectdb";  // the package name of selectdb cloud.
make it an config option

2024-03-01 02:14 UTC, w41ter commented
run buildall

2024-03-01 06:50 UTC, w41ter commented
run buildall

2024-03-04 04:26 UTC, morningman commented on cloud/src/common/config.h
> +CONF_String(secondary_package_name, "selectdb");
the default should be empty.
And better to explain why need this config and how to use, for other opensource user who want to expand this service

2024-03-05 08:03 UTC, morningman approved these changes
LGTM

2024-03-05 14:52 UTC, gavinchou approved these changes

2024-03-06 12:57 UTC, morningman approved these changes
LGTM

2024-03-07 08:58 UTC, w41ter commented
run buildall

2024-03-07 12:36 UTC, dataroaring approved these changes
LGTM

2024-03-07 12:37 UTC, merged