[Fix](schema change) Fix schema change fault when add complex type column
apache/doris pull request #31824
Opened 2024-03-05 14:52 UTC by Yukang-Lian

Problem: An error is encountered when executing a schema change on a unique table to add a column with a complex type, such as bitmap, as documented in https://github.com/apache/doris/issues/31365

Reason: The error arises because the schema change logic erroneously applies an aggregation check for new columns across all table types, demanding an explicit aggregation type declaration. However, unique and duplicate tables inherently assume default aggregation types for newly added columns, leading to this misstep.

Solution: The schema change process for introducing new columns needs to distinguish between table types accurately. For unique and duplicate tables, it should automatically assign the appropriate aggregation type, which, for the purpose of smooth integration with subsequent processes, should be set to NONE.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-03-05 16:39 UTC, Yukang-Lian commented
run buildall

2024-03-05 16:42 UTC, dataroaring approved these changes, later dismissed
LGTM

2024-03-06 02:37 UTC, zhannngchen approved these changes, later dismissed
LGTM

2024-03-06 09:29 UTC, Yukang-Lian commented
run buildall

2024-03-22 12:19 UTC, morrySnow requested changes

2024-03-22 12:19 UTC, morrySnow commented on fe/fe-core/src/main/java/org/apache/doris/analysis/ColumnDef.java
> +        if (keysType == null || keysType == KeysType.AGG_KEYS) {
if u update logic here, u should update logic in `ColumnDefinition` too

2024-03-28 09:13 UTC, Yukang-Lian commented
run buildall

2024-04-01 08:51 UTC, Yukang-Lian commented
run buildall

2024-04-01 12:55 UTC, Yukang-Lian commented
run feut

2024-04-02 08:52 UTC, Yukang-Lian commented
run buildall

2024-04-08 04:00 UTC, luwei16 approved these changes

2024-04-08 07:18 UTC, morrySnow approved these changes

2024-04-08 09:07 UTC, zhannngchen approved these changes
LGTM

2024-04-08 09:08 UTC, merged