Add curdate/now function in fe
apache/doris pull request #3215
Opened 2020-03-27 08:09 UTC by HangyuanLiu

For #3179

2020-03-27 08:10 UTC, chaoyli commented
You should set 
![image](https://user-images.githubusercontent.com/44767902/77735389-6ce19980-7045-11ea-9aae-8e83ad487799.png)

2020-03-27 08:11 UTC, HangyuanLiu commented
OK

2020-03-27 10:11 UTC, kangkaisen requested changes
You should add a test to `ConstantExpressTest`

2020-03-28 01:15 UTC, kangkaisen approved these changes
+1. LGTM

2020-03-28 05:39 UTC, merged