[fix](merge-cloud) Add retry when create tablet meet kv conflict in c…
apache/doris pull request #32267
Opened 2024-03-14 13:33 UTC by deardeng

…loud mode

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-03-14 13:34 UTC, deardeng commented
run buildall

2024-03-15 02:23 UTC, deardeng commented
run buildall

2024-03-17 17:08 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/cloud/datasource/CloudInternalCatalog.java
> +                response = MetaServiceProxy.getInstance().createTablets(createTabletsReq);
Why the retry mechanism does not work? Is it not implemented?

2024-03-17 17:14 UTC, gavinchou requested changes

2024-03-17 17:14 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/cloud/datasource/CloudInternalCatalog.java
> +                response = MetaServiceProxy.getInstance().createTablets(createTabletsReq);
The check of line 509 may not work because the response may remain null.

2024-03-18 02:12 UTC, deardeng commented on fe/fe-core/src/main/java/org/apache/doris/cloud/datasource/CloudInternalCatalog.java
> +                response = MetaServiceProxy.getInstance().createTablets(createTabletsReq);
1.  这个rpc 漏掉retry了
2. 509的和其他rpc retry 写法一致的

2024-03-18 04:02 UTC, deardeng commented on fe/fe-core/src/main/java/org/apache/doris/cloud/datasource/CloudInternalCatalog.java
> +                response = MetaServiceProxy.getInstance().createTablets(createTabletsReq);
3. 确认了，ms create tablet 遇到kv 冲突，没有处理retry，直接返回的

2024-03-18 12:35 UTC, w41ter approved these changes

2024-03-19 14:11 UTC, dataroaring approved these changes
LGTM

2024-03-20 06:39 UTC, deardeng commented
run buildall

2024-03-20 14:28 UTC, gavinchou approved these changes

2024-03-20 14:30 UTC, merged