[Fix](grace-exit) Fix threadpool hang on grace exit
apache/doris pull request #33132
Opened 2024-04-01 13:08 UTC by zclllyybb

## Proposed changes

Issue Number: close #xxx

stack like:
```
Thread 641 (Thread 0x7f1d6e3ae700 (LWP 3912128) "WriteCooldownMe"):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x614009733320) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x614009733358, cond=0x6140097332f8) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x6140097332f8, mutex=0x614009733358) at pthread_cond_wait.c:647
#3  0x000056102fd56b0c in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>) at /data/gcc-11.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:865
#4  std::__condvar::wait (__m=..., this=<optimized out>) at /data/gcc-11.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/std_mutex.h:155
#5  std::condition_variable::wait (this=<optimized out>, __lock=...) at ../../../../../libstdc++-v3/src/c++11/condition_variable.cc:41
#6  0x0000560ff926a0de in doris::BlockingPriorityQueue<doris::WorkThreadPool<true>::Task>::blocking_get (this=0x6140097332f0, out=0x7f1d69b0b020, timeout_ms=0) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/util/blocking_priority_queue.hpp:70
#7  0x0000560ff9264f19 in doris::WorkThreadPool<true>::work_thread (this=0x614009733240, thread_id=0) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/util/work_thread_pool.hpp:156
#8  0x0000560ff9267665 in std::__invoke_impl<void, void (doris::WorkThreadPool<true>::* const&)(int), doris::WorkThreadPool<true>*&, int&> (__f=@0x604042fb1c98: (void (doris::WorkThreadPool<true>::*)(doris::WorkThreadPool<true> * const, int)) 0x560ff9264d80 <doris::WorkThreadPool<true>::work_thread(int)>, __t=@0x604042fb1cb0: 0x614009733240, __args=@0x604042fb1ca8: 0) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:74
#9  0x0000560ff9267527 in std::__invoke<void (doris::WorkThreadPool<true>::* const&)(int), doris::WorkThreadPool<true>*&, int&> (__fn=@0x604042fb1c98: (void (doris::WorkThreadPool<true>::*)(doris::WorkThreadPool<true> * const, int)) 0x560ff9264d80 <doris::WorkThreadPool<true>::work_thread(int)>, __args=@0x604042fb1ca8: 0, __args=@0x604042fb1ca8: 0) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:96
#10 0x0000560ff92674e7 in std::_Mem_fn_base<void (doris::WorkThreadPool<true>::*)(int), true>::operator()<doris::WorkThreadPool<true>*&, int&> (this=0x604042fb1c98, __args=@0x604042fb1ca8: 0, __args=@0x604042fb1ca8: 0) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/functional:131
#11 0x0000560ff92674a7 in std::__invoke_impl<void, std::_Mem_fn<void (doris::WorkThreadPool<true>::*)(int)>&, doris::WorkThreadPool<true>*&, int&> (__f=..., __args=@0x604042fb1ca8: 0, __args=@0x604042fb1ca8: 0) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
#12 0x0000560ff92673a9 in std::__invoke_r<void, std::_Mem_fn<void (doris::WorkThreadPool<true>::*)(int)>&, doris::WorkThreadPool<true>*&, int&> (__fn=..., __args=@0x604042fb1ca8: 0, __args=@0x604042fb1ca8: 0) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:111
#13 0x0000560ff92672d6 in std::_Bind_result<void, std::_Mem_fn<void (doris::WorkThreadPool<true>::*)(int)> (doris::WorkThreadPool<true>*, int)>::__call<void, , 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>) (this=0x604042fb1c98, __args=...) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/functional:570
#14 0x0000560ff9267130 in std::_Bind_result<void, std::_Mem_fn<void (doris::WorkThreadPool<true>::*)(int)> (doris::WorkThreadPool<true>*, int)>::operator()<>() (this=0x604042fb1c98) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/functional:629
#15 0x0000560ff9267037 in std::__invoke_impl<void, std::_Bind_result<void, std::_Mem_fn<void (doris::WorkThreadPool<true>::*)(int)> (doris::WorkThreadPool<true>*, int)>>(std::__invoke_other, std::_Bind_result<void, std::_Mem_fn<void (doris::WorkThreadPool<true>::*)(int)> (doris::WorkThreadPool<true>*, int)>&&) (__f=...) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
#16 0x0000560ff9266fd7 in std::__invoke<std::_Bind_result<void, std::_Mem_fn<void (doris::WorkThreadPool<true>::*)(int)> (doris::WorkThreadPool<true>*, int)>>(std::_Bind_result<void, std::_Mem_fn<void (doris::WorkThreadPool<true>::*)(int)> (doris::WorkThreadPool<true>*, int)>&&) (__fn=...) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:96
#17 0x0000560ff9266f9f in std::thread::_Invoker<std::tuple<std::_Bind_result<void, std::_Mem_fn<void (doris::WorkThreadPool<true>::*)(int)> (doris::WorkThreadPool<true>*, int)> > >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x604042fb1c98) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_thread.h:253
#18 0x0000560ff9266f67 in std::thread::_Invoker<std::tuple<std::_Bind_result<void, std::_Mem_fn<void (doris::WorkThreadPool<true>::*)(int)> (doris::WorkThreadPool<true>*, int)> > >::operator()() (this=0x604042fb1c98) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_thread.h:260
#19 0x0000560ff9266eab in std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::_Bind_result<void, std::_Mem_fn<void (doris::WorkThreadPool<true>::*)(int)> (doris::WorkThreadPool<true>*, int)> > > >::_M_run() (this=0x604042fb1c90) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_thread.h:211
#20 0x000056102fdc5aa0 in std::execute_native_thread_routine (__p=0x604042fb1c90) at ../../../../../libstdc++-v3/src/c++11/thread.cc:82
#21 0x00007f29ad6e9609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#22 0x00007f29ad996133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-04-02 02:34 UTC, yiguolei commented on be/src/olap/tablet.cpp
> +WriteCooldownMetaExecutors::~WriteCooldownMetaExecutors() {
1. Refactor this code, add WriteCooldownMetaExecutors to exec_env.
2. Add a shutdown method to WriteCooldownMetaExecutors and call shutdown in exec_env's shutdown.

2024-04-02 02:34 UTC, yiguolei requested changes
Refactor WriteCooldownMetaExecutors

2024-04-02 03:11 UTC, yiguolei submitted a review, later dismissed
LGTM

2024-04-02 03:11 UTC, yiguolei commented
run buildall

2024-04-02 03:21 UTC, HappenLee approved these changes, later dismissed
LGTM

2024-04-02 04:58 UTC, zclllyybb commented
run buildall

2024-04-02 07:53 UTC, yiguolei approved these changes, later dismissed

2024-04-02 07:55 UTC, zhiqiang-hhhh requested changes

2024-04-02 08:10 UTC, zclllyybb commented
run buildall

2024-04-02 08:18 UTC, zclllyybb commented
run buildall

2024-04-02 08:22 UTC, zhiqiang-hhhh approved these changes
LGTM

2024-04-04 23:53 UTC, yiguolei submitted a review, later dismissed

2024-04-07 02:25 UTC, zclllyybb commented
run buildall

2024-04-08 02:58 UTC, BiteTheDDDDt approved these changes

2024-04-08 03:05 UTC, merged