[fix](index change) disable light index change for cloud mode
apache/doris pull request #33387
Opened 2024-04-08 12:55 UTC by xiaokang

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-04-08 12:55 UTC, xiaokang commented
run buildall

2024-04-08 15:58 UTC, xiaokang commented
run buildall

2024-04-10 02:30 UTC, platoneko commented on be/src/olap/schema_change.cpp
> +            auto column_new = new_tablet_schema->column(i);
```suggestion
            const auto& column_new = new_tablet_schema->column(i);
```

2024-04-10 02:30 UTC, platoneko commented on be/src/olap/schema_change.cpp
> +            auto column_old = base_tablet_schema->column(column_mapping->ref_column);
```suggestion
           const auto& column_old = base_tablet_schema->column(column_mapping->ref_column);
```

2024-04-10 02:31 UTC, platoneko requested changes
Please resolve the comment

2024-04-10 02:36 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/catalog/Index.java
> +        }
```suggestion
        return indexType == IndexDef.IndexType.INVERTED;
```

2024-04-10 08:08 UTC, luwei16 approved these changes

2024-04-10 09:23 UTC, xiaokang commented
run buildall

2024-04-11 01:59 UTC, xiaokang commented
run buildall

2024-04-11 04:33 UTC, xiaokang commented
run buildall

2024-04-11 06:31 UTC, xiaokang commented
> Please resolve the comment

@platoneko done

2024-04-11 07:11 UTC, dataroaring approved these changes
LGTM

2024-04-11 07:12 UTC, platoneko approved these changes

2024-04-11 07:13 UTC, merged