[Enhancement](mysql) support prepare statement completely
apache/doris pull request #33403
Opened 2024-04-09 03:04 UTC by nextdreamblue

## Proposed changes

Issue Number: close #33386

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-04-09 03:05 UTC, nextdreamblue commented
run buildall

2024-04-09 03:16 UTC, nextdreamblue commented
run buildall

2024-04-09 07:16 UTC, nextdreamblue commented
run buildall

2024-04-09 07:38 UTC, nextdreamblue commented
run buildall

2024-04-09 08:45 UTC, morrySnow commented
could we impl prepare on Nereids directly?

2024-04-09 09:20 UTC, nextdreamblue commented
run buildall

2024-04-10 02:17 UTC, dataroaring requested changes
Please add regression tests.

2024-04-10 11:57 UTC, nextdreamblue commented
run buildall

2024-04-10 12:00 UTC, nextdreamblue commented
run buildall

2024-04-15 11:13 UTC, nextdreamblue commented
run buildall

2024-04-17 02:56 UTC, nextdreamblue commented
run p0

2024-04-19 08:23 UTC, nextdreamblue commented
run buildall

2024-04-19 09:05 UTC, nextdreamblue commented
run buildall

2024-04-19 10:09 UTC, nextdreamblue commented
run compile

2024-04-24 03:36 UTC, nextdreamblue commented
run feut

2024-04-24 03:40 UTC, eldenmoon commented on regression-test/data/point_query_p0/test_point_query_cluster_key.out
> -1237	120939.111300000	a    ddd	laooq	2030-01-02	2020-01-01 12:36:38	22.822	7022-01-01	false	90696620686827832.374	[1.100000000, 2.200000000, 3.300000000, 4.400000000, 5.500000000]	[]
why modified these cases？

2024-04-24 03:47 UTC, eldenmoon commented on fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
> +        serializer.writeInt1(1);
these two fields is under some condition, you should not directly adding them

2024-04-24 03:49 UTC, eldenmoon commented on fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
> +            if (prepareStmt != null && isExecuteStmt && prepareStmt.isPointQuery()) {
sendFields should not use prepareStmt.isPointQuery() it has not relation to this function

2024-04-24 03:52 UTC, eldenmoon commented on fe/fe-core/src/main/java/org/apache/doris/planner/ResultSink.java
> +    private boolean isBinaryRow = false;
rename to `isBinaryMysqlRowFormat`

2024-04-24 03:52 UTC, eldenmoon commented on gensrc/thrift/DataSinks.thrift
> +    4: optional bool is_binary_row;
rename `is_binary_row` to `is_binary_mysql_row_format`

2024-04-24 03:55 UTC, eldenmoon commented on fe/fe-core/src/main/java/org/apache/doris/analysis/PrepareStmt.java
> +            if (isPointQuery) {
statment should be these types `NONE, FULL_PREPARED, STATEMENT`, STATEMENT type should suite. no need to `setPrepareStmt`, use type directly

2024-04-24 03:57 UTC, eldenmoon commented on regression-test/data/compaction/test_compaction_uniq_keys_row_store.out
>  -- !point_select --
please add none full prepared type sql cases, you could refer to this PR : https://github.com/apache/doris/pull/33807/files

2024-04-24 03:59 UTC, eldenmoon commented on fe/fe-core/src/main/java/org/apache/doris/qe/MysqlConnectProcessor.java
> +            if (packetBuf.hasRemaining() && (int) packetBuf.get() != 0) {
please add more comment to explain the changes to mysql protocol in FE

2024-04-24 03:59 UTC, eldenmoon commented on fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
> +        // warning_count
please add more comment to explain the changes to mysql protocol in FE

2024-04-24 04:03 UTC, eldenmoon commented
I think we should merge this PR or [33806](https://github.com/apache/doris/pull/33806/files)

2024-05-09 08:42 UTC, closed without merging