[fix](routine-load) fix get Kafka offset timeout may too long
apache/doris pull request #33502
Opened 2024-04-10 14:38 UTC by HHoflittlefish777

## Proposed changes

```
for (int32_t partition_id : partition_ids) {
        int64_t low = 0;
        int64_t high = 0;
        RdKafka::ErrorCode err =
                _k_consumer->query_watermark_offsets(_topic, partition_id, &low, &high, 5);
        if (err != RdKafka::ERR_NO_ERROR) {
            std::stringstream ss;
            ss << "failed to get latest offset for partition: " << partition_id
               << ", err: " << RdKafka::err2str(err);
            LOG(WARNING) << ss.str();
            return Status::InternalError(ss.str());
        }
```

fe getInfo timeout is 5s, but in be, the timeout is 5 * partition num.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-04-10 14:38 UTC, HHoflittlefish777 commented
run buildall

2024-04-10 14:38 UTC, dataroaring commented
run buildall

2024-04-10 14:39 UTC, HHoflittlefish777 commented
run buildall

2024-04-10 14:42 UTC, HHoflittlefish777 commented
run buildall

2024-04-10 14:44 UTC, HHoflittlefish777 commented
run buildall

2024-04-11 02:43 UTC, HHoflittlefish777 commented
run p0

2024-04-11 02:50 UTC, HHoflittlefish777 commented
run buildall

2024-04-11 03:14 UTC, HHoflittlefish777 commented
run buildall

2024-04-11 03:22 UTC, HHoflittlefish777 commented
run buildall

2024-04-11 05:58 UTC, HHoflittlefish777 commented
run buildall

2024-04-13 12:21 UTC, dataroaring submitted a review, later dismissed
LGTM

2024-04-13 13:16 UTC, HHoflittlefish777 commented
run buildall

2024-04-15 01:44 UTC, dataroaring approved these changes, later dismissed
LGTM

2024-04-15 03:11 UTC, liaoxin01 requested changes

2024-04-15 03:11 UTC, liaoxin01 commented on be/src/runtime/routine_load/data_consumer.cpp
> +        auto timeout_ms = timeout - watch.elapsed_time() / 1000 / 1000;
watch.elapsed_time() return uint64_t, implicit type conversion may lead to unexpected issues.

2024-04-15 08:54 UTC, HHoflittlefish777 commented
run buildall

2024-04-15 08:55 UTC, HHoflittlefish777 commented
run buildall

2024-04-15 08:58 UTC, liaoxin01 approved these changes
LGTM

2024-04-15 09:04 UTC, dataroaring approved these changes
LGTM

2024-04-15 11:35 UTC, merged