[Fix](timezone) fix miss of expected rounding of Date type with timezone
apache/doris pull request #33553
Opened 2024-04-11 11:43 UTC by zclllyybb

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-04-11 11:43 UTC, zclllyybb commented
run buildall

2024-04-12 03:15 UTC, HappenLee requested changes
Add commit desc for pr

2024-04-12 06:36 UTC, HappenLee commented on be/src/vec/runtime/vdatetime_value.cpp
> +    // here maybe date changed because of rouding
Add detail comment for the code.  what case, why we need the code.

2024-04-12 06:53 UTC, zclllyybb commented
run buildall

2024-04-12 06:58 UTC, HappenLee approved these changes
LGTM

2024-04-12 15:20 UTC, yiguolei approved these changes

2024-04-12 15:22 UTC, merged