[feature](Cloud) Alter be to fetch vault info after creating storage vault
apache/doris pull request #33558
Opened 2024-04-11 14:03 UTC by ByteYue

## Proposed changes

Issue Number: close #xxx

Make BE eagerly fetches the vault info right after FE receives the create vault resp from MS.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-04-11 14:14 UTC, ByteYue commented
run feut

2024-04-11 14:55 UTC, platoneko requested changes

2024-04-11 14:55 UTC, platoneko commented on be/src/service/internal_service.cpp
> +    _engine.to_cloud().sync_storage_vault();
Implement this method in `CloudBackendService`, `to_cloud()` here will check failed

2024-04-11 15:43 UTC, ByteYue commented
run buildall

2024-04-11 16:52 UTC, platoneko approved these changes

2024-04-12 02:02 UTC, dataroaring approved these changes
LGTM

2024-04-12 02:03 UTC, merged