[fix](merge-cloud) fix inconsistency between cloud mode and local mode for 2PC
apache/doris pull request #33917
Opened 2024-04-19 15:58 UTC by liaoxin01

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-04-19 15:58 UTC, liaoxin01 commented
run buildall

2024-04-19 16:21 UTC, gavinchou requested changes

2024-04-19 16:21 UTC, gavinchou commented on cloud/src/meta-service/meta_service_txn.cpp
> +        return;
missing msg update?

2024-04-19 16:21 UTC, gavinchou commented on cloud/src/meta-service/meta_service_txn.cpp
> +    return;
missing msg update?

2024-04-19 16:31 UTC, gavinchou requested changes

2024-04-19 16:31 UTC, gavinchou commented on gensrc/proto/cloud.proto
> +    optional int64 txn_id = 2;
repeated?

2024-04-19 16:31 UTC, gavinchou commented on cloud/src/meta-service/meta_service_txn.cpp
> +void MetaServiceImpl::get_txn_id(::google::protobuf::RpcController* controller,
Add sufficient comment to describe what does it do.

2024-04-19 16:31 UTC, gavinchou commented on cloud/src/meta-service/meta_service_txn.cpp
pls add UT to cover all the newly added code: line/branch coverage 90+%

2024-04-20 03:35 UTC, liaoxin01 commented
run buildall

2024-04-20 03:36 UTC, liaoxin01 commented on gensrc/proto/cloud.proto
> +    optional int64 txn_id = 2;
only return one txn_id.

2024-04-20 15:10 UTC, gavinchou approved these changes

2024-04-20 15:11 UTC, dataroaring approved these changes
LGTM

2024-04-21 02:52 UTC, merged