[fix](profile)  Fix reporting the profile while building the pipeline profile.
apache/doris pull request #34215
Opened 2024-04-28 02:42 UTC by Mryange

## Proposed changes

This error occurs because the profile is being reported while still in the build process.
```
start BE in local mode
*** Query id: 0-0 ***
*** is nereids: 0 ***
*** tablet id: 0 ***
*** Aborted at 1714226889 (unix time) try "date -d @1714226889" if you are using GNU date ***
*** Current BE git commitID: 53c62a4f03 ***
*** SIGSEGV address not mapped to object (@0x270) received by PID 3343430 (TID 3344068 OR 0x7ff93a2bc700) from PID 624; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /mnt/disk1/zhaochangle/doris/be/src/common/signal_handler.h:421
 1# PosixSignals::chained_handler(int, siginfo*, void*) [clone .part.0] in /mnt/disk1/zhaochangle/jdk-17.0.2/lib/server/libjvm.so
 2# JVM_handle_linux_signal in /mnt/disk1/zhaochangle/jdk-17.0.2/lib/server/libjvm.so
 3# 0x00007FFA7FA77B50 in /lib64/libc.so.6
 4# doris::RuntimeProfile::sort_children_by_total_time() at /mnt/disk1/zhaochangle/doris/be/src/util/runtime_profile.cpp:728
 5# doris::FragmentMgr::coordinator_callback(doris::ReportStatusRequest const&) at /mnt/disk1/zhaochangle/doris/be/src/runtime/fragment_mgr.cpp:269
 6# std::_Function_handler<void (), doris::FragmentMgr::trigger_pipeline_context_report(doris::ReportStatusRequest, std::shared_ptr<doris::pipeline::PipelineFragmentContext>&&)::$_0>::_M_invoke(std::_Any_data const&) at /mnt/disk1/zhaochangle/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_function.h:290
 7# doris::ThreadPool::dispatch_thread() in /mnt/disk1/zhaochangle/doris/output_perf/be/lib/doris_be
 8# doris::Thread::supervise_thread(void*) at /mnt/disk1/zhaochangle/doris/be/src/util/thread.cpp:499
 9# start_thread in /lib64/libpthread.so.0
10# __clone in /lib64/libc.so.6
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-04-28 02:44 UTC, Mryange commented
run buildall

2024-04-28 04:06 UTC, zhiqiang-hhhh commented on be/src/runtime/runtime_state.cpp
> +    std::lock_guard lc(_pipeline_profile_lock);
use read-write lock

2024-04-28 04:08 UTC, zhiqiang-hhhh requested changes
1. use read-write lock
2. do we any potential dead-lock?

2024-04-28 04:19 UTC, Mryange commented
> 1. use read-write lock
> 2. do we have any potential dead-lock?

1. done
2. This lock is only used in the functions pipeline_id_to_profile and build_pipeline_profile, and they do not call each other.

2024-04-28 04:19 UTC, Mryange commented
run buildall

2024-04-28 06:08 UTC, zhiqiang-hhhh commented on be/src/runtime/runtime_state.cpp
> +std::vector<std::unique_ptr<RuntimeProfile>>& RuntimeState::pipeline_id_to_profile() {
return value is a reference to the vector, after fucntion call, the vector will not be protected by the lock.

2024-04-28 06:10 UTC, zhiqiang-hhhh requested changes
The data race can not be fixed by this pr. It will still exist.

2024-04-28 06:50 UTC, Mryange commented
run buildall

2024-04-28 07:48 UTC, Mryange commented
run buildall

2024-04-29 02:33 UTC, zhiqiang-hhhh approved these changes
LGTM

2024-04-29 02:37 UTC, Gabriel39 approved these changes

2024-04-29 07:08 UTC, merged