[feature](Cloud) Try to do memory limit control for hdfs write
apache/doris pull request #34354
Opened 2024-04-30 08:10 UTC by ByteYue

## Proposed changes

Issue Number: close #xxx

In practice, we've found that if the import frequency to HDFS is too fast, it can cause an OutOfMemoryError (OOM) in the JVM started by the JNI. For this, we should have a method to monitor how much JVM memory is currently being used.

The HdfsWriteRateLimit class increments a recorded value during hdfsWrite when writing to HDFS. When hdfsCloseFile is called, all related memory in the JVM will be invalidated, so the recorded value can be decreased at that time. However, if the current usage exceeds the maximum set by the user, the current write will sleep. If the number of sleeps exceeds the number specified by the user, then the current write is considered to have failed.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-05-02 03:55 UTC, gavinchou commented on be/src/util/jni-util.cpp
> +    max_jvm_heap_memory_size_ = env->GetLongField(mu, max);
Is there any chance that the left-hand-side value is nullpointer?
Do we have to consider that situation?

2024-05-02 03:59 UTC, gavinchou commented on be/src/io/fs/hdfs_file_writer.cpp
> +    Status do_rate_limit(size_t memory_size) {
Make the name symmetric to `release_jni_memory()`,
and, may be the word `jni` is unnecessary.
say, `acquire_memory(size_t)` and `release_memory(size_t)`.

2024-05-02 04:03 UTC, gavinchou commented on be/src/common/config.cpp
> +DEFINE_mDouble(max_hdfs_jni_heap_usage_ratio, "0.7");
Naming max_hdfs_jni_heap_usage_ratio  -> max_hdfs_wirter_jni_heap_usage_ratio

2024-05-02 04:10 UTC, gavinchou requested changes

2024-05-02 04:10 UTC, gavinchou commented on be/src/io/fs/hdfs_file_writer.cpp
> +        return Status::InternalError("Run out of Jni jvm heap space");
also print the memory limit

2024-05-02 07:39 UTC, ByteYue commented
run buildall

2024-05-02 09:30 UTC, ByteYue commented
run buildall

2024-05-02 13:22 UTC, ByteYue commented
run buildall

2024-05-08 12:01 UTC, gavinchou approved these changes

2024-05-08 12:57 UTC, ByteYue commented
run buildall

2024-05-08 16:13 UTC, ByteYue commented
run buildall

2024-05-09 03:32 UTC, ByteYue commented
run buildall

2024-05-09 08:28 UTC, ByteYue commented
run buildall

2024-05-09 17:20 UTC, gavinchou commented on be/src/io/fs/hdfs_file_writer.cpp
> +        }
LOG if no available connections

2024-05-09 17:22 UTC, gavinchou commented on be/src/io/fs/hdfs_file_writer.cpp
> +#elif BE_TEST
Use syncpoint instead

2024-05-09 17:24 UTC, gavinchou commented on be/src/io/fs/hdfs_file_writer.cpp
> +#elif BE_TEST
return?

2024-05-09 17:24 UTC, gavinchou commented
LGTM

2024-05-10 07:15 UTC, ByteYue commented
run buildall

2024-05-10 07:43 UTC, ByteYue commented
run buildall

2024-05-10 16:46 UTC, gavinchou commented on be/src/util/jni-util.cpp
> +    LOG(INFO) << "the max_jvm_heap_memory_size_ is " << max_jvm_heap_memory_size_;
log fatal and exit if max_jvm_heap_memory_size_ is zero

2024-05-10 16:57 UTC, gavinchou approved these changes

2024-05-11 03:27 UTC, platoneko requested changes

2024-05-11 03:27 UTC, platoneko commented on be/src/io/fs/hdfs_file_writer.cpp
> +            return Status::InternalError(
`lck.unlock()` before return `InternalError`

2024-05-11 03:27 UTC, platoneko commented on be/src/io/fs/hdfs_file_writer.cpp
> +            return Status::InternalError(
Maybe stacktrace should be disabled here, use `InternalError<false>`

2024-05-11 03:27 UTC, platoneko commented on be/src/io/fs/hdfs_file_writer.cpp
> +            cv.notify_one();
notify_all

2024-05-11 04:55 UTC, ByteYue commented
run buildall

2024-05-11 05:11 UTC, ByteYue commented
run buildall

2024-05-11 05:20 UTC, ByteYue commented
run buildall

2024-05-11 09:40 UTC, dataroaring approved these changes
LGTM

2024-05-11 09:59 UTC, platoneko approved these changes

2024-05-11 10:09 UTC, merged