[improve](txn insert) Txn load support cloud mode
apache/doris pull request #34721
Opened 2024-05-11 09:51 UTC by mymeiyi

## Proposed changes

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-05-11 09:56 UTC, mymeiyi commented
run buildall

2024-05-11 13:49 UTC, gavinchou commented on cloud/src/meta-service/meta_service_txn.cpp
> +void MetaServiceImpl::commit_txn_with_sub_txn(::google::protobuf::RpcController* controller,
add comment to describe what does this rpc do?

2024-05-13 08:15 UTC, mymeiyi commented
run buildall

2024-05-15 04:55 UTC, mymeiyi commented
run buildall

2024-05-15 09:14 UTC, mymeiyi commented
run buildall

2024-05-20 02:35 UTC, mymeiyi commented
run buildall

2024-05-22 03:01 UTC, mymeiyi commented
run buildall

2024-05-22 04:19 UTC, mymeiyi commented
run buildall

2024-05-22 08:36 UTC, dataroaring approved these changes, later dismissed
LGTM

2024-05-22 11:06 UTC, mymeiyi commented
run cloud_p0 cloud_ut

2024-05-22 11:31 UTC, mymeiyi commented
run cloud_p0

2024-05-25 07:47 UTC, dataroaring submitted a review, later dismissed
LGTM

2024-05-29 10:19 UTC, gavinchou requested changes

2024-05-29 10:19 UTC, gavinchou commented on cloud/src/meta-service/meta_service_txn.cpp
> +    for (const auto& sub_txn_info : sub_txn_infos) {
Add enough UT to test the rowset meta KV versions continuity

2024-05-29 10:19 UTC, gavinchou commented on cloud/src/meta-service/meta_service_txn.cpp
> +        if (request->has_is_2pc() && request->is_2pc()) {
do not support 2PC

2024-05-29 10:19 UTC, gavinchou commented on cloud/src/meta-service/meta_service_txn.cpp
> +    LOG(INFO) << "commit_txn put_size=" << txn->put_bytes() << " del_size=" << txn->delete_bytes()
one LOG

2024-05-30 01:54 UTC, dataroaring commented
run buildall

2024-05-30 03:18 UTC, mymeiyi commented on gensrc/proto/cloud.proto
> +    repeated int64 base_tablet_ids= 3;
The Coordinator::updateCommitInfos ensure it

2024-05-30 09:23 UTC, mymeiyi commented
run buildall

2024-05-30 09:30 UTC, mymeiyi commented
run buildall

2024-05-30 11:29 UTC, mymeiyi commented
run buildall

2024-05-30 15:07 UTC, mymeiyi commented
run buildall

2024-05-31 02:50 UTC, mymeiyi commented
run buildall

2024-05-31 06:39 UTC, mymeiyi commented
run buildall

2024-05-31 08:50 UTC, mymeiyi commented
run cloud_ut cloud_p1

2024-05-31 09:17 UTC, mymeiyi commented
run cloud_p1

2024-05-31 10:40 UTC, mymeiyi commented
run cloud_p1

2024-05-31 10:40 UTC, mymeiyi commented
run cloud_p0

2024-06-03 02:12 UTC, mymeiyi commented
run buildall

2024-06-03 04:20 UTC, mymeiyi commented
run p0

2024-06-04 06:30 UTC, gavinchou approved these changes

2024-06-04 11:54 UTC, dataroaring approved these changes, later dismissed
LGTM

2024-06-04 12:27 UTC, mymeiyi commented
run fe_ut

2024-06-04 12:28 UTC, mymeiyi commented
run performance

2024-06-04 12:48 UTC, mymeiyi commented
run buildall

2024-06-04 14:46 UTC, mymeiyi commented
run cloud_p0

2024-06-04 14:48 UTC, dataroaring submitted a review, later dismissed
LGTM

2024-06-05 03:10 UTC, mymeiyi commented
run buildall

2024-06-05 06:07 UTC, mymeiyi commented
run cloud_ut

2024-06-05 06:09 UTC, mymeiyi commented
run p0

2024-06-05 06:15 UTC, mymeiyi commented
run cloudut

2024-06-05 07:48 UTC, dataroaring approved these changes
LGTM

2024-06-05 07:49 UTC, merged