[Memory Engine] add core column related classes
apache/doris pull request #3508
Opened 2020-05-07 10:41 UTC by decster

This CL add core column related classes into the code base, including:

- Buffer
- ColumnBlock
- ColumnDelta
- Column
- DeltaIndex
- ColumnSchema and Schema

Column read/write will added in the following PR

Part of #3465

2020-05-09 01:34 UTC, decster commented on be/src/olap/memory/buffer.h
> +class Buffer {
fixed

2020-05-09 01:34 UTC, decster commented on be/src/olap/memory/CMakeLists.txt
> +	buffer.cpp
fixed

2020-05-09 15:17 UTC, decster commented on be/src/olap/memory/column.cpp
> +    DLOG(INFO) << "create %s" << debug_string();
This log is only used in debug mode, like DCHECK, it help show more info when debugging, and it has no effect in release build. I can remove them if it's this project's convention.

2020-05-10 04:30 UTC, decster commented on be/src/olap/memory/delta_index.h
> +    // Return true this index has any rowid belonging to this block
fixed

2020-05-10 07:17 UTC, kangkaisen commented
@decster Hi, I have one question:  Do we have a data structure to describe `the block of rows for multi columns`?  Like  Doris `RowBlockV2`, Arrow `RecordBatch` and TiDB `Chunk`.

2020-05-11 02:32 UTC, decster commented on be/src/olap/memory/column.cpp
> +    _base.reserve(64);
> @decster Hi, I have one question: Do we have a data structure to describe `the block of rows for multi columns`? Like Doris `RowBlockV2`, Arrow `RecordBatch` and TiDB `Chunk`.

No, but the same block id and rowid represent same group of rows, so it's easy to add them if it's really necessary. But currently, I do not see any needs.

2020-05-11 02:33 UTC, decster commented on be/src/olap/memory/column_block.h
> +    Status alloc(size_t size, size_t esize);
Sure

2020-05-11 03:04 UTC, decster commented on be/src/olap/memory/buffer.h
> +    uint8_t* data() { return _data; }
There are already many places use this naming convention, and class in std also use this convention.

2020-05-11 03:05 UTC, decster commented on be/src/olap/memory/column.cpp
> +    _base.reserve(64);
fixed

2020-05-11 03:05 UTC, decster commented on be/src/olap/memory/column_block.h
> +    Status alloc(size_t size, size_t esize);
fixed

2020-05-11 03:09 UTC, decster commented
> @decster Hi, I have one question: Do we have a data structure to describe the block of rows for multi columns? Like Doris RowBlockV2, Arrow RecordBatch and TiDB Chunk.

Not currently, but same blockid represents same group of rows, so we can always add them latter if needed.

2020-05-11 03:11 UTC, decster commented on be/src/olap/memory/column.h
> +    ssize_t _base_idx;
This is for usage in Column.cpp, but I guess change code in for loop would be better. 

`        for (ssize_t i = static_cast<ssize_t>(_base_idx) - 1; i >= 0; i--) {
`

fixed

2020-05-11 03:15 UTC, decster commented on be/src/olap/memory/column.cpp
> +    _base.reserve(64);
It's the step size for base vector and version vector when over capacity and need to grow

2020-05-11 15:07 UTC, kangkaisen commented on be/src/olap/memory/buffer.h
> +    uint8_t* data() { return _data; }
OK

2020-05-11 15:09 UTC, kangkaisen submitted a review, later dismissed
+1, LGTM

2020-05-12 01:30 UTC, chaoyli requested changes

2020-05-12 04:08 UTC, decster commented on be/src/olap/memory/common.h
> +inline size_t NBlock(T v, ST bs) {
fixed

2020-05-12 04:08 UTC, decster commented on be/src/olap/memory/common.h
> +inline T Padding(T v, ST pad) {
fixed

2020-05-12 04:08 UTC, decster commented on be/src/olap/memory/schema.h
> +// Schema have some differences comparing to original TablteSchema:
fixed

2020-05-13 08:25 UTC, chaoyli approved these changes

2020-05-13 08:29 UTC, chaoyli commented
LGTM

2020-05-13 08:30 UTC, merged