[feature-wip](Cloud) Extract obj storage client interface to suite different kinds of object storage
apache/doris pull request #35307
Opened 2024-05-23 12:36 UTC by ByteYue

## Proposed changes

Issue Number: close #xxx

For authentication and better tracing to different cloud vendors, we're intended to introduce kinds of sdk to suite corresponding obj storage. This pr is part of the whole procedure, which tries to extract one basic interface and implement the S3 client.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-05-24 09:31 UTC, ByteYue commented
run buildall

2024-05-24 14:08 UTC, ByteYue commented
run buildall

2024-05-24 15:44 UTC, ByteYue commented
run buildall

2024-05-26 10:09 UTC, ByteYue commented
run buildall

2024-05-26 14:56 UTC, ByteYue commented
run buildall

2024-05-28 02:57 UTC, platoneko commented on be/src/io/fs/err_utils.h
> +Status s3fs_error(Status msg, std::string_view path);
参数名和实际调用时候传入的对不上

2024-05-28 06:15 UTC, gavinchou requested changes

2024-05-28 06:15 UTC, gavinchou commented on be/src/io/fs/s3_file_reader.cpp
> +            {
Strange indention.

2024-05-28 06:15 UTC, gavinchou commented on be/src/io/fs/obj_storage_client.h
> +    virtual ObjectStorageResponse CreateMultiPartUpload(const ObjectStoragePathOptions& opts) = 0;
Naming style should be `lower_case_under_score` not `UpperCaseCamel`

2024-05-28 13:08 UTC, ByteYue commented
run buildall

2024-05-29 08:04 UTC, ByteYue commented
run buildall

2024-05-29 09:18 UTC, platoneko commented on be/src/io/fs/obj_storage_client.h
> +    std::optional<std::string> upload_id;
考虑抽出一个 ObjectStorageUploadResponse，ObjectStorageResponse 只用存 code 和 msg

2024-05-29 09:27 UTC, platoneko commented on be/src/io/fs/s3_file_system.cpp
> +        return ResultError(resp.status.append(
```suggestion
        return ResultError(std::move(resp.status.append(
```

2024-05-29 09:28 UTC, platoneko commented on be/src/io/fs/s3_file_system.cpp
> +    return resp.status.append(fmt::format("failed to delete file {}", full_s3_path(key)));
```suggestion
    return std::move(resp.status.append(fmt::format("failed to delete file {}", full_s3_path(key))));
```

2024-05-29 09:32 UTC, platoneko commented on be/src/io/fs/s3_file_system.cpp
> +        return resp.status.append(fmt::format("failed to check exists {}", full_s3_path(key)));
ditto

2024-05-29 09:33 UTC, platoneko commented on be/src/io/fs/s3_file_system.cpp
> +        std::shared_ptr<std::packaged_task<Status(Path local_file, Path remote_file,
auto

2024-05-29 09:37 UTC, platoneko commented on be/src/io/fs/s3_file_system.cpp
> +    auto upload_task = [this](Path local_file, Path remote_file, FileWriterPtr* obj_writer) {
```suggestion
    auto upload_task = [this, &](size_t idx) {
```

2024-05-29 09:42 UTC, platoneko commented on be/src/io/fs/s3_file_system.cpp
> +        return Status::IOError("failed to download {}: failed to write file: {}",
localfs_error

2024-05-29 12:40 UTC, platoneko approved these changes
有些comment，下个PR改也行

2024-05-30 05:25 UTC, gavinchou approved these changes

2024-05-30 05:43 UTC, merged