[feature-wip](Cloud) Introduce obj storage client interface to recycler
apache/doris pull request #35447
Opened 2024-05-27 08:28 UTC by ByteYue

## Proposed changes

Issue Number: close #xxx

This is one subsequent pr of #35307 which does the same thing to recycler to extract basic interface to suite different kinds of Object Storage.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-05-27 09:44 UTC, ByteYue commented
run buildall

2024-05-27 15:51 UTC, gavinchou requested changes

2024-05-27 15:51 UTC, gavinchou commented on cloud/src/recycler/obj_store_accessor.h
> +class ObjStorageClient {
Add enough/detailed comments to describe the behavior of each function as much as possible

2024-05-27 15:51 UTC, gavinchou commented on cloud/src/recycler/obj_store_accessor.h
> +    int ret {0};
Is this for "return code"?
If yes, try to make it `enum class` or pre-define some constants for codes

2024-05-27 15:51 UTC, gavinchou commented on cloud/src/recycler/s3_obj_client.cpp
> +#define HELP_MACRO(ret, req, point_name)
typo, HELPER_MACRO

2024-05-28 06:38 UTC, ByteYue commented
run buildall

2024-05-29 08:29 UTC, ByteYue commented
run buildall

2024-05-30 13:08 UTC, platoneko requested changes

2024-05-30 13:08 UTC, platoneko commented on cloud/src/recycler/s3_obj_client.cpp
> +            files->push_back({obj.GetKey().substr(opts.prefix.size() + 1), obj.GetSize(),
在 `ObjStoreAccessor` 中 `ObjectMeta` 的 `path` 需要存除去 Accessor prefix 的那段，而不是除去传入的 prefix 的段。e.g. accessor.prefix = "doris_s3_vault", opts.preifx = "doris_s3_vault/data/114115/"

2024-05-30 13:08 UTC, platoneko commented on be/src/io/fs/s3_obj_storage_client.cpp
在 BE 中 FileInfo 中的 file_name 不应该包含 list 使用的 prefix 那段 e.g.:
prefix = "doris_s3_vault/data/114115/", key = "doris_s3_vault/data/114115/abc_0.dat", file_name = "abc_0.dat"
prefix = "doris_s3_vault/data/100/114115/", key = "doris_s3_vault/data/100/114115/abc/0.dat", file_name = "abc/0.dat"

2024-05-30 13:30 UTC, gavinchou approved these changes

2024-05-30 13:32 UTC, gavinchou approved these changes

2024-05-31 10:01 UTC, ByteYue commented
run buildall

2024-05-31 16:27 UTC, ByteYue commented
run buildall

2024-06-03 12:09 UTC, platoneko approved these changes

2024-06-03 12:12 UTC, merged