[feature](Cloud) Add azure's support to BE
apache/doris pull request #35670
Opened 2024-05-30 11:47 UTC by ByteYue

## Proposed changes

As one subsequent pr of #35307, this pr will link azure into BE, and implements the corresponding interface of ObjStorageClient for Azure.

2024-05-30 13:29 UTC, gavinchou approved these changes

2024-05-31 16:53 UTC, gavinchou requested changes

2024-05-31 16:53 UTC, gavinchou commented on be/test/io/fs/azure_test.cpp
> +    const std::string blobContent = "Fuck Azure!";
Remove the F word

2024-05-31 16:53 UTC, gavinchou commented on be/src/io/fs/azure_obj_storage_client.cpp
How do we test each function implementation?

2024-05-31 16:59 UTC, ByteYue commented on be/src/io/fs/azure_obj_storage_client.cpp
I'll add enough ut to test them right after i've done all the feature test like batch delete test in azure.

2024-05-31 17:00 UTC, ByteYue commented on be/src/util/s3_util.cpp
> +std::shared_ptr<io::ObjStorageClient> S3ClientFactory::create(const S3ClientConf& s3_conf) {
I think it could be one future work, since change the class name might be error-prone at developing time.

2024-06-04 02:55 UTC, ByteYue commented
run buildall

2024-06-04 11:36 UTC, ByteYue commented
run beut

2024-06-05 02:22 UTC, ByteYue commented
run beut

2024-06-05 05:28 UTC, ByteYue commented
run buildall

2024-06-05 07:38 UTC, ByteYue commented
run buildall

2024-06-05 08:02 UTC, ByteYue commented
run buildall

2024-06-05 11:43 UTC, ByteYue commented
run buildall

2024-06-06 01:47 UTC, dataroaring approved these changes, later dismissed
LGTM

2024-06-06 06:12 UTC, gavinchou approved these changes

2024-06-06 06:22 UTC, platoneko commented on gensrc/thrift/AgentService.thrift
> +    AWS = 0,
```suggestion
    UNKNOWN = 0,
```

2024-06-06 06:49 UTC, platoneko commented on be/src/util/s3_util.h
>      }
```c++
static S3Conf get_s3_conf(const ObjectStoreInfoPB&);
static S3Conf get_s3_conf(const TS3StorageParam&);
```
在函数实现里面处理 unknown provider，注意前向兼容

2024-06-06 08:02 UTC, ByteYue commented
run buildall

2024-06-06 08:44 UTC, ByteYue commented
run buildall

2024-06-06 11:26 UTC, ByteYue commented
run buildall

2024-06-07 02:36 UTC, ByteYue commented
run buildall

2024-06-07 02:38 UTC, ByteYue commented
run buildall

2024-06-11 01:52 UTC, gavinchou approved these changes

2024-06-11 02:17 UTC, dataroaring approved these changes, later dismissed
LGTM

2024-06-11 03:28 UTC, ByteYue commented
run buildall

2024-06-11 06:34 UTC, dataroaring approved these changes
LGTM

2024-06-11 07:03 UTC, merged