[feature-wip](Cloud) Support Azure Cloud Blob in FE
apache/doris pull request #35990
Opened 2024-06-06 09:51 UTC by ByteYue

## Proposed changes

As one subsequent pr of #35307, this pr tries to support Azure Cloud in FE. After this pr, we should be able to use Azure Blob for Cold Heat Separation and Storage Compute Separation along with backup restore to Azure Cloud.

For the data lakes support, you can add corresponding sdks to FE and implements the corresponding features.

2024-06-08 15:51 UTC, dataroaring commented
run buildall

2024-06-13 01:53 UTC, dataroaring commented
run buildall

2024-06-15 15:25 UTC, dataroaring commented
run buildall

2024-06-17 06:05 UTC, gavinchou requested changes

2024-06-19 07:00 UTC, ByteYue commented
run buildall

2024-06-19 13:58 UTC, ByteYue commented
run buildall

2024-06-19 15:01 UTC, gavinchou commented on regression-test/suites/tpcds_sf100_dup_without_key_p2/load.groovy
> +        |"AWS_REGION" = "${getS3Region()}"),
bug , should not end if `),`

2024-06-19 15:03 UTC, gavinchou commented
Add a case to  cover s3 load without `provider` option
```
oad ....
WITH S3 (
        "AWS_ACCESS_KEY" = "aaa",
        "AWS_SECRET_KEY" = "bbb",
        "AWS_ENDPOINT" = "ccc",
        "AWS_REGION" = "ddd")
        PROPERTIES(
        "exec_mem_limit" = "8589934592",
        "load_parallelism" = "3")
```

2024-06-20 03:25 UTC, ByteYue commented
run buildall

2024-06-21 10:23 UTC, gavinchou approved these changes, later dismissed

2024-06-21 14:38 UTC, morningman commented on fe/fe-core/src/main/java/org/apache/doris/fs/remote/AzureFileSystem.java
> +    private static String removeUselessSchema(String remotePath) {
Add comment with an example to describe the transform

2024-06-21 14:38 UTC, morningman commented on fe/fe-core/src/main/java/org/apache/doris/fs/remote/AzureFileSystem.java
> +            LOG.info("file not found: " + e.getMessage());
better print file path in log

2024-06-21 14:38 UTC, morningman commented on fe/fe-core/src/main/java/org/apache/doris/fs/remote/AzureFileSystem.java
> +            LOG.error("errors while get file status ", e);
better print file path in log.
And use warn

2024-06-21 14:38 UTC, morningman commented on fe/fe-core/src/main/java/org/apache/doris/fs/obj/AzureObjStorage.java
> +            LOG.info("head file " + remotePath + " success: " + properties.toString());
```suggestion
            LOG.info("head file {} success: {}", remotePath, properties.toString());
```

2024-06-21 14:38 UTC, morningman commented on fe/fe-core/src/main/java/org/apache/doris/fs/obj/AzureObjStorage.java
> +                LOG.warn("headObject failed:", e);
print file path

2024-06-21 14:38 UTC, morningman commented on fe/fe-core/src/main/java/org/apache/doris/catalog/AzureResource.java
> +    private static void pingS3(CloudCredentialWithEndpoint credential, String bucketName, String rootPath,
```suggestion
    private static void pingAzure(CloudCredentialWithEndpoint credential, String bucketName, String rootPath,
```

2024-06-21 16:57 UTC, ByteYue commented
run buildall

2024-06-22 12:56 UTC, ByteYue commented
run buildall

2024-06-22 13:08 UTC, ByteYue commented
run buildall

2024-06-23 07:00 UTC, ByteYue commented
run buildall

2024-06-23 15:55 UTC, gavinchou approved these changes

2024-06-24 03:22 UTC, morningman approved these changes

2024-06-24 03:24 UTC, merged