[fix](restore) avoid NPE for restore job
apache/doris pull request #36395
Opened 2024-06-17 09:02 UTC by DarvenDuan

## Proposed changes

Issue Number: close #xxx
The indexes of OlapTable may not be assigned in method `readFields`:
```
@Override
public void readFields(DataInput in) throws IOException {
    ...
    // read indexes
    if (in.readBoolean()) {
        this.indexes = TableIndexes.read(in);
    }
    ...
}
```
So indexes may be null.

2024-06-17 09:08 UTC, dataroaring requested changes
Please describe when the case happens.

2024-06-18 03:10 UTC, DarvenDuan commented
> Please describe when the case happens.

I added some words in comment above.

2024-06-26 12:19 UTC, dataroaring approved these changes
LGTM

2024-06-26 12:19 UTC, dataroaring commented
run buildall

2024-06-26 13:20 UTC, GoGoWen approved these changes
LGTM

2024-06-27 02:28 UTC, DarvenDuan commented
run p0

2024-06-27 02:28 UTC, DarvenDuan commented
run cloud_p1

2024-06-27 05:14 UTC, DarvenDuan commented
run buildall

2024-06-27 07:06 UTC, DarvenDuan commented
run p0

2024-06-27 09:14 UTC, DarvenDuan commented
run p0

2024-06-27 12:14 UTC, GoGoWen approved these changes
LGTM

2024-06-27 12:15 UTC, merged