[function](signature) add datev2 signature for from_days function
apache/doris pull request #36505
Opened 2024-06-19 02:58 UTC by zhangstar333

## Proposed changes

add datev2 signature for from_days function

2024-06-19 02:58 UTC, zhangstar333 commented
run buildall

2024-06-19 03:03 UTC, morrySnow requested changes

2024-06-19 03:03 UTC, morrySnow commented on fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/FromDays.java
>              FunctionSignature.ret(DateType.INSTANCE).args(IntegerType.INSTANCE)
should not have two signature with same input. remove sig with date return type. and update from_days constant folding in `org.apache.doris.nereids.trees.expressions.functions.executable.DateTimeExtractAndTransform`

2024-06-19 03:33 UTC, zhangstar333 commented
run buildall

2024-06-19 03:43 UTC, morrySnow approved these changes

2024-06-20 03:28 UTC, HappenLee approved these changes
LGTM

2024-06-20 07:47 UTC, merged