[improvement](meta) Switch meta serialization to gson 4
apache/doris pull request #36568
Opened 2024-06-19 14:32 UTC by iszhangpch

## Proposed changes

Issue Number:

Switch meta serialization to gson
Contains the following classes：

RoutineLoadJob
UserPropertyInfo
AnalyzeDeletionLog
CreateTableInfo
HbPackage
PartitionPersistInfo
ReplicaPersistInfo
RoutineLoadOperation

2024-06-19 14:32 UTC, iszhangpch commented
run buildall

2024-06-21 08:08 UTC, iszhangpch commented
run buildall

2024-06-25 02:06 UTC, iszhangpch commented
run buildall

2024-06-25 04:02 UTC, dataroaring commented on fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadProgress.java
> +                progress = new KafkaProgress();
We should handle like this in gsonPostProcess.

2024-06-25 04:02 UTC, dataroaring commented on fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadProgress.java
>      }
Just remove write method.

2024-06-25 04:05 UTC, dataroaring commented on fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
> +                job = new KafkaRoutineLoadJob();
handle like this in gsonPostProcess.

2024-06-25 04:14 UTC, dataroaring commented on fe/fe-core/src/main/java/org/apache/doris/persist/ReplicaPersistInfo.java
>      private ReplicaOperationType opType;
please handle field of ReplicaOperationType.

2024-06-25 04:16 UTC, dataroaring commented on fe/fe-core/src/main/java/org/apache/doris/persist/CreateTableInfo.java
>          table = Table.read(in);
handle this in gson post proessor.

2024-06-25 08:59 UTC, dataroaring commented
run buildall

2024-06-25 09:46 UTC, iszhangpch commented
run buildall

2024-06-25 10:57 UTC, iszhangpch commented
run buildall

2024-06-25 11:36 UTC, dataroaring approved these changes, later dismissed
LGTM

2024-06-25 11:45 UTC, iszhangpch commented
run buildall

2024-06-25 11:55 UTC, iszhangpch commented
run buildall

2024-06-25 11:57 UTC, dataroaring approved these changes, later dismissed
LGTM

2024-06-25 12:13 UTC, w41ter requested changes

2024-06-25 12:13 UTC, w41ter commented on fe/fe-core/src/main/java/org/apache/doris/task/LoadTaskInfo.java
>          public List<ImportColumnDesc> descs = Lists.newArrayList();
`ImportColumnDesc` is not annotated with `SerializedName`.

2024-06-25 12:13 UTC, w41ter commented on fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/UserPropertyInfo.java
> +            uProp.user = ClusterNamespace.getNameFromFullName(uProp.user);
handle `user` in gson post processor.

2024-06-25 12:13 UTC, w41ter commented on fe/fe-core/src/main/java/org/apache/doris/persist/CreateTableInfo.java
> +            return GsonUtils.GSON.fromJson(Text.readString(in), CreateTableInfo.class);
handle `dbName` in gson post processor.

2024-06-25 13:25 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
> +    @SerializedName("dst")
naming `dsrc`
dst usually means destination

2024-06-25 13:51 UTC, iszhangpch commented on fe/fe-core/src/main/java/org/apache/doris/persist/CreateTableInfo.java
> +            return GsonUtils.GSON.fromJson(Text.readString(in), CreateTableInfo.class);
already done.

2024-06-25 14:11 UTC, iszhangpch commented
run buildall

2024-06-25 16:11 UTC, iszhangpch commented
run buildall

2024-06-25 16:19 UTC, iszhangpch commented
run buildall

2024-06-25 16:44 UTC, iszhangpch commented
run buildall

2024-06-25 19:32 UTC, iszhangpch commented
run buildall

2024-06-25 19:57 UTC, iszhangpch commented
run buildall

2024-06-25 20:07 UTC, iszhangpch commented
run buildall

2024-06-26 01:57 UTC, iszhangpch commented
run buildall

2024-06-26 06:10 UTC, dataroaring submitted a review, later dismissed
LGTM

2024-06-26 06:17 UTC, w41ter submitted a review, later dismissed

2024-06-26 06:30 UTC, dataroaring commented
run buildall

2024-06-26 06:31 UTC, w41ter approved these changes

2024-06-26 08:38 UTC, dataroaring approved these changes
LGTM

2024-06-26 11:02 UTC, merged