[improvement](sql-dialect) support multiple servers of dialect sql converter
apache/doris pull request #36674
Opened 2024-06-21 09:08 UTC by Nicholas-ehui

Add a new FE Config dialect_converter_services.
If this config is set, and the session variable enableMultiDialectConvertService is set,
Doris will poll using multiple sql converter services to convert user input sql to
specified sql dialect. but if the session variable sql_converter_service_url is set at the same time, use sql_converter_service_url. eg:

set fe.conf:
dialect_converter_services = 192.168.1.13:5001;192.168.1.13:5002;192.168.1.13:5003;192.168.1.13:5004

`
mysql> UNSET GLOBAL VARIABLE sql_converter_service_url;
Query OK, 0 rows affected (0.07 sec)

mysql> UNSET VARIABLE enable_multi_dialect_convert_service;
Query OK, 0 rows affected (0.01 sec)

mysql> set sql_dialect=presto;
Query OK, 0 rows affected (0.01 sec)

mysql> SELECT cast(start_time as varchar(20)) as col1,
    ->             array_distinct(arr_int) as col2,
    ->             FILTER(arr_str, x -> x LIKE '%World%') as col3,
    ->             to_date(value,'%Y-%m-%d') as col4,
    ->             YEAR(start_time) as col5,
    ->             date_add('month', 1, start_time) as col6,
    ->             REGEXP_EXTRACT_ALL(value, '-.') as col7,
    ->             JSON_EXTRACT('{"id": "33"}', '$.id')as col8,
    ->             element_at(arr_int, 1) as col9,
    ->             date_trunc('day',start_time) as col10
    ->          FROM test_sqlconvert
    ->          where date_trunc('day',start_time)= DATE'2024-05-20'
    ->      order by id;
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 3:
            FILTER(arr_str, x -> x LIKE '%World%') as col3,
                              ^
Encountered: ->
Expected: ||, COMMA, ., IDENTIFIER

mysql>
mysql>
mysql> set global sql_converter_service_url = "http://192.168.1.13:5001/api/v1/convert";
Query OK, 0 rows affected (0.01 sec)

mysql> SELECT cast(start_time as varchar(20)) as col1,
    ->             array_distinct(arr_int) as col2,
    ->             FILTER(arr_str, x -> x LIKE '%World%') as col3,
    ->             to_date(value,'%Y-%m-%d') as col4,
    ->             YEAR(start_time) as col5,
    ->             date_add('month', 1, start_time) as col6,
    ->             REGEXP_EXTRACT_ALL(value, '-.') as col7,
    ->             JSON_EXTRACT('{"id": "33"}', '$.id')as col8,
    ->             element_at(arr_int, 1) as col9,
    ->             date_trunc('day',start_time) as col10
    ->          FROM test_sqlconvert
    ->          where date_trunc('day',start_time)= DATE'2024-05-20'
    ->      order by id;
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
| col1                | col2      | col3      | col4       | col5 | col6                | col7        | col8 | col9 | col10               |
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
| 2024-05-20 13:14:52 | [1, 2, 3] | ["World"] | 2024-01-14 | 2024 | 2024-06-20 13:14:52 | ['-0','-1'] | "33" |    1 | 2024-05-20 00:00:00 |
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
1 row in set (0.36 sec)

mysql>
mysql> UNSET GLOBAL VARIABLE sql_converter_service_url;
Query OK, 0 rows affected (0.03 sec)

mysql> SELECT cast(start_time as varchar(20)) as col1,
    ->             array_distinct(arr_int) as col2,
    ->             FILTER(arr_str, x -> x LIKE '%World%') as col3,
    ->             to_date(value,'%Y-%m-%d') as col4,
    ->             YEAR(start_time) as col5,
    ->             date_add('month', 1, start_time) as col6,
    ->             REGEXP_EXTRACT_ALL(value, '-.') as col7,
    ->             JSON_EXTRACT('{"id": "33"}', '$.id')as col8,
    ->             element_at(arr_int, 1) as col9,
    ->             date_trunc('day',start_time) as col10
    ->          FROM test_sqlconvert
    ->          where date_trunc('day',start_time)= DATE'2024-05-20'
    ->      order by id;
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 3:
            FILTER(arr_str, x -> x LIKE '%World%') as col3,
                              ^
Encountered: ->
Expected: ||, COMMA, ., IDENTIFIER

mysql>
mysql>
mysql> set enable_multi_dialect_convert_service = true;
Query OK, 0 rows affected (0.01 sec)

mysql> SELECT cast(start_time as varchar(20)) as col1,
    ->             array_distinct(arr_int) as col2,
    ->             FILTER(arr_str, x -> x LIKE '%World%') as col3,
    ->             to_date(value,'%Y-%m-%d') as col4,
    ->             YEAR(start_time) as col5,
    ->             date_add('month', 1, start_time) as col6,
    ->             REGEXP_EXTRACT_ALL(value, '-.') as col7,
    ->             JSON_EXTRACT('{"id": "33"}', '$.id')as col8,
    ->             element_at(arr_int, 1) as col9,
    ->             date_trunc('day',start_time) as col10
    ->          FROM test_sqlconvert
    ->          where date_trunc('day',start_time)= DATE'2024-05-20'
    ->      order by id;
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
| col1                | col2      | col3      | col4       | col5 | col6                | col7        | col8 | col9 | col10               |
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
| 2024-05-20 13:14:52 | [1, 2, 3] | ["World"] | 2024-01-14 | 2024 | 2024-06-20 13:14:52 | ['-0','-1'] | "33" |    1 | 2024-05-20 00:00:00 |
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
1 row in set (0.40 sec)
`

2024-06-21 09:14 UTC, Nicholas-ehui commented
`mysql> UNSET GLOBAL VARIABLE sql_converter_service_url;
Query OK, 0 rows affected (0.07 sec)

mysql> UNSET VARIABLE enable_multi_dialect_convert_service;
Query OK, 0 rows affected (0.01 sec)

mysql> set sql_dialect=presto;
Query OK, 0 rows affected (0.01 sec)

mysql> SELECT cast(start_time as varchar(20)) as col1,
-> array_distinct(arr_int) as col2,
-> FILTER(arr_str, x -> x LIKE '%World%') as col3,
-> to_date(value,'%Y-%m-%d') as col4,
-> YEAR(start_time) as col5,
-> date_add('month', 1, start_time) as col6,
-> REGEXP_EXTRACT_ALL(value, '-.') as col7,
-> JSON_EXTRACT('{"id": "33"}', '$.id')as col8,
-> element_at(arr_int, 1) as col9,
-> date_trunc('day',start_time) as col10
-> FROM test_sqlconvert
-> where date_trunc('day',start_time)= DATE'2024-05-20'
-> order by id;
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 3:
FILTER(arr_str, x -> x LIKE '%World%') as col3,
^
Encountered: ->
Expected: ||, COMMA, ., IDENTIFIER

mysql>
mysql>
mysql> set global sql_converter_service_url = "http://192.168.1.13:5001/api/v1/convert";
Query OK, 0 rows affected (0.01 sec)

mysql> SELECT cast(start_time as varchar(20)) as col1,
-> array_distinct(arr_int) as col2,
-> FILTER(arr_str, x -> x LIKE '%World%') as col3,
-> to_date(value,'%Y-%m-%d') as col4,
-> YEAR(start_time) as col5,
-> date_add('month', 1, start_time) as col6,
-> REGEXP_EXTRACT_ALL(value, '-.') as col7,
-> JSON_EXTRACT('{"id": "33"}', '$.id')as col8,
-> element_at(arr_int, 1) as col9,
-> date_trunc('day',start_time) as col10
-> FROM test_sqlconvert
-> where date_trunc('day',start_time)= DATE'2024-05-20'
-> order by id;
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
| col1 | col2 | col3 | col4 | col5 | col6 | col7 | col8 | col9 | col10 |
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
| 2024-05-20 13:14:52 | [1, 2, 3] | ["World"] | 2024-01-14 | 2024 | 2024-06-20 13:14:52 | ['-0','-1'] | "33" | 1 | 2024-05-20 00:00:00 |
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
1 row in set (0.36 sec)

mysql>
mysql> UNSET GLOBAL VARIABLE sql_converter_service_url;
Query OK, 0 rows affected (0.03 sec)

mysql> SELECT cast(start_time as varchar(20)) as col1,
-> array_distinct(arr_int) as col2,
-> FILTER(arr_str, x -> x LIKE '%World%') as col3,
-> to_date(value,'%Y-%m-%d') as col4,
-> YEAR(start_time) as col5,
-> date_add('month', 1, start_time) as col6,
-> REGEXP_EXTRACT_ALL(value, '-.') as col7,
-> JSON_EXTRACT('{"id": "33"}', '$.id')as col8,
-> element_at(arr_int, 1) as col9,
-> date_trunc('day',start_time) as col10
-> FROM test_sqlconvert
-> where date_trunc('day',start_time)= DATE'2024-05-20'
-> order by id;
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 3:
FILTER(arr_str, x -> x LIKE '%World%') as col3,
^
Encountered: ->
Expected: ||, COMMA, ., IDENTIFIER

mysql>
mysql>
mysql> set enable_multi_dialect_convert_service = true;
Query OK, 0 rows affected (0.01 sec)

mysql> SELECT cast(start_time as varchar(20)) as col1,
-> array_distinct(arr_int) as col2,
-> FILTER(arr_str, x -> x LIKE '%World%') as col3,
-> to_date(value,'%Y-%m-%d') as col4,
-> YEAR(start_time) as col5,
-> date_add('month', 1, start_time) as col6,
-> REGEXP_EXTRACT_ALL(value, '-.') as col7,
-> JSON_EXTRACT('{"id": "33"}', '$.id')as col8,
-> element_at(arr_int, 1) as col9,
-> date_trunc('day',start_time) as col10
-> FROM test_sqlconvert
-> where date_trunc('day',start_time)= DATE'2024-05-20'
-> order by id;
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
| col1 | col2 | col3 | col4 | col5 | col6 | col7 | col8 | col9 | col10 |
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
| 2024-05-20 13:14:52 | [1, 2, 3] | ["World"] | 2024-01-14 | 2024 | 2024-06-20 13:14:52 | ['-0','-1'] | "33" | 1 | 2024-05-20 00:00:00 |
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
1 row in set (0.40 sec)
`

2024-06-21 09:17 UTC, Nicholas-ehui commented
run buildall

2024-06-21 09:25 UTC, Nicholas-ehui commented
```
mysql> UNSET GLOBAL VARIABLE sql_converter_service_url;
Query OK, 0 rows affected (0.07 sec)

mysql> UNSET VARIABLE enable_multi_dialect_convert_service;
Query OK, 0 rows affected (0.01 sec)

mysql> set sql_dialect=presto;
Query OK, 0 rows affected (0.01 sec)

mysql> SELECT cast(start_time as varchar(20)) as col1,
-> array_distinct(arr_int) as col2,
-> FILTER(arr_str, x -> x LIKE '%World%') as col3,
-> to_date(value,'%Y-%m-%d') as col4,
-> YEAR(start_time) as col5,
-> date_add('month', 1, start_time) as col6,
-> REGEXP_EXTRACT_ALL(value, '-.') as col7,
-> JSON_EXTRACT('{"id": "33"}', '$.id')as col8,
-> element_at(arr_int, 1) as col9,
-> date_trunc('day',start_time) as col10
-> FROM test_sqlconvert
-> where date_trunc('day',start_time)= DATE'2024-05-20'
-> order by id;
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 3:
FILTER(arr_str, x -> x LIKE '%World%') as col3,
^
Encountered: ->
Expected: ||, COMMA, ., IDENTIFIER

mysql>
mysql>
mysql> set global sql_converter_service_url = "http://192.168.1.13:5001/api/v1/convert";
Query OK, 0 rows affected (0.01 sec)

mysql> SELECT cast(start_time as varchar(20)) as col1,
-> array_distinct(arr_int) as col2,
-> FILTER(arr_str, x -> x LIKE '%World%') as col3,
-> to_date(value,'%Y-%m-%d') as col4,
-> YEAR(start_time) as col5,
-> date_add('month', 1, start_time) as col6,
-> REGEXP_EXTRACT_ALL(value, '-.') as col7,
-> JSON_EXTRACT('{"id": "33"}', '$.id')as col8,
-> element_at(arr_int, 1) as col9,
-> date_trunc('day',start_time) as col10
-> FROM test_sqlconvert
-> where date_trunc('day',start_time)= DATE'2024-05-20'
-> order by id;
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
| col1 | col2 | col3 | col4 | col5 | col6 | col7 | col8 | col9 | col10 |
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
| 2024-05-20 13:14:52 | [1, 2, 3] | ["World"] | 2024-01-14 | 2024 | 2024-06-20 13:14:52 | ['-0','-1'] | "33" | 1 | 2024-05-20 00:00:00 |
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
1 row in set (0.36 sec)

mysql>
mysql> UNSET GLOBAL VARIABLE sql_converter_service_url;
Query OK, 0 rows affected (0.03 sec)

mysql> SELECT cast(start_time as varchar(20)) as col1,
-> array_distinct(arr_int) as col2,
-> FILTER(arr_str, x -> x LIKE '%World%') as col3,
-> to_date(value,'%Y-%m-%d') as col4,
-> YEAR(start_time) as col5,
-> date_add('month', 1, start_time) as col6,
-> REGEXP_EXTRACT_ALL(value, '-.') as col7,
-> JSON_EXTRACT('{"id": "33"}', '$.id')as col8,
-> element_at(arr_int, 1) as col9,
-> date_trunc('day',start_time) as col10
-> FROM test_sqlconvert
-> where date_trunc('day',start_time)= DATE'2024-05-20'
-> order by id;
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 3:
FILTER(arr_str, x -> x LIKE '%World%') as col3,
^
Encountered: ->
Expected: ||, COMMA, ., IDENTIFIER

mysql>
mysql>
mysql> set enable_multi_dialect_convert_service = true;
Query OK, 0 rows affected (0.01 sec)

mysql> SELECT cast(start_time as varchar(20)) as col1,
-> array_distinct(arr_int) as col2,
-> FILTER(arr_str, x -> x LIKE '%World%') as col3,
-> to_date(value,'%Y-%m-%d') as col4,
-> YEAR(start_time) as col5,
-> date_add('month', 1, start_time) as col6,
-> REGEXP_EXTRACT_ALL(value, '-.') as col7,
-> JSON_EXTRACT('{"id": "33"}', '$.id')as col8,
-> element_at(arr_int, 1) as col9,
-> date_trunc('day',start_time) as col10
-> FROM test_sqlconvert
-> where date_trunc('day',start_time)= DATE'2024-05-20'
-> order by id;
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
| col1 | col2 | col3 | col4 | col5 | col6 | col7 | col8 | col9 | col10 |
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
| 2024-05-20 13:14:52 | [1, 2, 3] | ["World"] | 2024-01-14 | 2024 | 2024-06-20 13:14:52 | ['-0','-1'] | "33" | 1 | 2024-05-20 00:00:00 |
+---------------------+-----------+-----------+------------+------+---------------------+-------------+------+------+---------------------+
1 row in set (0.40 sec)

```

2024-06-22 03:25 UTC, morningman commented
2 questions:
1. Why do we need multi convertor services? What is the use case?
2. Why not just use `sql_converter_service_url` variable and make it support multiple urls? so that we can remove the fe config item and also remove the `enable_multi_dialect_convert_service` variable. If `sql_converter_service_url` has only one url, use that one. If `sql_converter_service_url` has multi urls, poll each of them

2024-06-22 05:06 UTC, Nicholas-ehui commented
> 2个问题：
> 
> 1. 为什么我们需要多转换器服务？用例是什么？
> 2. 为什么不直接使用变量并使其支持多个 url？这样我们就可以删除 FE 配置项并删除变量。如果只有一个 URL，请使用该 URL。如果有多个 URL，请轮询每个 URL`sql_converter_service_url``enable_multi_dialect_convert_service``sql_converter_service_url``sql_converter_service_url`

2024-06-22 05:25 UTC, Nicholas-ehui commented
> 2 questions:
> 
> 1. Why do we need multi convertor services? What is the use case?
> 2. Why not just use `sql_converter_service_url` variable and make it support multiple urls? so that we can remove the fe config item and also remove the `enable_multi_dialect_convert_service` variable. If `sql_converter_service_url` has only one url, use that one. If `sql_converter_service_url` has multi urls, poll each of them

![image](https://github.com/apache/doris/assets/81006630/4174e991-37e7-419e-b0c5-6f861d58c64a)
1: If multiple FE nodes have started the Doris SQL Convertor service, how to use the configured multiple converters? Currently, each FE can only use at most one converter set by sql_converter_service_url.

![image](https://github.com/apache/doris/assets/81006630/7100f6bd-4785-460d-9076-58b89c49cf97)
2: I thought about setting up multiple conversion servers using only sql_converter_service_url, but I didn’t know how to describe it in one URL, so I used fe.conf + enable_multi_dialect_convert_service

2024-06-22 15:22 UTC, morningman commented
> > 2 questions:
> > 
> > 1. Why do we need multi convertor services? What is the use case?
> > 2. Why not just use `sql_converter_service_url` variable and make it support multiple urls? so that we can remove the fe config item and also remove the `enable_multi_dialect_convert_service` variable. If `sql_converter_service_url` has only one url, use that one. If `sql_converter_service_url` has multi urls, poll each of them
> 
> ![image](https://private-user-images.githubusercontent.com/81006630/341937400-4174e991-37e7-419e-b0c5-6f861d58c64a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjk3MzYsIm5iZiI6MTcxOTA2OTQzNiwicGF0aCI6Ii84MTAwNjYzMC8zNDE5Mzc0MDAtNDE3NGU5OTEtMzdlNy00MTllLWIwYzUtNmY4NjFkNThjNjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE1MTcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYjM2YmRhNjdmYmM4M2E1ZGUxZWY4NzZjMzE2MTUyZTE0NDQ2ODBjNmJjNjI0ZGE4YTNiZjcwMTNlNWE0NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T0YULMEpaDPw3RSpxHk7o6ivCHn9uoYYaJ1BQUYeYYY) 1: If multi FE nodes have started the Doris SQL Convertor service, how to use these converter services? Currently, each FE can only use at most one converter set by sql_converter_service_url.
> 
> ![image](https://private-user-images.githubusercontent.com/81006630/341937493-7100f6bd-4785-460d-9076-58b89c49cf97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjk3MzYsIm5iZiI6MTcxOTA2OTQzNiwicGF0aCI6Ii84MTAwNjYzMC8zNDE5Mzc0OTMtNzEwMGY2YmQtNDc4NS00NjBkLTkwNzYtNThiODljNDljZjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE1MTcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMGMwMzEzOGU0NTQ4YjVhOGU5Mjg5MzkzMGZlOGQwNmU2MDRmNDMwODMyOGVlZTE4MjQwZDY4NGMzODFmZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I968i_rnVe4-f1LyJ-p4stWGuFgj9pGwDOkEfC1rwJQ) 2: I thought about setting up multiple conversion servers using only sql_converter_service_url, but I didn’t know how to describe it in one URL, so I used fe.conf `dialect_converter_services` + session variable `enable_multi_dialect_convert_service`

Oh, I see.
The recommendation in document is not very clear.
Actually, it means that user can deploy sql convertor services(same service) on each FE node,
and then setting url using the loopback ip: `127.0.0.1`.
So that each FE node can access its own converter service locally without network traffic.

In addition, user can also deploy only on convertor service on arbitrary node and setting url using the
node ip, just making sure this ip can be accessed by all FEs

2024-06-24 02:07 UTC, Nicholas-ehui commented
Yes, what you mentioned above is that each FE can use at most one dialect converter server. In this PR, each FE can use multi dialect converter servers using polling. Check to see if this PR is needed? If don’t need it, you can close it.

2024-06-25 02:58 UTC, morningman commented
> Yes, what you mentioned above is that each FE can use at most one dialect converter server. In this PR, each FE can use multi dialect converter servers using polling. Check to see if this PR is needed? If don’t need it, you can close it.

I don't think we need to start multi converter servers for a single FE?

2024-06-25 03:45 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/plugin/dialect/HttpDialectConverterPlugin.java
> +        String  dialectConverterServices = Config.dialect_converter_services;
double spaces after `String`

2024-06-25 03:45 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/plugin/dialect/HttpDialectConverterPlugin.java
> +            return originSql;
Should we log here if the conversion fails? 
The log should contain how many times tried and which server has been tried.

2024-06-25 03:45 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/plugin/dialect/HttpDialectConverterPlugin.java
> +                String chooseServer = dialectConverterSerInfo.get(chooseServerIdx++ % dialectConverterSerInfo.size());
We may have to skip the servers that have been marked unavailable, which can be deduced by line 152, for better availability.
e.g. remember some unavailable servers, and reduce the possibility accessing that servers with a back-off algorithm.

2024-06-25 03:46 UTC, gavinchou commented on fe/fe-common/src/main/java/org/apache/doris/common/Config.java
> +    public static String dialect_converter_services = "";
Add an example here, what the format is
e.g. `a.com:8080;b.com:8090`

2024-06-25 03:47 UTC, gavinchou requested changes
Fix some obvious errors and consider further improvement.

2024-07-18 15:51 UTC, closed without merging