[enhance](Azure) Check delete operation's response on Azure Blob Storage
apache/doris pull request #36800
Opened 2024-06-25 08:11 UTC by ByteYue

## Proposed changes

Issue Number: close #xxx

We should check if the delete operation is successful or not.

2024-06-25 08:34 UTC, gavinchou requested changes

2024-06-25 08:34 UTC, gavinchou commented on be/src/io/fs/azure_obj_storage_client.cpp
> +struct AzureBatchDeleter {
type alias the name space for readability, such as using asb = Azure::Storage::Blobs

2024-06-25 08:34 UTC, gavinchou commented on be/src/io/fs/azure_obj_storage_client.cpp
> +    AzureBatchDeleter(Azure::Storage::Blobs::BlobContainerClient* client,
add sufficient comments for all functions and params

2024-06-25 08:34 UTC, gavinchou commented on be/src/io/fs/azure_obj_storage_client.cpp
> +public:
redundant public?

2024-06-25 08:34 UTC, gavinchou commented on be/src/io/fs/azure_obj_storage_client.cpp
> +        std::ranges::for_each(std::ranges::subrange(begin, chunkEnd),
`chunkEnd` style is not correct, pls check other occurrences

and, capture only what is used

2024-06-25 08:34 UTC, gavinchou commented on be/src/io/fs/azure_obj_storage_client.cpp
> +        auto resp = do_azure_client_call([&]() { _client->SubmitBatch(_batch); }, _opts);
Is there any limit for this _batch, say is it ok that  10000000 blobs to delete?

2024-06-25 08:43 UTC, gavinchou requested changes

2024-06-25 08:43 UTC, gavinchou commented on be/src/io/fs/azure_obj_storage_client.cpp
> +        }
```suggestion
        for (auto& i : deferred_resps) {
            if (i.GetResponse().Value.Deleted) continue;
            auto status = convert_to_obj_response(Status::InternalError<false>(
                                    "Failed to batch delete azure blob, path msg {}",
                                    wrap_object_storage_path_msg(_opts)))};
            return {.status = std::move(status)};
        }
```

2024-06-25 09:31 UTC, ByteYue commented
run buildall

2024-06-26 04:54 UTC, ByteYue commented
run buildall

2024-06-26 06:03 UTC, ByteYue commented
run buildall

2024-06-26 07:01 UTC, gavinchou commented on be/src/io/fs/azure_obj_storage_client.cpp
> +        return {};
explicitly set {statuscode = ok}

2024-06-26 07:01 UTC, gavinchou commented on be/src/io/fs/azure_obj_storage_client.cpp
> +        return {};
ditto

2024-06-26 07:02 UTC, gavinchou commented on cloud/src/recycler/azure_obj_client.cpp
> +        return {};
ditto

2024-06-26 07:02 UTC, gavinchou approved these changes

2024-06-26 07:03 UTC, ByteYue commented on cloud/src/recycler/azure_obj_client.cpp
> +        return {};
I'll improve it in #36829

2024-06-26 07:55 UTC, Yukang-Lian approved these changes

2024-06-26 09:07 UTC, merged