[feature](Azure) Implement generate_presigned_url function for Azure object client
apache/doris pull request #36829
Opened 2024-06-25 13:35 UTC by ByteYue

## Proposed changes

implement generate_presigned_url function for azure object client.

2024-06-25 17:37 UTC, gavinchou requested changes

2024-06-25 17:37 UTC, gavinchou commented on be/src/io/fs/azure_obj_storage_client.cpp
> +    sas_builder.SetPermissions(Azure::Storage::Sas::BlobSasPermissions::Write);
We also need "Read" permission here.
Make sure that this signature is constrained by the specific blob.

And USE HTTPS only here
```
sas_biulder.Protocol = SasProtocol.HttpsOnly;
```

2024-06-26 07:02 UTC, liaoxin01 approved these changes, later dismissed
LGTM

2024-06-26 07:05 UTC, gavinchou commented on be/src/io/fs/azure_obj_storage_client.cpp
> +                               Azure::Storage::Sas::BlobSasPermissions::Write);
No need `write` permission

2024-06-26 09:18 UTC, ByteYue commented
run buildall

2024-06-26 09:24 UTC, ByteYue commented
run buildall

2024-06-26 09:25 UTC, gavinchou approved these changes

2024-06-26 09:27 UTC, gavinchou requested changes

2024-06-26 09:27 UTC, gavinchou commented on cloud/src/recycler/obj_store_accessor.h
> +    static ObjectStorageResponse OK() { return {}; }
`return {};` -> return explicit OK  not the default one.

2024-06-26 09:40 UTC, ByteYue commented
run buildall

2024-06-26 14:19 UTC, gavinchou approved these changes

2024-06-26 14:38 UTC, platoneko approved these changes

2024-06-27 01:56 UTC, merged