[enhancement](trash) support skip trash, update trash default expire time
apache/doris pull request #37170
Opened 2024-07-02 12:52 UTC by zhannngchen

## Proposed changes

Issue Number: close #xxx

1. if user set `trash_file_expire_time_sec` to 0, skip trash directly
2. update trash_file_expire_time_sec default value from 3 days to 1 day

2024-07-02 12:54 UTC, dataroaring submitted a review, later dismissed
LGTM

2024-07-02 13:42 UTC, gavinchou approved these changes, later dismissed

2024-07-03 01:55 UTC, yujun777 commented on be/src/olap/data_dir.cpp
> +    if (0 == config::trash_file_expire_time_sec) {
config::trash_file_expire_time_sec <= 0

2024-07-03 01:59 UTC, yujun777 commented on be/src/olap/data_dir.cpp
> +        return io::global_local_filesystem()->delete_directory(tablet_path);
after delete the tablet_path (it is root_dir/shard/tablet_id/schema_hash),   need delete path root_dir/shard/tablet_id if it is empty.

see line 950:  RETURN_IF_ERROR(delete_tablet_parent_path_if_empty(tablet_path))

2024-07-03 02:00 UTC, yujun777 requested changes
need update

2024-07-03 02:10 UTC, yujun777 commented on be/src/common/config.cpp
> +DEFINE_mInt32(trash_file_expire_time_sec, "86400");
maybe can change this default value to 0.   not found any user case recover tablet from trash.

2024-07-03 03:04 UTC, zhannngchen commented on be/src/common/config.cpp
> +DEFINE_mInt32(trash_file_expire_time_sec, "86400");
default 0 might be too aggressive?
it's a behavior change

2024-07-03 03:05 UTC, zhannngchen commented
run buildall

2024-07-03 03:19 UTC, zhannngchen commented
run buildall

2024-07-03 09:36 UTC, yujun777 commented on be/src/common/config.cpp
> +DEFINE_mInt32(trash_file_expire_time_sec, "86400");
trash 很费，实际中没用，trash 的副本在fe中元数据都是必定不存在的，即使手工把它从trash 中拉回来，在fe 元数据也不含它，  把它搞回来后， 都还不能用。 

真正的回收站是 fe catalog recycle bin， 这部分的数据在BE中是一直在data目录中的，跟trash没关系， 可以通过recover 命令把 fe recycle bin 中的数据给恢复过来。

线上给用户建议时，都是直接建议直接把这个值设置为0的。

后续再提个pr把它清了吧

2024-07-03 09:36 UTC, yujun777 approved these changes
LGTM

2024-07-03 14:47 UTC, dataroaring approved these changes
LGTM

2024-07-03 14:48 UTC, merged