[chore](audit) Optimize the sql length in audit logs
apache/doris pull request #37894
Opened 2024-07-16 07:08 UTC by yagagagaga

## Proposed changes

- Add annotation information to the `insert into value` statement
- Let the SQL length in the audit log be controlled by `GlobalVariable.auditPluginMaxSqlLength`

2024-07-16 07:37 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/qe/AuditLogHelper.java
> +        origStmt = origStmt.replace("\n", " ").substring(0, length);
\r\n

2024-07-16 13:06 UTC, gavinchou commented on fe/fe-core/src/main/java/org/apache/doris/qe/AuditLogHelper.java
> +        int length = Math.min(GlobalVariable.auditPluginMaxSqlLength, origStmt.length());
return origstmt if origStmt.length < maxLength;

2024-07-17 06:19 UTC, morrySnow approved these changes, later dismissed

2024-07-17 16:22 UTC, gavinchou commented on regression-test/suites/audit/test_audit_log_behavior.groovy
> +        while (res.isEmpty()) {
this will be a dead loop if something is wrong.

2024-07-17 16:32 UTC, gavinchou requested changes

2024-07-22 06:41 UTC, yagagagaga commented
run buildall

2024-07-22 06:53 UTC, gavinchou approved these changes

2024-07-22 07:17 UTC, LiBinfeng-01 approved these changes

2024-07-22 09:04 UTC, yagagagaga commented
run buildall

2024-07-23 03:38 UTC, yagagagaga commented
run buildall

2024-07-23 03:45 UTC, yagagagaga commented
/run buildall

2024-07-23 12:41 UTC, luwei16 approved these changes

2024-07-23 12:42 UTC, merged