Add segment v2 footer meta viewer
apache/doris pull request #3822
Opened 2020-06-10 12:18 UTC by yangzhg

Add segment  v2 footer meta viewer tool

2020-06-10 14:51 UTC, morningman reviewed
Hi, you need to update the doc~

2020-06-10 16:02 UTC, chaoyli requested changes

2020-06-16 04:02 UTC, yangzhg commented on be/src/tools/meta_tool.cpp
> +#include "env/env.h"
@chaoyli please review again

2020-06-16 05:36 UTC, kangkaisen commented on docs/zh-CN/administrator-guide/operation/tablet-meta-tool.md
> +这个命令是为了查看SegmentV2 的SegmentFooterPB信息，以json 形式展示出来
Would better show the command result by a simple example. Because most of people don't know what's SegmentFooterPB.

2020-06-17 05:50 UTC, chaoyli submitted a review, later dismissed

2020-06-18 05:52 UTC, morningman commented on docs/en/administrator-guide/operation/tablet-meta-tool.md
> +./lib/meta_tool --operation=how_meta --root_path=/path/to/root_path --pb_header_path=path
```suggestion
./lib/meta_tool --operation=show_meta --root_path=/path/to/root_path --pb_header_path=path
```

2020-06-18 06:49 UTC, morningman approved these changes
LGTM

2020-06-19 01:32 UTC, merged