[]
apache/doris pull request #38305
Opened 2024-07-24 09:04 UTC by Mryange

## Proposed changes

Issue Number: close #xxx

2024-07-24 09:04 UTC, Mryange commented
run buildall

2024-07-25 06:37 UTC, Mryange commented
run buildall

2024-07-26 09:31 UTC, zclllyybb requested changes
__ARM_NEON is enabled as far back as arm-v7. crc32cw is supported since arm-v8. so in some arm-v7 it will lead to compilation failure.

2024-07-26 09:38 UTC, Mryange commented
run buildall

2024-07-26 10:21 UTC, Mryange commented
run buildall

2024-07-26 14:08 UTC, zclllyybb approved these changes
LGTM. should pass real arm P0 before merging

2024-07-29 06:36 UTC, Mryange commented
run buildall

2024-07-30 10:09 UTC, closed without merging