[opt](Nereids): Remove useless code of rule `PullUpJoinFromUnionAll`
apache/doris pull request #38529
Opened 2024-07-30 09:13 UTC by XieJiann

## Proposed changes

Issue Number: close #xxx

2024-07-30 09:13 UTC, XieJiann commented
run buildall

2024-07-30 09:16 UTC, morrySnow approved these changes, later dismissed

2024-07-30 09:53 UTC, XieJiann commented
run buildall

2024-07-30 12:13 UTC, XieJiann commented
run buildall

2024-07-31 01:59 UTC, xzj7019 approved these changes

2024-07-31 02:02 UTC, XieJiann commented
run buildall

2024-07-31 03:59 UTC, xzj7019 commented
> ## Proposed changes
> Issue Number: close #xxx

Hold on this pr until the new rules are ready.

2024-07-31 04:00 UTC, xzj7019 requested changes
Hold on this pr until the new rules are ready.

2024-07-31 05:02 UTC, XieJiann commented
run buildall

2024-07-31 06:15 UTC, XieJiann commented
run buildall

2025-01-29 00:11 UTC, closed without merging