[fix](ES Catalog)Only push down literal expr in binary predicate
apache/doris pull request #39844
Opened 2024-08-23 08:17 UTC by qidaye

## Proposed changes

Issue Number: close #xxx

2024-08-23 08:17 UTC, qidaye commented
run buildall

2024-08-23 10:55 UTC, morrySnow requested changes

2024-08-23 10:55 UTC, morrySnow commented on fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/QueryBuilders.java
> +                return parseBinaryPredicate(literalExpr, opCode, column, needDateCompat);
flip opcode if value from left side

2024-08-29 03:22 UTC, qidaye commented
run buildall

2024-08-29 06:08 UTC, morrySnow approved these changes

2024-08-29 07:29 UTC, airborne12 approved these changes
LGTM

2024-08-29 07:29 UTC, merged