applyInnerJoinConditionReorganizeRule
apache/doris pull request #4000
Opened 2020-07-02 03:52 UTC by wutiangan

fix #3908

2020-07-03 03:04 UTC, spaces-X commented on fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
> +                if (father.getChild(0) == expr) {
father may be null here.

2020-07-05 14:11 UTC, morningman commented on fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
> +    boolean ifExprIsCompandAndPredicate(Expr expr) {
```suggestion
    boolean ifExprIsCompoundAndPredicate(Expr expr) {
```

2020-07-22 14:10 UTC, spaces-X commented
@morningman @wutiangan 
Fix the NullPointerException of the variable `father` in this [PR ](https://github.com/apache/incubator-doris/pull/4145)

2020-07-23 08:04 UTC, wuyunfeng requested changes
Suggest you change the title for this PR, You should describe what you did in one sentence for your PR. Thanks.

BTW the title for this PR is so disgusted

2020-08-06 10:51 UTC, wuyunfeng commented
@wutiangan Are you still work on this PR?

2022-05-23 12:19 UTC, jackwener commented
Please rebase the `master` and add an UT for this PR.

2022-06-21 02:26 UTC, closed without merging