[branch-2.1](hive) support hive write text table (#38549)
apache/doris pull request #40063
Opened 2024-08-28 11:10 UTC by suxiaogang223

1. Support write hive text table
2. Add SessionVariable `hive_text_compression` to write compressed hive text table
3. Supported compression type: gzip, bzip2, snappy, lz4, zstd

pick from https://github.com/apache/doris/pull/38549

2024-08-28 11:11 UTC, suxiaogang223 commented
run buildall

2024-08-28 14:10 UTC, suxiaogang223 commented
run buildall

2024-08-28 14:13 UTC, yiguolei requested changes
This Pr need detailed review
Pls not merge it now

2024-08-29 08:50 UTC, yiguolei approved these changes

2024-08-29 08:50 UTC, merged