[feature](func) support timestmamp(datetime, zone), DATE(datetime,zone)
apache/doris pull request #40231
Opened 2024-09-02 01:46 UTC by justfortaste

SELECT TIMESTAMP("2008-12-25 15:30:00", "America/Los_Angeles") AS timestamp_str;
+---------------------+
| timestamp_str       |
+---------------------+
| 2008-12-24 23:30:00 |
+---------------------+
1 row in set (0.01 sec)
    
select date(datetime '2020-01-01 23:00:00','Asia/Shanghai');
+----------------------------------------------------------------+
| date(CAST('2020-01-01 23:00:00' AS datetime), 'Asia/Shanghai') |
+----------------------------------------------------------------+
| 2020-01-02                                                     |
+----------------------------------------------------------------+

2024-09-02 02:45 UTC, justfortaste commented
run buildall

2024-09-02 03:38 UTC, zclllyybb commented
why we need this function and `convert_tz` is not enough?

2024-09-02 11:16 UTC, justfortaste commented
run buildall

2024-09-03 13:01 UTC, lide-reed approved these changes, later dismissed
LGTM

2024-09-04 05:06 UTC, zclllyybb requested changes
please explain why we need these functions

2024-09-04 07:02 UTC, morrySnow commented on fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/DateTimeExtractAndTransform.java
> +        return new DateV2Literal(localDateTime.getYear(), localDateTime.getMonthValue(), localDateTime.getDayOfMonth());
should return DateLiteral

2024-09-04 07:02 UTC, morrySnow commented on fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Date.java
> +     * constructor with 1 argument.
```suggestion
     * constructor with 2 argument.
```

2024-09-04 07:02 UTC, morrySnow commented on fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Timestamp.java
>              FunctionSignature.ret(DateTimeType.INSTANCE).args(DateTimeType.INSTANCE)
please groups by arg count, e.g. put 1 arg signatures togather and 2 args signatures togather

2024-09-04 07:44 UTC, zclllyybb requested changes
1. you can still set nullmap and return `ColumnNullable` with `use_default_implementation_for_nulls` is true. the framework will combine them al last.
2. please add testcases to ensure these situations are covered:
2.1. empty table
2.2. nullable column (no, part, all)
2.3. const column (no, part, all)
2.4. const and nullable (you could use function `nullable` to construct cases with literal)
3. remove support of V1 datelike type

2024-09-04 07:44 UTC, zclllyybb commented on be/src/vec/functions/function_convert_tz.h
> +    bool use_default_implementation_for_nulls() const override { return false; }
should be true(that is ,remove this)

2024-09-04 07:44 UTC, zclllyybb commented on be/src/vec/functions/function_convert_tz.h
> +            check_set_nullable(argument_columns[i], result_null_map_column, col_const[i]);
then you could remove this.

2024-09-04 14:26 UTC, justfortaste commented
run buildall

2024-09-06 02:26 UTC, zclllyybb approved these changes
LGTM

2024-09-11 14:52 UTC, morrySnow approved these changes

2024-09-24 11:41 UTC, lide-reed approved these changes
LGTM

2024-09-26 03:32 UTC, lide-reed approved these changes
LGTM

2025-03-31 00:13 UTC, closed without merging