Add delayed deletion of rowsets function, fix -230 error.
apache/doris pull request #4039
Opened 2020-07-07 08:51 UTC by ZhangYu0123

Related issue #4017, main changes as follows:
(1) Add expired_snapshot_rs_version_map，_expired_snapshot_rs_metas，(2) Add  VersionedRowsetTracker record compacted path version， (3) Record path version when rowsets compact，(4) In gc process, add expired snapshot rowsets to unused set to remove.

2020-07-07 08:57 UTC, wuyunfeng requested changes

2020-07-07 08:57 UTC, wuyunfeng commented on be/src/common/config.h
> +    CONF_mInt32(tablet_rowset_expired_snapshot_sweep_time, "1800");
It is better to add `unit` to your config item

2020-07-07 08:57 UTC, wuyunfeng commented on be/src/olap/rowset_graph.cpp
> +            //   begin from min_begin_version
merge this two comment into one line maybe better

2020-07-07 08:57 UTC, wuyunfeng commented on be/src/olap/rowset_graph.cpp
> +            //   tracker the first
```suggestion
            // tracker the first
```

2020-07-07 08:57 UTC, wuyunfeng commented on be/src/olap/tablet.cpp
> +    _versioned_rs_tracker.construct_versioned_tracker(_tablet_meta->all_rs_metas(),
66 - 67 has nonstandard format

2020-07-14 02:31 UTC, wutiangan commented on be/src/olap/tablet.cpp
> +    // _rs_graph.add_version_to_graph(rowset->version());
remove this line？

2020-07-15 13:54 UTC, morningman commented on be/src/olap/tablet.cpp
> +                    _tablet_meta->all_rs_metas(), expired_snapshot_version_path_map);
expired_snapshot_version_path_map does not contains the expired path you just deleted.

2020-07-15 13:54 UTC, morningman commented on be/src/olap/tablet.cpp
> +                    << "] not find in expired snapshot rs version ";
```suggestion
                    << "] not find in expired snapshot rs version map";
```

2020-07-15 13:54 UTC, morningman commented on be/src/olap/tablet.cpp
> +            _delete_expired_snapshot_rowset_by_version(timestampedVersion->version());
in `_delete_expired_snapshot_rowset_by_version`, we call `_expired_snapshot_rs_version_map.erase()` again, which is duplicated.

2020-07-15 13:54 UTC, morningman commented on be/src/olap/tablet_meta.cpp
> +            break;
Are you sure there will be only one version which equals to the specified version?

2020-07-17 15:23 UTC, morningman approved these changes
LGTM

2020-07-17 15:23 UTC, morningman approved these changes
LGTM

2020-07-19 14:04 UTC, merged