[feature](cloud) Add more ut and bvar for txn lazy commit
apache/doris pull request #40486
Opened 2024-09-06 09:30 UTC by SWJTU-ZhangLei

## Proposed changes

Issue Number: close #xxx

2024-09-06 09:30 UTC, SWJTU-ZhangLei commented
run buildall

2024-09-06 14:18 UTC, SWJTU-ZhangLei commented
run buildall

2024-09-12 13:10 UTC, SWJTU-ZhangLei commented
run buildall

2024-09-13 13:30 UTC, SWJTU-ZhangLei commented
run buildall

2024-09-14 02:33 UTC, SWJTU-ZhangLei commented
run buildall

2024-09-14 06:20 UTC, SWJTU-ZhangLei commented
run buildall

2024-09-14 08:47 UTC, SWJTU-ZhangLei commented
run cloud_p0

2024-09-18 08:29 UTC, SWJTU-ZhangLei commented
run buildall

2024-09-23 12:03 UTC, gavinchou commented on cloud/src/meta-service/txn_lazy_committer.cpp
> -                        return;
is this a bug?

2024-09-23 12:19 UTC, gavinchou requested changes

2024-09-23 12:19 UTC, gavinchou commented on cloud/src/meta-service/meta_service_txn.cpp
> +        LOG(INFO) << "txn_id=" << txn_id << " fallthrough commit_txn_eventually";
简化一些这里的代码, 目前不太好理解. 按照下述条件来进行判断.
能走到eventual条件应该是以下其中之一:
1. request显式set lazy = true 并且 不是2pc提交
2. request没有lazy 字段并且config:enable_lazy 并且 rowset.size 超过 conf:rowsets_thresold 并且 不是2pc提交
3. request没有lazy 字段并且config:enable_lazy 并且 rowset.size 没超过 conf:rowsets_thresold 但是immediate_commit失败 并且 不是2pc提交

2024-09-24 08:59 UTC, SWJTU-ZhangLei commented on cloud/src/meta-service/txn_lazy_committer.cpp
> -                        return;
> is this a bug?

yes, i have fixed

2024-09-24 09:59 UTC, SWJTU-ZhangLei commented
run buildall

2024-09-24 13:37 UTC, SWJTU-ZhangLei commented
run buildall

2024-09-28 17:54 UTC, gavinchou approved these changes

2024-09-29 07:35 UTC, Yukang-Lian approved these changes

2024-09-29 07:36 UTC, merged