[enhancement](cloud) dump error file when footer parse failure
apache/doris pull request #40943
Opened 2024-09-18 14:10 UTC by freemandealer

dump error file to local disk in cloud mode for better debug. limit the error file directory to avoid disk capacity problem.

## Proposed changes

Issue Number: close #xxx

2024-09-18 14:12 UTC, freemandealer commented
run buildall

2024-09-18 14:26 UTC, gavinchou requested changes

2024-09-18 14:26 UTC, gavinchou commented on be/src/olap/rowset/segment_v2/segment.cpp
> +    std::string file_path = dir_path + std::to_string(cur_time) + "_" + ss.str();
use this pattern to get rid of duplicated dumps (check existence before read and write)
```
    std::string file_path = dir_path + this->_rowset_id.to_string() + "_" + segment_id + "_" + offset + "_" + size;
```

2024-09-20 11:18 UTC, freemandealer commented
run buildall

2024-09-20 13:23 UTC, freemandealer commented
run buildall

2024-09-23 06:44 UTC, gavinchou approved these changes, later dismissed

2024-09-23 07:10 UTC, Yukang-Lian approved these changes

2024-09-23 13:34 UTC, freemandealer commented
run beut

2024-09-24 02:46 UTC, freemandealer commented
run buildall

2024-09-24 06:59 UTC, freemandealer commented
run buildall

2024-09-24 08:12 UTC, freemandealer commented
run beut

2024-09-24 11:35 UTC, freemandealer commented
run buildall

2024-09-28 18:00 UTC, gavinchou approved these changes

2024-09-29 03:25 UTC, merged