[chore](light-schema-change) Enable light scghema change by force
apache/doris pull request #40967
Opened 2024-09-19 04:10 UTC by TangSiyang2001

## Proposed changes

We enable light scghema change by force in this PR, no matter what users set.

For compability of user facade, do not forbid setting `enbale_light_schema_change=false`.

2024-09-19 04:11 UTC, TangSiyang2001 commented
run buildall

2024-10-22 09:47 UTC, TangSiyang2001 commented
run buildall

2024-10-22 11:45 UTC, TangSiyang2001 commented
run buildall

2024-10-24 03:15 UTC, TangSiyang2001 commented
run buildall

2024-10-25 00:39 UTC, TangSiyang2001 commented
run p0

2024-10-25 01:57 UTC, TangSiyang2001 commented
run feut

2024-10-27 17:43 UTC, gavinchou approved these changes

2024-10-28 01:22 UTC, TangSiyang2001 commented
run p0

2024-10-28 03:20 UTC, TangSiyang2001 commented
run buildall

2024-10-28 09:46 UTC, dataroaring requested changes
Add case for non-light-sc upgrade.

2025-04-28 00:13 UTC, closed without merging