[fix](schema change) fix delete predicate incorrect comparisons result with empty strings during schema change
apache/doris pull request #41064
Opened 2024-09-20 08:59 UTC by luwei16

2024-09-20 09:07 UTC, luwei16 commented
run buildall

2024-09-21 01:32 UTC, dataroaring commented
run buildall

2024-09-21 03:23 UTC, gavinchou requested changes

2024-09-21 03:23 UTC, gavinchou commented on regression-test/data/schema_change_p0/test_schema_change_delete.out
no need  to add an empty file, just use `result = sql """` to check result.

2024-09-21 03:23 UTC, gavinchou commented on regression-test/suites/schema_change_p0/test_schema_change_delete.groovy
> +    qt_select "select * from ${tableName}"
use `result = sql """` to get rid of empty .out file.

2024-09-24 08:57 UTC, luwei16 commented
run p0

2024-09-25 07:07 UTC, luwei16 commented
run buildall

2024-09-26 02:26 UTC, dataroaring approved these changes
LGTM

2024-09-26 02:33 UTC, gavinchou approved these changes

2024-09-26 02:35 UTC, merged