Support batch delete syntax in fe and add pass the delete infomation to be
apache/doris pull request #4141
Opened 2020-07-22 09:41 UTC by yangzhg

## Proposed changes

Part of Issues #4051
Add batch delete synatx support, support the syntax described in  Issues #4051 
Bring the delete infomation to be

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on [Doris's issues](https://github.com/apache/incubator-doris/issues), and have described the bug/feature there in detail
- [x] Commit messages in my PR start with the related issues ID
- [x] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this change need a document change, I have updated the document
- [x] Any dependent changes have been merged

2020-07-28 01:45 UTC, yangzhg commented on be/src/exec/broker_scan_node.cpp
> +        return Status::InvalidArgument("cannot support delete condition in APPEND or DELETE load.");
delete on condition is for MERGE load,  APPEND is append all data in this load, DELETE is drop all data in this load, Merge is delete all data match delete condition and append others

2020-07-28 01:52 UTC, yangzhg commented on fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
> +            this.execMemLimit = stmt.getExecMemLimit();
execMemLimit in all load's property except routine load, add this just for keeping syntax consist.

2020-07-28 04:41 UTC, yangzhg commented on fe/fe-core/pom.xml
> +                    <expectedConflicts>7</expectedConflicts>
this will be 0 after the he

2020-07-31 01:52 UTC, imay requested changes
Should discuss about this feature.

2020-08-10 03:17 UTC, closed without merging