[Fix](Rowset Id) Use a randomly generated rowset ID to handle memory write failures
apache/doris pull request #42949
Opened 2024-10-30 17:26 UTC by Yukang-Lian

## Proposed changes

Issue Number: close #xxx

2024-10-31 02:28 UTC, cambyzju commented
1、这个改动很基础，有什么合理的场景，需要这么改吗？
2、随机生成rowset id会导致跟其他地方的元数据等对不上的风险吗？

2024-10-31 06:24 UTC, gavinchou commented on be/src/olap/olap_common.h
> +                }();
```suggestion
                std::mt19937_64 rg(std::random_device {}());
                high = std::uniform_int_distribution<int64_t>()(rg);
```

2024-10-31 06:28 UTC, gavinchou requested changes

2024-10-31 06:28 UTC, gavinchou commented on be/src/olap/olap_common.h
> +                    return std::uniform_int_distribution<int64_t>()(rg);
use the original rowsetid generator instead of a rng here.

2024-10-31 06:31 UTC, Yukang-Lian commented
> 1、这个改动很基础，有什么合理的场景，需要这么改吗？ 2、随机生成rowset id会导致跟其他地方的元数据等对不上的风险吗？

1. 当内存写飞了之后be会起不来，这样避免了起不来的问题。2. 随机生成需要修改，统一通过rowset id生成的方法来生成。

2024-10-31 09:03 UTC, Yukang-Lian commented
run buildall

2024-11-04 16:27 UTC, gavinchou commented on be/src/olap/olap_common.h
> +                high = unique_rowset_id_next_high();
why not just
```
RowsetId rsid = next_rowset_id();
init(1, rsid.high, 0, 0);
```
No need to introduce an extra function `UniqueRowsetIdGenerator::next_high()`

2024-11-05 18:03 UTC, Yukang-Lian commented
run buildall

2024-11-07 12:23 UTC, Yukang-Lian commented
run buildall

2024-11-11 16:33 UTC, Yukang-Lian commented
run buildall

2024-11-11 19:17 UTC, Yukang-Lian commented
run beut

2024-11-12 02:20 UTC, gavinchou approved these changes

2024-11-12 05:17 UTC, Yukang-Lian commented
run p0

2024-11-12 05:17 UTC, Yukang-Lian commented
run beut

2024-11-12 07:42 UTC, Yukang-Lian commented
run beut

2024-11-12 13:33 UTC, Yukang-Lian commented
run beut

2024-11-12 16:01 UTC, Yukang-Lian commented
run beut

2024-11-13 11:05 UTC, Yukang-Lian commented
run buildall

2024-11-13 15:33 UTC, Yukang-Lian commented
run beut

2024-11-14 05:12 UTC, Yukang-Lian commented
run buildall

2024-11-14 09:13 UTC, yagagagaga approved these changes

2024-11-14 09:26 UTC, merged

2025-05-14 11:31 UTC, XLPE commented
> > 1、这个改动很基础，有什么合理的场景，需要这么改吗？ 2、随机生成rowset id会导致跟其他地方的元数据等对不上的风险吗？
> 
> 1. 当内存写飞了之后be会起不来，这样避免了起不来的问题。2. 随机生成需要修改，统一通过rowset id生成的方法来生成。
我们线上在一次coredump之后也是遇到这个错误。错误如下：
[libprotobuf ERROR /home/jenkins_agent/workspace/BigDataComponent_doris-arm/thirdparty/src/protobuf-21.11/src/google/protobuf/message_lite.cc:133] Can't parse message of type "doris.TabletMetaPB" because it is missing required fields: rs_metas[1].rowset_id

当前这个pr还是跳过不了BE起不来的问题，最好的方案应该是跳过有问题的tablet，然后等待副本均衡