[feture](inverted index) Adding Storage Format V3 for Inverted Index
apache/doris pull request #44414
Opened 2024-11-21 09:59 UTC by zzzxl1993

### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

2024-11-25 02:10 UTC, airborne12 commented on be/src/olap/rowset/beta_rowset.cpp
> +        format_str = "Unknown";
return Error status here

2024-11-25 02:11 UTC, airborne12 commented on be/src/olap/rowset/segment_v2/inverted_index_file_writer.cpp
> +    output->writeInt(_storage_format);
may be we can change function name from create_output_stream_v2 to create_output_stream now

2024-11-25 02:16 UTC, airborne12 commented on gensrc/proto/olap_file.proto
> +    V3 = 3;
why 3 not 2?

2024-11-25 02:17 UTC, airborne12 reviewed
We need some FE UT test

2024-11-25 15:00 UTC, zzzxl1993 commented
run buildall

2024-11-26 02:24 UTC, zzzxl1993 commented
run buildall

2024-11-28 04:14 UTC, zzzxl1993 commented
run buildall

2024-11-28 06:05 UTC, zzzxl1993 commented
run buildall

2024-11-28 08:03 UTC, zzzxl1993 commented
run buildall

2024-11-29 08:25 UTC, zzzxl1993 commented
run buildall

2024-12-02 03:31 UTC, airborne12 commented
run buildall

2024-12-02 03:37 UTC, airborne12 submitted a review, later dismissed
LGTM

2024-12-02 07:10 UTC, csun5285 approved these changes
LGTM

2024-12-02 11:17 UTC, airborne12 requested changes
Need to add inverted index storage format v3 in CreateReplicaTask.java

2024-12-02 13:10 UTC, zzzxl1993 commented
run buildall

2024-12-02 14:44 UTC, zzzxl1993 commented
run buildall

2024-12-03 02:30 UTC, zzzxl1993 commented
run buildall

2024-12-03 12:04 UTC, zzzxl1993 commented
run buildall

2024-12-03 14:23 UTC, zzzxl1993 commented
run buildall

2024-12-04 02:22 UTC, airborne12 commented
run p1

2024-12-04 02:23 UTC, airborne12 commented
run cloud_p1

2024-12-04 04:05 UTC, airborne12 approved these changes, later dismissed
LGTM

2024-12-04 04:24 UTC, zzzxl1993 commented
run buildall

2024-12-04 07:05 UTC, airborne12 approved these changes
LGTM

2024-12-04 09:09 UTC, qidaye approved these changes
LGTM

2024-12-04 09:12 UTC, merged