[feat](test) add fe ut for bf index create table
apache/doris pull request #44973
Opened 2024-12-04 03:48 UTC by airborne12

### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

2024-12-04 03:48 UTC, airborne12 commented
run buildall

2024-12-04 04:04 UTC, airborne12 commented
run buildall

2024-12-04 10:38 UTC, airborne12 commented
run buildall

2024-12-05 09:40 UTC, airborne12 commented
run buildall

2024-12-06 03:14 UTC, eldenmoon approved these changes
LGTM

2024-12-06 03:31 UTC, csun5285 requested changes

2024-12-06 03:31 UTC, csun5285 commented on fe/fe-core/src/main/java/org/apache/doris/analysis/IndexDef.java
> +                parseAndValidateProperty(properties, NGRAM_SIZE_KEY, MIN_NGRAM_SIZE, MAX_NGRAM_SIZE);
need to modify `IndexDefinition.java`

2024-12-06 06:16 UTC, qidaye approved these changes
LGTM

2024-12-06 08:13 UTC, merged