Enhance the usability of Load operation
apache/doris pull request #490
Opened 2019-01-01 10:21 UTC by morningman

1. Add broker load error hub
A broker load error hub will collect error messages in load process and saves them as a file to the specified remote storage via broker. In case that in broker/min/streaming load process, user may not be able to access the error log file in Backend directly.
We also add a new header option: 'enable_hub' in streaming load request, and default is false. Because if we enable the broker load error hub, it will significantly slow down the processing speed of streaming load, due to the visit of remote storage via broker. So use can disable the error load hub using this header option, to avoid slowing down the load speed.

2. Show load error logs by using SHOW LOAD WARNINGS stmt
We also provide a more easy way to get load error logs. We implement 'SHOW LOAD WARNINGS ON 'url'' stmt to show load error logs directly. The 'url' in stmt is provided in 'SHOW  LOAD' stmt.
eg:
show load warnings on "http://192.168.1.1:8040/api/_load_error_log?file=__shard_2/error_log_xxx";

3. Support now() function in broker load
User can mapping a column to now() in broker load stmt, which means this column will be filled with time when the ETL started.

4. Support more types of wildcard in broker load
Currently, we only support wildcard '*' to match the file names. wildcard like '/path/to/20190[1-4]*' is not support.

2019-01-02 02:33 UTC, imay requested changes

2019-01-02 02:33 UTC, imay commented on fe/src/main/java/org/apache/doris/load/BrokerLoadErrorHub.java
> +package org.apache.doris.load;
license header

2019-01-02 08:31 UTC, imay commented on fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/common/WildcardURI.java
> +package org.apache.doris.common;
license header

2019-01-02 08:31 UTC, imay commented on gensrc/thrift/FrontendService.thrift
> +    16: optional string enable_hub
You should use `boolean` instead of `string` to a switch filed

However, I think you'd better not to add this filed.

2019-01-02 09:19 UTC, morningman commented on fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/common/WildcardURI.java
> +package org.apache.doris.common;
done

2019-01-03 10:20 UTC, morningman commented on be/src/http/download_action.cpp
> -    Status status = check_log_path_is_allowed(absolute_path);
add it back

2019-01-03 10:20 UTC, morningman commented on be/src/util/broker_load_error_hub.cpp
> +    delete _broker_writer;
moved

2019-01-03 10:20 UTC, morningman commented on be/src/util/broker_load_error_hub.h
> +    BrokerWriter* _broker_writer;
done

2019-01-03 10:54 UTC, imay submitted a review, later dismissed

2019-01-03 11:06 UTC, imay approved these changes

2019-01-03 11:07 UTC, merged