[enhancement]improve performance of json load
apache/doris pull request #5055
Opened 2020-12-10 02:33 UTC by yangzhg

## Proposed changes

There are two points that affect performance in the current json load:
1 json is actually a traversal operation for searching by key. We call HasMember and operator[] twice, and need to traverse twice
2 If you use a string as the key to find the json object, strlen will be called every time, so the number of calls to strlen is the row number * column number

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [] I have create an issue on (Fix #5054), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

2020-12-10 06:17 UTC, HappenLee commented on be/src/exec/json_scanner.cpp
>      // Get one line
Why delete the reader timer？

2020-12-10 06:44 UTC, HappenLee commented on be/src/exec/json_scanner.cpp
> -    SCOPED_TIMER(_read_timer);
why delete this read_timer? Maybe should keep the same with orc scanner

2020-12-10 06:44 UTC, HappenLee commented on be/src/exec/json_scanner.cpp
> +    SCOPED_TIMER(_read_timer);
Add a new timer name 'parse json timer' to track the parse json time.

2020-12-10 06:45 UTC, HappenLee requested changes
should revise some code of timer

2020-12-14 02:53 UTC, HappenLee approved these changes

2020-12-14 08:00 UTC, morningman approved these changes
LGTM

2020-12-15 01:27 UTC, merged