add create file hard link for rowset
apache/doris pull request #506
Opened 2019-01-07 12:34 UTC by kangpinghuang

Add two rowset interface to support initialization:
1. add create_hard_links to create new name hard links
2. add remove_old_files to delete old name files

2019-01-07 12:38 UTC, kangpinghuang commented
Resolve ISSUE #507

2019-01-07 12:51 UTC, chaoyli requested changes

2019-01-07 12:51 UTC, chaoyli commented on be/src/olap/rowset/segment_group.cpp
> +bool SegmentGroup::create_hard_links() {
No gc when failed.

2019-01-08 08:07 UTC, chaoyli approved these changes

2019-01-08 08:07 UTC, merged