[optimization] use replace top instead of push pop in priority #5312
apache/doris pull request #5313
Opened 2021-01-28 09:30 UTC by stdpain

## Proposed changes

referen to #5312 

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [x] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If these changes need document changes, I have updated the document
- [x] Any dependent changes have been merged

2021-01-28 10:35 UTC, yangzhg commented on be/src/util/sort_heap.h
> +    bool isValid() const { return !_queue.empty(); }
```suggestion
    bool is_valid() const { return !_queue.empty(); }
```

2021-01-28 10:37 UTC, yangzhg commented on be/src/exec/topn_node.h
> +    boost::scoped_ptr<SortingHeap<Tuple*, std::vector<Tuple*>, TupleRowComparator>> _priority_queue;
```suggestion
    std::unique_ptr<SortingHeap<Tuple*, std::vector<Tuple*>, TupleRowComparator>> _priority_queue;
```

2021-01-29 07:24 UTC, HappenLee requested changes
some code need change~

2021-02-01 08:13 UTC, stdpain commented on be/src/exec/topn_node.h
> +    std::unique_ptr<SortingHeap<Tuple*, std::vector<Tuple*>, TupleRowComparator>> _priority_queue;
SortingHeap is essentially a priority queue, but with a replace_top interface, so naming it as a priority queue is more friendly to people who come into contact with this code for the first time

2021-02-02 07:12 UTC, HappenLee commented on be/src/util/sort_heap.h
> +        auto top(std::move(*begin));
remove unless std::move.

2021-02-02 07:13 UTC, HappenLee commented on be/src/util/sort_heap.h
> +template <typename T, typename _Sequence, typename _Compare>
no need add "_" in type name

2021-02-02 07:34 UTC, HappenLee requested changes
some little thing need to change

2021-02-03 11:25 UTC, HappenLee approved these changes
@stdpain LGTM

2021-02-03 12:13 UTC, morningman approved these changes
LGTM

2021-02-04 01:21 UTC, merged