Fix bug doris on es
apache/doris pull request #5363
Opened 2021-02-05 07:18 UTC by e0c9

## Proposed changes

when ES field value is null.  An exception occurs when parsing the field.
such as:
```
Scanner[0] process failed. status=Expected value of type: BIGINT; but found type: Null Type; Docuemnt source slice is : null 
```

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] If these changes need document changes, I have updated the document
- [] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-02-19 02:09 UTC, yangzhg approved these changes, later dismissed
LGTM

2021-02-19 03:05 UTC, wuyunfeng commented on be/src/exec/es/es_scroll_parser.cpp
> +        if (col.IsNull()) {
Plz add some comments for this

2021-02-19 03:06 UTC, wuyunfeng requested changes
I left some minor comment

2021-02-20 06:29 UTC, e0c9 commented on be/src/exec/es/es_scroll_parser.cpp
> +        if (col.IsNull()) {
done

2021-02-22 08:10 UTC, yangzhg approved these changes
LGTM

2021-02-23 02:40 UTC, wuyunfeng approved these changes

2021-02-23 02:42 UTC, merged