[Feature] Clean up old sync jobs regularly
apache/doris pull request #7061
Opened 2021-11-09 08:52 UTC by xy720

## Proposed changes

#7060 

Each job that has been stopped for more than 3 days(set with Config.label_keep_max_second) will be permanently cleaned up.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #7060 ) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-11-09 13:01 UTC, pengxiangyu requested changes

2021-11-10 02:46 UTC, xy720 commented on fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncJobManager.java
> +                    Map<String, List<SyncJob>> map = dbIdToJobNameToSyncJobs.get(syncJob.getDbId());
ok

2021-11-10 02:46 UTC, xy720 commented on fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncChecker.java
> +        this.syncJobManager.cleanOldSyncJobs();
ok. done

2021-11-10 02:48 UTC, pengxiangyu approved these changes

2021-11-11 15:15 UTC, morningman approved these changes
LGTM

2021-11-12 02:53 UTC, merged