[feature](cold-hot) support remote storage
apache/doris pull request #8532
Opened 2022-03-18 11:30 UTC by qidaye

# Proposed changes

Issue Number: close #8531 

1. Support add/drop/show/alter remote storage
2. Support create olap table with remote storage

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
4. Has unit tests been added: (Yes/No/No Need)
5. Has document been added or modified: (Yes/No/No Need)
6. Does it need to update dependencies: (Yes/No)
7. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-03-21 04:10 UTC, pengxiangyu requested changes

2022-03-21 04:10 UTC, pengxiangyu commented on fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
>              return oldDataProperty;
如果是SSD->HDD，remote storage是空的。

2022-03-21 04:10 UTC, pengxiangyu commented on fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
> +            throw new AnalysisException("Invalid data property, " +
SSD->HDD的情况下不需要remote storage

2022-03-24 09:20 UTC, pengxiangyu requested changes

2022-03-24 09:20 UTC, pengxiangyu commented on fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
> +                hasColdMedium = true;
coldMedium有可能是HDD。

2022-03-24 09:20 UTC, pengxiangyu commented on fe/fe-core/src/main/java/org/apache/doris/catalog/RemoteStorageMgr.java
> +            String storageName = clause.getStorageName();
storage_name是key，不要引入空格，这里和下面的modify需要做一下trim。

2022-03-28 10:23 UTC, pengxiangyu approved these changes
LGTM

2022-03-29 00:21 UTC, yiguolei commented
Backup Restore has also defined similar remote storage logic. And Cold Hot defines another one. Could we unify these concepts?

2022-04-01 09:46 UTC, qidaye commented
This PR is closed, please refer to #8808

2022-04-01 09:46 UTC, closed without merging