[Vectorized] support string type cast to bitmap
apache/doris pull request #8614
Opened 2022-03-23 08:31 UTC by zhangstar333

# Proposed changes

Issue Number: close #8613 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-04-02 06:52 UTC, HappenLee commented on be/src/vec/functions/function_cast.h
> +    template <typename Additions = void*>
remove the template `Additions`

2022-04-02 07:09 UTC, zhangstar333 commented on be/src/vec/functions/function_cast.h
> +    template <typename Additions = void*>
done

2022-04-02 07:10 UTC, HappenLee approved these changes
LGTM

2022-04-02 13:28 UTC, morningman commented
Why should we support converting bitmap to string?

2022-04-02 16:12 UTC, HappenLee commented
> Why should we support converting bitmap to string?

This is to be compatible with regression testing to not cause coredump. Now directly prohibiting bitmap, HLL cast to string, which is afraid of introducing new problems.

2022-04-03 03:13 UTC, morningman requested changes
I think we should not allow to convert string to bitmap or vice versa, for both vec and non-vec

2022-04-06 03:04 UTC, closed without merging