[Improve]Remove http v1 code and disable mini load by default
apache/doris pull request #8701
Opened 2022-03-28 10:00 UTC by hf200012

1. http v2 has been actually tested in production, and it is completely replaceable to have http code. In order to simplify code maintenance, remove the previous http part of the code
2. The mini load function can completely pass the stream load function. In the next version, the mini load transition is disabled through the switch, and then this code is removed in the subsequent version. If users need to use the mini load function, they can add  in fe.conf `disable_mini_load=false` to enable, the default is disabled

# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes)
2. Has unit tests been added: (No Need)
4. Has document been added or modified: (Yes)
5. Does it need to update dependencies: (No)
6. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-03-29 02:19 UTC, yiguolei commented on fe/fe-core/src/main/java/org/apache/doris/PaloFe.java
> +            httpServer2.setMaxHttpPostSize(Config.jetty_server_max_http_post_size);
httpServer is ok

2022-03-29 02:22 UTC, yiguolei commented on fe/fe-core/src/test/java/org/apache/doris/http/HttpAuthManagerTest.java
> +        sessionIds.clear ();
clear()

2022-03-29 02:23 UTC, yiguolei commented on fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBDebugger.java
> +        httpServer.setAcceptors(Config.jetty_server_acceptors);
Why set these parameters but not set them in the past?

2022-03-29 02:24 UTC, yiguolei commented on fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/LoadAction.java
> +        if(!Config.disable_mini_load) {
it is better to use if (condition) xxx not use if (!condition)

2022-03-29 02:26 UTC, yiguolei commented on fe/fe-core/src/main/java/org/apache/doris/common/Config.java
> +    public static boolean disable_mini_load = true;
Missing @ConfField?

2022-04-02 03:28 UTC, yiguolei submitted a review, later dismissed
LGTM

2022-04-02 04:15 UTC, morningman requested changes
Please don't put multiple types of changes into one PR.
Please split this PR into 3 parts:
1. disable mini load
2. remove http v1
3. modify http thread config

2022-04-06 01:48 UTC, closed without merging