[Enhancement](Join) Construct output tuple in join node
apache/doris pull request #9954
Opened 2022-06-04 14:19 UTC by EmmyMiao87

# Proposed changes

Closed #7901

## Problem Summary

In a vectorized scenario, the query plan will generate a new tuple for the join node.
This tuple mainly describes the output schema of the join node.
Adding this tuple mainly solves the problem that the input schema of the join node is different from the output schema.
For example:
1. The case where the null side column caused by outer join is converted to nullable.
2. The projection of the outer tuple.

* Since this function is unavailable for non-vectorized code,
the new attributes vOutputTupleDesc and vSrcToOutputSMap accompanying this function are unique to vectorization.*

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-06-04 15:23 UTC, morningman commented
Could you add some ut for this?

2022-06-13 04:19 UTC, HappenLee commented on gensrc/thrift/PlanNodes.thrift
> +  7: optional list<Exprs.TExpr> srcExprList
use `src_expr_list`

2022-06-20 11:43 UTC, morrySnow commented on gensrc/thrift/PlanNodes.thrift
> +  8: optional Types.TTupleId voutput_tuple_id
move it to TPlanNode

2022-06-22 14:08 UTC, morningman commented
Fixed in #10323

2022-06-24 11:10 UTC, morningman approved these changes
LGTM

2022-06-26 01:54 UTC, morningman requested changes
hold for a second, there is still some problem

2022-06-27 04:01 UTC, EmmyMiao87 commented
The contents of this pr are merged into the new pr#10437  and submitted together

2022-06-27 04:02 UTC, closed without merging